// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import (
	"context"
	"fmt"
)

type GetBadgeParams struct {
	User     string
	Interval string
	Filter   string
}

// GetBadge retrieves badge data for a user, interval, and filter in a format compatible with Shields.io. Use `interval` to choose the aggregation period and `filter` to select an entity such as a project or language; public data access must be enabled for the user.
//
// Retrieve total time for a given entity (e.g. a project) within a given range (e.g. one week) in a format compatible with [Shields.io](https://shields.io/endpoint). Requires public data access to be allowed.
//
// Parameters:
//
//	user: User ID to fetch data for
//	interval: Interval to aggregate data for
//	filter: Filter to apply (e.g. 'project:wakapi' or 'language:Go')
func GetBadge(ctx context.Context, clientConfig ClientConfig, params GetBadgeParams, opts ...RequestOption) (*V1BadgeData, error) {
	user := params.User
	interval := params.Interval
	filter := params.Filter

	resp, err := DoCfg[V1BadgeData](ctx, &clientConfig, "GET", fmt.Sprintf("/compat/shields/v1/%s/%s/%s", EncodePathSegment(user), EncodePathSegment(interval), EncodePathSegment(filter)), &RequestOpts{
		OperationID: "GetBadge",
		Options:     opts,
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}
