// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import "context"

type PostDiagnosticsParams struct {
	Architecture *string
	CliVersion   *string
	Id           *int64
	Logs         *string
	Platform     *string
	Plugin       *string
	Stacktrace   *string
}

// PostDiagnostics submits a diagnostics object sent by the WakaTime CLI. Include diagnostic details such as the CLI version, platform, logs, or stack trace to provide context for the reported issue.
//
// Parameters:
//
//	architecture: Optional `string` value serialized in the `architecture` wire
//	field.
//	cliVersion: Optional `string` value serialized in the `cli_version` wire
//	field.
//	id: Optional `integer` value serialized in the `id` wire field.
//	logs: Optional `string` value serialized in the `logs` wire field.
//	platform: Optional `string` value serialized in the `platform` wire field.
//	plugin: Optional `string` value serialized in the `plugin` wire field.
//	stacktrace: Optional `string` value serialized in the `stacktrace` wire
//	field.
func PostDiagnostics(ctx context.Context, clientConfig ClientConfig, params PostDiagnosticsParams, opts ...RequestOption) (any, error) {
	architecture := params.Architecture
	cliVersion := params.CliVersion
	id := params.Id
	logs := params.Logs
	platform := params.Platform
	plugin := params.Plugin
	stacktrace := params.Stacktrace

	_, err := DoEmptyCfg(ctx, &clientConfig, "POST", "/plugins/errors", &RequestOpts{
		Body: map[string]any{
			"architecture": architecture,
			"cli_version":  cliVersion,
			"id":           id,
			"logs":         logs,
			"platform":     platform,
			"plugin":       plugin,
			"stacktrace":   stacktrace,
		},
		OperationID: "PostDiagnostics",
		Options:     opts,
	})
	if err != nil {
		return nil, err
	}
	return nil, nil
}
