// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import (
	"context"
	"fmt"
)

type GetHeartbeatsParams struct {
	User string
	Date string
}

// GetHeartbeats lists a user's heartbeats for a specified date. Provide `date` to select the day and `user` to identify whose activity to retrieve.
//
// Parameters:
//
//	user: Username (or current)
//	date: Date
func GetHeartbeats(ctx context.Context, clientConfig ClientConfig, params GetHeartbeatsParams, opts ...RequestOption) (*V1HeartbeatsResult, error) {
	user := params.User
	date := params.Date

	resp, err := DoCfg[V1HeartbeatsResult](ctx, &clientConfig, "GET", fmt.Sprintf("/compat/wakatime/v1/users/%s/heartbeats", EncodePathSegment(user)), &RequestOpts{
		Query: map[string]any{
			"date": QueryValue{Value: date, Style: "form", Explode: true},
		},
		OperationID: "GetHeartbeats",
		Options:     opts,
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

type PostHeartbeat3Params struct {
	User             string
	AiInputTokens    *int64
	AiLineChanges    *int64
	AiOutputTokens   *int64
	AiPromptLength   *int64
	AiSession        *string
	Branch           *string
	Category         *string
	CreatedAt        *float64
	Cursorpos        *int64
	Editor           *string
	Entity           *string
	HumanLineChanges *int64
	IsWrite          *bool
	Language         *string
	LineAdditions    *int64
	LineDeletions    *int64
	Lineno           *int64
	Lines            *int64
	Machine          *string
	OperatingSystem  *string
	Project          *string
	ProjectRootCount *int64
	Time             *float64
	Type_            *string
	UserAgent        *string
}

// PostHeartbeat3 creates a single heartbeat for a user from a WakaTime-compatible request. Send the heartbeat as a JSON object; `created_at` is numeric, and the `editor` field is ignored.
//
// Parameters:
//
//	user: Username (or current)
//	aiInputTokens: Optional `integer` value serialized in the `ai_input_tokens`
//	wire field.
//	aiLineChanges: Optional `integer` value serialized in the `ai_line_changes`
//	wire field.
//	aiOutputTokens: Optional `integer` value serialized in the
//	`ai_output_tokens` wire field.
//	aiPromptLength: Optional `integer` value serialized in the
//	`ai_prompt_length` wire field.
//	aiSession: Optional `string` value serialized in the `ai_session` wire
//	field.
//	branch: Optional `string` value serialized in the `branch` wire field.
//	category: Optional `string` value serialized in the `category` wire field.
//	createdAt: https://gorm.io/docs/conventions.html#CreatedAt
//	cursorpos: Optional `integer` value serialized in the `cursorpos` wire
//	field.
//	editor: ignored because editor might be parsed differently by wakatime
//	entity: Optional `string` value serialized in the `entity` wire field.
//	humanLineChanges: Optional `integer` value serialized in the
//	`human_line_changes` wire field.
//	isWrite: Optional `boolean` value serialized in the `is_write` wire field.
//	language: Optional `string` value serialized in the `language` wire field.
//	lineAdditions: Optional `integer` value serialized in the `line_additions`
//	wire field.
//	lineDeletions: Optional `integer` value serialized in the `line_deletions`
//	wire field.
//	lineno: Optional `integer` value serialized in the `lineno` wire field.
//	lines: Optional `integer` value serialized in the `lines` wire field.
//	machine: ignored because wakatime api doesn't return machines currently
//	operatingSystem: ignored because os might be parsed differently by wakatime
//	project: Optional `string` value serialized in the `project` wire field.
//	projectRootCount: Optional `integer` value serialized in the
//	`project_root_count` wire field.
//	time: note: on sqlite, table will have an additional column `time_real`,
//	introduced "manually" by migration 20260111 see
//	https://github.com/muety/wakapi/issues/882 for details
//	type_: Optional `string` value serialized in the `type` wire field.
//	userAgent: Optional `string` value serialized in the `user_agent` wire
//	field.
func PostHeartbeat3(ctx context.Context, clientConfig ClientConfig, params PostHeartbeat3Params, opts ...RequestOption) (any, error) {
	user := params.User
	aiInputTokens := params.AiInputTokens
	aiLineChanges := params.AiLineChanges
	aiOutputTokens := params.AiOutputTokens
	aiPromptLength := params.AiPromptLength
	aiSession := params.AiSession
	branch := params.Branch
	category := params.Category
	createdAt := params.CreatedAt
	cursorpos := params.Cursorpos
	editor := params.Editor
	entity := params.Entity
	humanLineChanges := params.HumanLineChanges
	isWrite := params.IsWrite
	language := params.Language
	lineAdditions := params.LineAdditions
	lineDeletions := params.LineDeletions
	lineno := params.Lineno
	lines := params.Lines
	machine := params.Machine
	operatingSystem := params.OperatingSystem
	project := params.Project
	projectRootCount := params.ProjectRootCount
	time := params.Time
	type_ := params.Type_
	userAgent := params.UserAgent

	_, err := DoEmptyCfg(ctx, &clientConfig, "POST", fmt.Sprintf("/compat/wakatime/v1/users/%s/heartbeats", EncodePathSegment(user)), &RequestOpts{
		Body: map[string]any{
			"ai_input_tokens":    aiInputTokens,
			"ai_line_changes":    aiLineChanges,
			"ai_output_tokens":   aiOutputTokens,
			"ai_prompt_length":   aiPromptLength,
			"ai_session":         aiSession,
			"branch":             branch,
			"category":           category,
			"created_at":         createdAt,
			"cursorpos":          cursorpos,
			"editor":             editor,
			"entity":             entity,
			"human_line_changes": humanLineChanges,
			"is_write":           isWrite,
			"language":           language,
			"line_additions":     lineAdditions,
			"line_deletions":     lineDeletions,
			"lineno":             lineno,
			"lines":              lines,
			"machine":            machine,
			"operating_system":   operatingSystem,
			"project":            project,
			"project_root_count": projectRootCount,
			"time":               time,
			"type":               type_,
			"user_agent":         userAgent,
		},
		OperationID: "PostHeartbeat3",
		Options:     opts,
	})
	if err != nil {
		return nil, err
	}
	return nil, nil
}

type PostHeartbeat7Params struct {
	User string
	Body []ModelsHeartbeat
}

// PostHeartbeat7 creates multiple heartbeats for a user from a WakaTime-compatible request. Send a JSON array of heartbeat objects; each object can include fields such as `entity`, `language`, and `created_at`.
//
// Parameters:
//
//	user: Username (or current)
func PostHeartbeat7(ctx context.Context, clientConfig ClientConfig, params PostHeartbeat7Params, opts ...RequestOption) (any, error) {
	user := params.User
	body := params.Body

	_, err := DoEmptyCfg(ctx, &clientConfig, "POST", fmt.Sprintf("/compat/wakatime/v1/users/%s/heartbeats.bulk", EncodePathSegment(user)), &RequestOpts{
		Body:        body,
		OperationID: "PostHeartbeat7",
		Options:     opts,
	})
	if err != nil {
		return nil, err
	}
	return nil, nil
}

type PostHeartbeatParams struct {
	AiInputTokens    *int64
	AiLineChanges    *int64
	AiOutputTokens   *int64
	AiPromptLength   *int64
	AiSession        *string
	Branch           *string
	Category         *string
	CreatedAt        *float64
	Cursorpos        *int64
	Editor           *string
	Entity           *string
	HumanLineChanges *int64
	IsWrite          *bool
	Language         *string
	LineAdditions    *int64
	LineDeletions    *int64
	Lineno           *int64
	Lines            *int64
	Machine          *string
	OperatingSystem  *string
	Project          *string
	ProjectRootCount *int64
	Time             *float64
	Type_            *string
	UserAgent        *string
}

// PostHeartbeat submits a single heartbeat containing activity data. Send the heartbeat as a JSON object, using fields such as `entity`, `category`, and `language` to describe the recorded activity.
//
// Parameters:
//
//	aiInputTokens: Optional `integer` value serialized in the `ai_input_tokens`
//	wire field.
//	aiLineChanges: Optional `integer` value serialized in the `ai_line_changes`
//	wire field.
//	aiOutputTokens: Optional `integer` value serialized in the
//	`ai_output_tokens` wire field.
//	aiPromptLength: Optional `integer` value serialized in the
//	`ai_prompt_length` wire field.
//	aiSession: Optional `string` value serialized in the `ai_session` wire
//	field.
//	branch: Optional `string` value serialized in the `branch` wire field.
//	category: Optional `string` value serialized in the `category` wire field.
//	createdAt: https://gorm.io/docs/conventions.html#CreatedAt
//	cursorpos: Optional `integer` value serialized in the `cursorpos` wire
//	field.
//	editor: ignored because editor might be parsed differently by wakatime
//	entity: Optional `string` value serialized in the `entity` wire field.
//	humanLineChanges: Optional `integer` value serialized in the
//	`human_line_changes` wire field.
//	isWrite: Optional `boolean` value serialized in the `is_write` wire field.
//	language: Optional `string` value serialized in the `language` wire field.
//	lineAdditions: Optional `integer` value serialized in the `line_additions`
//	wire field.
//	lineDeletions: Optional `integer` value serialized in the `line_deletions`
//	wire field.
//	lineno: Optional `integer` value serialized in the `lineno` wire field.
//	lines: Optional `integer` value serialized in the `lines` wire field.
//	machine: ignored because wakatime api doesn't return machines currently
//	operatingSystem: ignored because os might be parsed differently by wakatime
//	project: Optional `string` value serialized in the `project` wire field.
//	projectRootCount: Optional `integer` value serialized in the
//	`project_root_count` wire field.
//	time: note: on sqlite, table will have an additional column `time_real`,
//	introduced "manually" by migration 20260111 see
//	https://github.com/muety/wakapi/issues/882 for details
//	type_: Optional `string` value serialized in the `type` wire field.
//	userAgent: Optional `string` value serialized in the `user_agent` wire
//	field.
func PostHeartbeat(ctx context.Context, clientConfig ClientConfig, params PostHeartbeatParams, opts ...RequestOption) (any, error) {
	aiInputTokens := params.AiInputTokens
	aiLineChanges := params.AiLineChanges
	aiOutputTokens := params.AiOutputTokens
	aiPromptLength := params.AiPromptLength
	aiSession := params.AiSession
	branch := params.Branch
	category := params.Category
	createdAt := params.CreatedAt
	cursorpos := params.Cursorpos
	editor := params.Editor
	entity := params.Entity
	humanLineChanges := params.HumanLineChanges
	isWrite := params.IsWrite
	language := params.Language
	lineAdditions := params.LineAdditions
	lineDeletions := params.LineDeletions
	lineno := params.Lineno
	lines := params.Lines
	machine := params.Machine
	operatingSystem := params.OperatingSystem
	project := params.Project
	projectRootCount := params.ProjectRootCount
	time := params.Time
	type_ := params.Type_
	userAgent := params.UserAgent

	_, err := DoEmptyCfg(ctx, &clientConfig, "POST", "/heartbeat", &RequestOpts{
		Body: map[string]any{
			"ai_input_tokens":    aiInputTokens,
			"ai_line_changes":    aiLineChanges,
			"ai_output_tokens":   aiOutputTokens,
			"ai_prompt_length":   aiPromptLength,
			"ai_session":         aiSession,
			"branch":             branch,
			"category":           category,
			"created_at":         createdAt,
			"cursorpos":          cursorpos,
			"editor":             editor,
			"entity":             entity,
			"human_line_changes": humanLineChanges,
			"is_write":           isWrite,
			"language":           language,
			"line_additions":     lineAdditions,
			"line_deletions":     lineDeletions,
			"lineno":             lineno,
			"lines":              lines,
			"machine":            machine,
			"operating_system":   operatingSystem,
			"project":            project,
			"project_root_count": projectRootCount,
			"time":               time,
			"type":               type_,
			"user_agent":         userAgent,
		},
		OperationID: "PostHeartbeat",
		Options:     opts,
	})
	if err != nil {
		return nil, err
	}
	return nil, nil
}

type PostHeartbeat5Params struct {
	Body []ModelsHeartbeat
}

// PostHeartbeat5 submits multiple heartbeats in one request. Send a JSON array of heartbeat objects to record activity in bulk.
func PostHeartbeat5(ctx context.Context, clientConfig ClientConfig, params PostHeartbeat5Params, opts ...RequestOption) (any, error) {
	body := params.Body

	_, err := DoEmptyCfg(ctx, &clientConfig, "POST", "/heartbeats", &RequestOpts{
		Body:        body,
		OperationID: "PostHeartbeat5",
		Options:     opts,
	})
	if err != nil {
		return nil, err
	}
	return nil, nil
}

type PostHeartbeat4Params struct {
	User             string
	AiInputTokens    *int64
	AiLineChanges    *int64
	AiOutputTokens   *int64
	AiPromptLength   *int64
	AiSession        *string
	Branch           *string
	Category         *string
	CreatedAt        *float64
	Cursorpos        *int64
	Editor           *string
	Entity           *string
	HumanLineChanges *int64
	IsWrite          *bool
	Language         *string
	LineAdditions    *int64
	LineDeletions    *int64
	Lineno           *int64
	Lines            *int64
	Machine          *string
	OperatingSystem  *string
	Project          *string
	ProjectRootCount *int64
	Time             *float64
	Type_            *string
	UserAgent        *string
}

// PostHeartbeat4 submits a single heartbeat for a specified user. Send the heartbeat as a JSON object containing activity data such as `entity`, `category`, and `language`.
//
// Parameters:
//
//	user: Username (or current)
//	aiInputTokens: Optional `integer` value serialized in the `ai_input_tokens`
//	wire field.
//	aiLineChanges: Optional `integer` value serialized in the `ai_line_changes`
//	wire field.
//	aiOutputTokens: Optional `integer` value serialized in the
//	`ai_output_tokens` wire field.
//	aiPromptLength: Optional `integer` value serialized in the
//	`ai_prompt_length` wire field.
//	aiSession: Optional `string` value serialized in the `ai_session` wire
//	field.
//	branch: Optional `string` value serialized in the `branch` wire field.
//	category: Optional `string` value serialized in the `category` wire field.
//	createdAt: https://gorm.io/docs/conventions.html#CreatedAt
//	cursorpos: Optional `integer` value serialized in the `cursorpos` wire
//	field.
//	editor: ignored because editor might be parsed differently by wakatime
//	entity: Optional `string` value serialized in the `entity` wire field.
//	humanLineChanges: Optional `integer` value serialized in the
//	`human_line_changes` wire field.
//	isWrite: Optional `boolean` value serialized in the `is_write` wire field.
//	language: Optional `string` value serialized in the `language` wire field.
//	lineAdditions: Optional `integer` value serialized in the `line_additions`
//	wire field.
//	lineDeletions: Optional `integer` value serialized in the `line_deletions`
//	wire field.
//	lineno: Optional `integer` value serialized in the `lineno` wire field.
//	lines: Optional `integer` value serialized in the `lines` wire field.
//	machine: ignored because wakatime api doesn't return machines currently
//	operatingSystem: ignored because os might be parsed differently by wakatime
//	project: Optional `string` value serialized in the `project` wire field.
//	projectRootCount: Optional `integer` value serialized in the
//	`project_root_count` wire field.
//	time: note: on sqlite, table will have an additional column `time_real`,
//	introduced "manually" by migration 20260111 see
//	https://github.com/muety/wakapi/issues/882 for details
//	type_: Optional `string` value serialized in the `type` wire field.
//	userAgent: Optional `string` value serialized in the `user_agent` wire
//	field.
func PostHeartbeat4(ctx context.Context, clientConfig ClientConfig, params PostHeartbeat4Params, opts ...RequestOption) (any, error) {
	user := params.User
	aiInputTokens := params.AiInputTokens
	aiLineChanges := params.AiLineChanges
	aiOutputTokens := params.AiOutputTokens
	aiPromptLength := params.AiPromptLength
	aiSession := params.AiSession
	branch := params.Branch
	category := params.Category
	createdAt := params.CreatedAt
	cursorpos := params.Cursorpos
	editor := params.Editor
	entity := params.Entity
	humanLineChanges := params.HumanLineChanges
	isWrite := params.IsWrite
	language := params.Language
	lineAdditions := params.LineAdditions
	lineDeletions := params.LineDeletions
	lineno := params.Lineno
	lines := params.Lines
	machine := params.Machine
	operatingSystem := params.OperatingSystem
	project := params.Project
	projectRootCount := params.ProjectRootCount
	time := params.Time
	type_ := params.Type_
	userAgent := params.UserAgent

	_, err := DoEmptyCfg(ctx, &clientConfig, "POST", fmt.Sprintf("/users/%s/heartbeats", EncodePathSegment(user)), &RequestOpts{
		Body: map[string]any{
			"ai_input_tokens":    aiInputTokens,
			"ai_line_changes":    aiLineChanges,
			"ai_output_tokens":   aiOutputTokens,
			"ai_prompt_length":   aiPromptLength,
			"ai_session":         aiSession,
			"branch":             branch,
			"category":           category,
			"created_at":         createdAt,
			"cursorpos":          cursorpos,
			"editor":             editor,
			"entity":             entity,
			"human_line_changes": humanLineChanges,
			"is_write":           isWrite,
			"language":           language,
			"line_additions":     lineAdditions,
			"line_deletions":     lineDeletions,
			"lineno":             lineno,
			"lines":              lines,
			"machine":            machine,
			"operating_system":   operatingSystem,
			"project":            project,
			"project_root_count": projectRootCount,
			"time":               time,
			"type":               type_,
			"user_agent":         userAgent,
		},
		OperationID: "PostHeartbeat4",
		Options:     opts,
	})
	if err != nil {
		return nil, err
	}
	return nil, nil
}

type PostHeartbeat8Params struct {
	User string
	Body []ModelsHeartbeat
}

// PostHeartbeat8 submits multiple heartbeats for a specified user in one request. Send a JSON array of heartbeat objects to record activity in bulk.
//
// Parameters:
//
//	user: Username (or current)
func PostHeartbeat8(ctx context.Context, clientConfig ClientConfig, params PostHeartbeat8Params, opts ...RequestOption) (any, error) {
	user := params.User
	body := params.Body

	_, err := DoEmptyCfg(ctx, &clientConfig, "POST", fmt.Sprintf("/users/%s/heartbeats.bulk", EncodePathSegment(user)), &RequestOpts{
		Body:        body,
		OperationID: "PostHeartbeat8",
		Options:     opts,
	})
	if err != nil {
		return nil, err
	}
	return nil, nil
}

type PostHeartbeat2Params struct {
	User             string
	AiInputTokens    *int64
	AiLineChanges    *int64
	AiOutputTokens   *int64
	AiPromptLength   *int64
	AiSession        *string
	Branch           *string
	Category         *string
	CreatedAt        *float64
	Cursorpos        *int64
	Editor           *string
	Entity           *string
	HumanLineChanges *int64
	IsWrite          *bool
	Language         *string
	LineAdditions    *int64
	LineDeletions    *int64
	Lineno           *int64
	Lines            *int64
	Machine          *string
	OperatingSystem  *string
	Project          *string
	ProjectRootCount *int64
	Time             *float64
	Type_            *string
	UserAgent        *string
}

// PostHeartbeat2 creates a heartbeat for the specified user. Submit a JSON object with the activity data you want to record, such as `entity`, `language`, `category`, and line-change values. The schema does not mark any heartbeat fields as required.
//
// Parameters:
//
//	user: Username (or current)
//	aiInputTokens: Optional `integer` value serialized in the `ai_input_tokens`
//	wire field.
//	aiLineChanges: Optional `integer` value serialized in the `ai_line_changes`
//	wire field.
//	aiOutputTokens: Optional `integer` value serialized in the
//	`ai_output_tokens` wire field.
//	aiPromptLength: Optional `integer` value serialized in the
//	`ai_prompt_length` wire field.
//	aiSession: Optional `string` value serialized in the `ai_session` wire
//	field.
//	branch: Optional `string` value serialized in the `branch` wire field.
//	category: Optional `string` value serialized in the `category` wire field.
//	createdAt: https://gorm.io/docs/conventions.html#CreatedAt
//	cursorpos: Optional `integer` value serialized in the `cursorpos` wire
//	field.
//	editor: ignored because editor might be parsed differently by wakatime
//	entity: Optional `string` value serialized in the `entity` wire field.
//	humanLineChanges: Optional `integer` value serialized in the
//	`human_line_changes` wire field.
//	isWrite: Optional `boolean` value serialized in the `is_write` wire field.
//	language: Optional `string` value serialized in the `language` wire field.
//	lineAdditions: Optional `integer` value serialized in the `line_additions`
//	wire field.
//	lineDeletions: Optional `integer` value serialized in the `line_deletions`
//	wire field.
//	lineno: Optional `integer` value serialized in the `lineno` wire field.
//	lines: Optional `integer` value serialized in the `lines` wire field.
//	machine: ignored because wakatime api doesn't return machines currently
//	operatingSystem: ignored because os might be parsed differently by wakatime
//	project: Optional `string` value serialized in the `project` wire field.
//	projectRootCount: Optional `integer` value serialized in the
//	`project_root_count` wire field.
//	time: note: on sqlite, table will have an additional column `time_real`,
//	introduced "manually" by migration 20260111 see
//	https://github.com/muety/wakapi/issues/882 for details
//	type_: Optional `string` value serialized in the `type` wire field.
//	userAgent: Optional `string` value serialized in the `user_agent` wire
//	field.
func PostHeartbeat2(ctx context.Context, clientConfig ClientConfig, params PostHeartbeat2Params, opts ...RequestOption) (any, error) {
	user := params.User
	aiInputTokens := params.AiInputTokens
	aiLineChanges := params.AiLineChanges
	aiOutputTokens := params.AiOutputTokens
	aiPromptLength := params.AiPromptLength
	aiSession := params.AiSession
	branch := params.Branch
	category := params.Category
	createdAt := params.CreatedAt
	cursorpos := params.Cursorpos
	editor := params.Editor
	entity := params.Entity
	humanLineChanges := params.HumanLineChanges
	isWrite := params.IsWrite
	language := params.Language
	lineAdditions := params.LineAdditions
	lineDeletions := params.LineDeletions
	lineno := params.Lineno
	lines := params.Lines
	machine := params.Machine
	operatingSystem := params.OperatingSystem
	project := params.Project
	projectRootCount := params.ProjectRootCount
	time := params.Time
	type_ := params.Type_
	userAgent := params.UserAgent

	_, err := DoEmptyCfg(ctx, &clientConfig, "POST", fmt.Sprintf("/v1/users/%s/heartbeats", EncodePathSegment(user)), &RequestOpts{
		Body: map[string]any{
			"ai_input_tokens":    aiInputTokens,
			"ai_line_changes":    aiLineChanges,
			"ai_output_tokens":   aiOutputTokens,
			"ai_prompt_length":   aiPromptLength,
			"ai_session":         aiSession,
			"branch":             branch,
			"category":           category,
			"created_at":         createdAt,
			"cursorpos":          cursorpos,
			"editor":             editor,
			"entity":             entity,
			"human_line_changes": humanLineChanges,
			"is_write":           isWrite,
			"language":           language,
			"line_additions":     lineAdditions,
			"line_deletions":     lineDeletions,
			"lineno":             lineno,
			"lines":              lines,
			"machine":            machine,
			"operating_system":   operatingSystem,
			"project":            project,
			"project_root_count": projectRootCount,
			"time":               time,
			"type":               type_,
			"user_agent":         userAgent,
		},
		OperationID: "PostHeartbeat2",
		Options:     opts,
	})
	if err != nil {
		return nil, err
	}
	return nil, nil
}

type PostHeartbeat6Params struct {
	User string
	Body []ModelsHeartbeat
}

// PostHeartbeat6 creates multiple heartbeats for the specified user. Submit a JSON array of heartbeat objects containing the activity data you want to record. The schema does not mark any fields within the heartbeat objects as required.
//
// Parameters:
//
//	user: Username (or current)
func PostHeartbeat6(ctx context.Context, clientConfig ClientConfig, params PostHeartbeat6Params, opts ...RequestOption) (any, error) {
	user := params.User
	body := params.Body

	_, err := DoEmptyCfg(ctx, &clientConfig, "POST", fmt.Sprintf("/v1/users/%s/heartbeats.bulk", EncodePathSegment(user)), &RequestOpts{
		Body:        body,
		OperationID: "PostHeartbeat6",
		Options:     opts,
	})
	if err != nil {
		return nil, err
	}
	return nil, nil
}
