// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import "context"

// GetHealth retrieves the application's health status. Use this endpoint to check the service's current health without supplying request parameters or a body.
func GetHealth(ctx context.Context, clientConfig ClientConfig, opts ...RequestOption) (string, error) {

	resp, err := DoRawCfg(ctx, &clientConfig, "GET", "/health", &RequestOpts{
		OperationID: "GetHealth",
		Options:     opts,
	})
	if err != nil {
		return "", err
	}
	return resp.Data, nil
}
