// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import "encoding/json"

// ModelsSummary Typed representation of the `ModelsSummary` API schema.
type ModelsSummary struct {
	// Branches branches are not persisted, but calculated at runtime in case a project Filter is applied
	Branches []ModelsSummaryItem `json:"branches,omitempty"`
	// Categories Optional array value serialized in the `categories` wire field.
	Categories []ModelsSummaryItem `json:"categories,omitempty"`
	// Editors Optional array value serialized in the `editors` wire field.
	Editors []ModelsSummaryItem `json:"editors,omitempty"`
	// Entities entities are not persisted, but calculated at runtime in case a project Filter is applied
	Entities []ModelsSummaryItem `json:"entities,omitempty"`
	// From filled by gorm if not set, see https://gorm.io/docs/conventions.html#CreatedAt
	From *string `json:"from,omitempty"`
	// Labels labels are not persisted, but calculated at runtime, i.e. when summary is retrieved
	Labels []ModelsSummaryItem `json:"labels,omitempty"`
	// Languages Optional array value serialized in the `languages` wire field.
	Languages []ModelsSummaryItem `json:"languages,omitempty"`
	// Machines Optional array value serialized in the `machines` wire field.
	Machines []ModelsSummaryItem `json:"machines,omitempty"`
	// OperatingSystems Optional array value serialized in the `operating_systems` wire field.
	OperatingSystems []ModelsSummaryItem `json:"operating_systems,omitempty"`
	// Projects Previously, all the following properties created a cascade foreign key constraint on the summary_items table
	// back to this summary table resulting in 5 identical foreign key constraints on the summary_items table.
	// This is not a problem for PostgreSQL, MySQL and SQLite, but for MSSQL (not supported anymore though), which complains about circular cascades on
	// update/delete between these two tables. All of these created foreign key constraints are identical, so only one constraint is enough.
	// MySQL will create a foreign key constraint for every property referencing other structs, even no constraint is specified in tags.
	// So explicitly set gorm:"-" in all other properties to avoid creating duplicate foreign key constraints
	Projects []ModelsSummaryItem `json:"projects,omitempty"`
	// To filled by gorm if not set, see https://gorm.io/docs/conventions.html#CreatedAt
	To *string `json:"to,omitempty"`
	// UserId Optional `string` value serialized in the `user_id` wire field.
	UserId *string `json:"user_id,omitempty"`
}

func (value *ModelsSummary) UnmarshalJSON(data []byte) error {
	type ModelsSummaryAlias ModelsSummary
	var decoded ModelsSummaryAlias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	*value = ModelsSummary(decoded)
	var rawFields map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawFields); err != nil {
		return err
	}
	if value.From != nil {
		if err := ValidateDate("from", *value.From); err != nil {
			return err
		}
	}
	if value.To != nil {
		if err := ValidateDate("to", *value.To); err != nil {
			return err
		}
	}
	return nil
}

// NewModelsSummary returns a validated ModelsSummary built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewModelsSummary(fields ModelsSummary) (*ModelsSummary, error) {
	return ConstructModel(fields)
}

// ModelsSummaryItem Typed representation of the `ModelsSummaryItem` API schema.
type ModelsSummaryItem struct {
	// Key Optional `string` value serialized in the `key` wire field.
	Key *string `json:"key,omitempty"`
	// Total Optional `integer` value serialized in the `total` wire field.
	Total *int64 `json:"total,omitempty"`
}

// NewModelsSummaryItem returns a validated ModelsSummaryItem built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewModelsSummaryItem(fields ModelsSummaryItem) (*ModelsSummaryItem, error) {
	return ConstructModel(fields)
}
