// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

// ModelsHeartbeat Typed representation of the `ModelsHeartbeat` API schema.
type ModelsHeartbeat struct {
	// AiInputTokens Optional `integer` value serialized in the `ai_input_tokens` wire field.
	AiInputTokens *int64 `json:"ai_input_tokens,omitempty"`
	// AiLineChanges Optional `integer` value serialized in the `ai_line_changes` wire field.
	AiLineChanges *int64 `json:"ai_line_changes,omitempty"`
	// AiOutputTokens Optional `integer` value serialized in the `ai_output_tokens` wire field.
	AiOutputTokens *int64 `json:"ai_output_tokens,omitempty"`
	// AiPromptLength Optional `integer` value serialized in the `ai_prompt_length` wire field.
	AiPromptLength *int64 `json:"ai_prompt_length,omitempty"`
	// AiSession Optional `string` value serialized in the `ai_session` wire field.
	AiSession *string `json:"ai_session,omitempty"`
	// Branch Optional `string` value serialized in the `branch` wire field.
	Branch *string `json:"branch,omitempty"`
	// Category Optional `string` value serialized in the `category` wire field.
	Category *string `json:"category,omitempty"`
	// CreatedAt https://gorm.io/docs/conventions.html#CreatedAt
	CreatedAt *float64 `json:"created_at,omitempty"`
	// Cursorpos Optional `integer` value serialized in the `cursorpos` wire field.
	Cursorpos *int64 `json:"cursorpos,omitempty"`
	// Editor ignored because editor might be parsed differently by wakatime
	Editor *string `json:"editor,omitempty"`
	// Entity Optional `string` value serialized in the `entity` wire field.
	Entity *string `json:"entity,omitempty"`
	// HumanLineChanges Optional `integer` value serialized in the `human_line_changes` wire field.
	HumanLineChanges *int64 `json:"human_line_changes,omitempty"`
	// IsWrite Optional `boolean` value serialized in the `is_write` wire field.
	IsWrite *bool `json:"is_write,omitempty"`
	// Language Optional `string` value serialized in the `language` wire field.
	Language *string `json:"language,omitempty"`
	// LineAdditions Optional `integer` value serialized in the `line_additions` wire field.
	LineAdditions *int64 `json:"line_additions,omitempty"`
	// LineDeletions Optional `integer` value serialized in the `line_deletions` wire field.
	LineDeletions *int64 `json:"line_deletions,omitempty"`
	// Lineno Optional `integer` value serialized in the `lineno` wire field.
	Lineno *int64 `json:"lineno,omitempty"`
	// Lines Optional `integer` value serialized in the `lines` wire field.
	Lines *int64 `json:"lines,omitempty"`
	// Machine ignored because wakatime api doesn't return machines currently
	Machine *string `json:"machine,omitempty"`
	// OperatingSystem ignored because os might be parsed differently by wakatime
	OperatingSystem *string `json:"operating_system,omitempty"`
	// Project Optional `string` value serialized in the `project` wire field.
	Project *string `json:"project,omitempty"`
	// ProjectRootCount Optional `integer` value serialized in the `project_root_count` wire field.
	ProjectRootCount *int64 `json:"project_root_count,omitempty"`
	// Time note: on sqlite, table will have an additional column `time_real`, introduced "manually" by migration 20260111
	// see https://github.com/muety/wakapi/issues/882 for details
	Time *float64 `json:"time,omitempty"`
	// Type Optional `string` value serialized in the `type` wire field.
	Type *string `json:"type,omitempty"`
	// UserAgent Optional `string` value serialized in the `user_agent` wire field.
	UserAgent *string `json:"user_agent,omitempty"`
}

// NewModelsHeartbeat returns a validated ModelsHeartbeat built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewModelsHeartbeat(fields ModelsHeartbeat) (*ModelsHeartbeat, error) {
	return ConstructModel(fields)
}

// V1HeartbeatEntry Typed representation of the `V1HeartbeatEntry` API schema.
type V1HeartbeatEntry struct {
	// AiInputTokens Optional `integer` value serialized in the `ai_input_tokens` wire field.
	AiInputTokens *int64 `json:"ai_input_tokens,omitempty"`
	// AiLineChanges Optional `integer` value serialized in the `ai_line_changes` wire field.
	AiLineChanges *int64 `json:"ai_line_changes,omitempty"`
	// AiOutputTokens Optional `integer` value serialized in the `ai_output_tokens` wire field.
	AiOutputTokens *int64 `json:"ai_output_tokens,omitempty"`
	// AiPromptLength Optional `integer` value serialized in the `ai_prompt_length` wire field.
	AiPromptLength *int64 `json:"ai_prompt_length,omitempty"`
	// AiSession Optional `string` value serialized in the `ai_session` wire field.
	AiSession *string `json:"ai_session,omitempty"`
	// Branch Optional `string` value serialized in the `branch` wire field.
	Branch *string `json:"branch,omitempty"`
	// Category Optional `string` value serialized in the `category` wire field.
	Category *string `json:"category,omitempty"`
	// CreatedAt Optional `string` value serialized in the `created_at` wire field.
	CreatedAt *string `json:"created_at,omitempty"`
	// Cursorpos Optional `integer` value serialized in the `cursorpos` wire field.
	Cursorpos *int64 `json:"cursorpos,omitempty"`
	// Entity Optional `string` value serialized in the `entity` wire field.
	Entity *string `json:"entity,omitempty"`
	// HumanLineChanges Optional `integer` value serialized in the `human_line_changes` wire field.
	HumanLineChanges *int64 `json:"human_line_changes,omitempty"`
	// Id Optional `string` value serialized in the `id` wire field.
	Id *string `json:"id,omitempty"`
	// IsWrite Optional `boolean` value serialized in the `is_write` wire field.
	IsWrite *bool `json:"is_write,omitempty"`
	// Language Optional `string` value serialized in the `language` wire field.
	Language *string `json:"language,omitempty"`
	// LineAdditions Optional `integer` value serialized in the `line_additions` wire field.
	LineAdditions *int64 `json:"line_additions,omitempty"`
	// LineDeletions Optional `integer` value serialized in the `line_deletions` wire field.
	LineDeletions *int64 `json:"line_deletions,omitempty"`
	// Lineno Optional `integer` value serialized in the `lineno` wire field.
	Lineno *int64 `json:"lineno,omitempty"`
	// Lines Optional `integer` value serialized in the `lines` wire field.
	Lines *int64 `json:"lines,omitempty"`
	// MachineNameId Optional `string` value serialized in the `machine_name_id` wire field.
	MachineNameId *string `json:"machine_name_id,omitempty"`
	// Project Optional `string` value serialized in the `project` wire field.
	Project *string `json:"project,omitempty"`
	// Time Optional `number` value serialized in the `time` wire field.
	Time *float64 `json:"time,omitempty"`
	// Type Optional `string` value serialized in the `type` wire field.
	Type *string `json:"type,omitempty"`
	// UserAgentId Optional `string` value serialized in the `user_agent_id` wire field.
	UserAgentId *string `json:"user_agent_id,omitempty"`
	// UserId Optional `string` value serialized in the `user_id` wire field.
	UserId *string `json:"user_id,omitempty"`
}

// NewV1HeartbeatEntry returns a validated V1HeartbeatEntry built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewV1HeartbeatEntry(fields V1HeartbeatEntry) (*V1HeartbeatEntry, error) {
	return ConstructModel(fields)
}

// V1HeartbeatsResult Typed representation of the `V1HeartbeatsResult` API schema.
type V1HeartbeatsResult struct {
	// Data Optional array value serialized in the `data` wire field.
	Data []V1HeartbeatEntry `json:"data,omitempty"`
	// End Optional `string` value serialized in the `end` wire field.
	End *string `json:"end,omitempty"`
	// Start Optional `string` value serialized in the `start` wire field.
	Start *string `json:"start,omitempty"`
	// Timezone Optional `string` value serialized in the `timezone` wire field.
	Timezone *string `json:"timezone,omitempty"`
}

// NewV1HeartbeatsResult returns a validated V1HeartbeatsResult built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewV1HeartbeatsResult(fields V1HeartbeatsResult) (*V1HeartbeatsResult, error) {
	return ConstructModel(fields)
}
