// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

// V1AllTimeData Typed representation of the `V1AllTimeData` API schema.
type V1AllTimeData struct {
	// IsUpToDate true if the stats are up to date; when false, a 202 response code is returned and stats will be refreshed soon>
	IsUpToDate *bool `json:"is_up_to_date,omitempty"`
	// Range Optional object value serialized in the `range` wire field.
	Range *V1AllTimeRange `json:"range,omitempty"`
	// Text total time logged since account created as human readable string>
	Text *string `json:"text,omitempty"`
	// TotalSeconds total number of seconds logged since account created
	TotalSeconds *float64 `json:"total_seconds,omitempty"`
}

// NewV1AllTimeData returns a validated V1AllTimeData built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewV1AllTimeData(fields V1AllTimeData) (*V1AllTimeData, error) {
	return ConstructModel(fields)
}

// V1AllTimeRange Typed representation of the `V1AllTimeRange` API schema.
type V1AllTimeRange struct {
	// End Optional `string` value serialized in the `end` wire field.
	End *string `json:"end,omitempty"`
	// EndDate Optional `string` value serialized in the `end_date` wire field.
	EndDate *string `json:"end_date,omitempty"`
	// Start Optional `string` value serialized in the `start` wire field.
	Start *string `json:"start,omitempty"`
	// StartDate Optional `string` value serialized in the `start_date` wire field.
	StartDate *string `json:"start_date,omitempty"`
	// Timezone Optional `string` value serialized in the `timezone` wire field.
	Timezone *string `json:"timezone,omitempty"`
}

// NewV1AllTimeRange returns a validated V1AllTimeRange built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewV1AllTimeRange(fields V1AllTimeRange) (*V1AllTimeRange, error) {
	return ConstructModel(fields)
}

// V1AllTimeViewModel Typed representation of the `V1AllTimeViewModel` API schema.
type V1AllTimeViewModel struct {
	// Data Optional object value serialized in the `data` wire field.
	Data *V1AllTimeData `json:"data,omitempty"`
}

// NewV1AllTimeViewModel returns a validated V1AllTimeViewModel built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewV1AllTimeViewModel(fields V1AllTimeViewModel) (*V1AllTimeViewModel, error) {
	return ConstructModel(fields)
}

// V1LeadersCurrentUser Typed representation of the `V1LeadersCurrentUser` API schema.
type V1LeadersCurrentUser struct {
	// Page Optional `integer` value serialized in the `page` wire field.
	Page *int64 `json:"page,omitempty"`
	// Rank Optional `integer` value serialized in the `rank` wire field.
	Rank *int64 `json:"rank,omitempty"`
	// User Optional object value serialized in the `user` wire field.
	User *V1User `json:"user,omitempty"`
}

// NewV1LeadersCurrentUser returns a validated V1LeadersCurrentUser built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewV1LeadersCurrentUser(fields V1LeadersCurrentUser) (*V1LeadersCurrentUser, error) {
	return ConstructModel(fields)
}

// V1LeadersEntry Typed representation of the `V1LeadersEntry` API schema.
type V1LeadersEntry struct {
	// Rank Optional `integer` value serialized in the `rank` wire field.
	Rank *int64 `json:"rank,omitempty"`
	// RunningTotal Optional object value serialized in the `running_total` wire field.
	RunningTotal *V1LeadersRunningTotal `json:"running_total,omitempty"`
	// User Optional object value serialized in the `user` wire field.
	User *V1User `json:"user,omitempty"`
}

// NewV1LeadersEntry returns a validated V1LeadersEntry built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewV1LeadersEntry(fields V1LeadersEntry) (*V1LeadersEntry, error) {
	return ConstructModel(fields)
}

// V1LeadersLanguage Typed representation of the `V1LeadersLanguage` API schema.
type V1LeadersLanguage struct {
	// Name Optional `string` value serialized in the `name` wire field.
	Name *string `json:"name,omitempty"`
	// TotalSeconds Optional `number` value serialized in the `total_seconds` wire field.
	TotalSeconds *float64 `json:"total_seconds,omitempty"`
}

// NewV1LeadersLanguage returns a validated V1LeadersLanguage built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewV1LeadersLanguage(fields V1LeadersLanguage) (*V1LeadersLanguage, error) {
	return ConstructModel(fields)
}

// V1LeadersRange Typed representation of the `V1LeadersRange` API schema.
type V1LeadersRange struct {
	// EndDate Optional `string` value serialized in the `end_date` wire field.
	EndDate *string `json:"end_date,omitempty"`
	// EndText Optional `string` value serialized in the `end_text` wire field.
	EndText *string `json:"end_text,omitempty"`
	// Name Optional `string` value serialized in the `name` wire field.
	Name *string `json:"name,omitempty"`
	// StartDate Optional `string` value serialized in the `start_date` wire field.
	StartDate *string `json:"start_date,omitempty"`
	// StartText Optional `string` value serialized in the `start_text` wire field.
	StartText *string `json:"start_text,omitempty"`
	// Text Optional `string` value serialized in the `text` wire field.
	Text *string `json:"text,omitempty"`
}

// NewV1LeadersRange returns a validated V1LeadersRange built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewV1LeadersRange(fields V1LeadersRange) (*V1LeadersRange, error) {
	return ConstructModel(fields)
}

// V1LeadersRunningTotal Typed representation of the `V1LeadersRunningTotal` API schema.
type V1LeadersRunningTotal struct {
	// DailyAverage Optional `number` value serialized in the `daily_average` wire field.
	DailyAverage *float64 `json:"daily_average,omitempty"`
	// HumanReadableDailyAverage Optional `string` value serialized in the `human_readable_daily_average` wire field.
	HumanReadableDailyAverage *string `json:"human_readable_daily_average,omitempty"`
	// HumanReadableTotal Optional `string` value serialized in the `human_readable_total` wire field.
	HumanReadableTotal *string `json:"human_readable_total,omitempty"`
	// Languages Optional array value serialized in the `languages` wire field.
	Languages []V1LeadersLanguage `json:"languages,omitempty"`
	// TotalSeconds Optional `number` value serialized in the `total_seconds` wire field.
	TotalSeconds *float64 `json:"total_seconds,omitempty"`
}

// NewV1LeadersRunningTotal returns a validated V1LeadersRunningTotal built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewV1LeadersRunningTotal(fields V1LeadersRunningTotal) (*V1LeadersRunningTotal, error) {
	return ConstructModel(fields)
}

// V1LeadersViewModel Typed representation of the `V1LeadersViewModel` API schema.
type V1LeadersViewModel struct {
	// CurrentUser Optional object value serialized in the `current_user` wire field.
	CurrentUser *V1LeadersCurrentUser `json:"current_user,omitempty"`
	// Data Optional array value serialized in the `data` wire field.
	Data []V1LeadersEntry `json:"data,omitempty"`
	// Language Optional `string` value serialized in the `language` wire field.
	Language *string `json:"language,omitempty"`
	// Page Optional `integer` value serialized in the `page` wire field.
	Page *int64 `json:"page,omitempty"`
	// Range Optional object value serialized in the `range` wire field.
	Range *V1LeadersRange `json:"range,omitempty"`
	// TotalPages Optional `integer` value serialized in the `total_pages` wire field.
	TotalPages *int64 `json:"total_pages,omitempty"`
}

// NewV1LeadersViewModel returns a validated V1LeadersViewModel built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewV1LeadersViewModel(fields V1LeadersViewModel) (*V1LeadersViewModel, error) {
	return ConstructModel(fields)
}

// V1Project Typed representation of the `V1Project` API schema.
type V1Project struct {
	// CreatedAt Optional `string` value serialized in the `created_at` wire field.
	CreatedAt *string `json:"created_at,omitempty"`
	// HumanReadableLastHeartbeatAt Optional `string` value serialized in the `human_readable_last_heartbeat_at` wire field.
	HumanReadableLastHeartbeatAt *string `json:"human_readable_last_heartbeat_at,omitempty"`
	// Id Optional `string` value serialized in the `id` wire field.
	Id *string `json:"id,omitempty"`
	// LastHeartbeatAt Optional `string` value serialized in the `last_heartbeat_at` wire field.
	LastHeartbeatAt *string `json:"last_heartbeat_at,omitempty"`
	// Name Optional `string` value serialized in the `name` wire field.
	Name *string `json:"name,omitempty"`
	// UrlencodedName Optional `string` value serialized in the `urlencoded_name` wire field.
	UrlencodedName *string `json:"urlencoded_name,omitempty"`
}

// NewV1Project returns a validated V1Project built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewV1Project(fields V1Project) (*V1Project, error) {
	return ConstructModel(fields)
}

// V1ProjectViewModel Typed representation of the `V1ProjectViewModel` API schema.
type V1ProjectViewModel struct {
	// Data Optional object value serialized in the `data` wire field.
	Data *V1Project `json:"data,omitempty"`
}

// NewV1ProjectViewModel returns a validated V1ProjectViewModel built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewV1ProjectViewModel(fields V1ProjectViewModel) (*V1ProjectViewModel, error) {
	return ConstructModel(fields)
}

// V1ProjectsViewModel Typed representation of the `V1ProjectsViewModel` API schema.
type V1ProjectsViewModel struct {
	// Data Optional array value serialized in the `data` wire field.
	Data []V1Project `json:"data,omitempty"`
}

// NewV1ProjectsViewModel returns a validated V1ProjectsViewModel built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewV1ProjectsViewModel(fields V1ProjectsViewModel) (*V1ProjectsViewModel, error) {
	return ConstructModel(fields)
}

// V1StatsData Typed representation of the `V1StatsData` API schema.
type V1StatsData struct {
	// Branches Optional array value serialized in the `branches` wire field.
	Branches []V1SummariesEntry `json:"branches,omitempty"`
	// Categories Optional array value serialized in the `categories` wire field.
	Categories []V1SummariesEntry `json:"categories,omitempty"`
	// DailyAverage Optional `number` value serialized in the `daily_average` wire field.
	DailyAverage *float64 `json:"daily_average,omitempty"`
	// DaysIncludingHolidays Optional `integer` value serialized in the `days_including_holidays` wire field.
	DaysIncludingHolidays *int64 `json:"days_including_holidays,omitempty"`
	// Editors Optional array value serialized in the `editors` wire field.
	Editors []V1SummariesEntry `json:"editors,omitempty"`
	// End Optional `string` value serialized in the `end` wire field.
	End *string `json:"end,omitempty"`
	// HumanReadableDailyAverage Optional `string` value serialized in the `human_readable_daily_average` wire field.
	HumanReadableDailyAverage *string `json:"human_readable_daily_average,omitempty"`
	// HumanReadableRange Optional `string` value serialized in the `human_readable_range` wire field.
	HumanReadableRange *string `json:"human_readable_range,omitempty"`
	// HumanReadableTotal Optional `string` value serialized in the `human_readable_total` wire field.
	HumanReadableTotal *string `json:"human_readable_total,omitempty"`
	// IsCodingActivityVisible Optional `boolean` value serialized in the `is_coding_activity_visible` wire field.
	IsCodingActivityVisible *bool `json:"is_coding_activity_visible,omitempty"`
	// IsOtherUsageVisible Optional `boolean` value serialized in the `is_other_usage_visible` wire field.
	IsOtherUsageVisible *bool `json:"is_other_usage_visible,omitempty"`
	// Languages Optional array value serialized in the `languages` wire field.
	Languages []V1SummariesEntry `json:"languages,omitempty"`
	// Machines Optional array value serialized in the `machines` wire field.
	Machines []V1SummariesEntry `json:"machines,omitempty"`
	// OperatingSystems Optional array value serialized in the `operating_systems` wire field.
	OperatingSystems []V1SummariesEntry `json:"operating_systems,omitempty"`
	// Projects Optional array value serialized in the `projects` wire field.
	Projects []V1SummariesEntry `json:"projects,omitempty"`
	// Range Optional `string` value serialized in the `range` wire field.
	Range *string `json:"range,omitempty"`
	// Start Optional `string` value serialized in the `start` wire field.
	Start *string `json:"start,omitempty"`
	// Status Optional `string` value serialized in the `status` wire field.
	Status *string `json:"status,omitempty"`
	// Timezone Optional `string` value serialized in the `timezone` wire field.
	Timezone *string `json:"timezone,omitempty"`
	// TotalSeconds Optional `number` value serialized in the `total_seconds` wire field.
	TotalSeconds *float64 `json:"total_seconds,omitempty"`
	// UserId Optional `string` value serialized in the `user_id` wire field.
	UserId *string `json:"user_id,omitempty"`
	// Username Optional `string` value serialized in the `username` wire field.
	Username *string `json:"username,omitempty"`
}

// NewV1StatsData returns a validated V1StatsData built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewV1StatsData(fields V1StatsData) (*V1StatsData, error) {
	return ConstructModel(fields)
}

// V1StatsViewModel Typed representation of the `V1StatsViewModel` API schema.
type V1StatsViewModel struct {
	// Data Optional object value serialized in the `data` wire field.
	Data *V1StatsData `json:"data,omitempty"`
}

// NewV1StatsViewModel returns a validated V1StatsViewModel built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewV1StatsViewModel(fields V1StatsViewModel) (*V1StatsViewModel, error) {
	return ConstructModel(fields)
}

// V1StatusBarViewModel Typed representation of the `V1StatusBarViewModel` API schema.
type V1StatusBarViewModel struct {
	// CachedAt Optional `string` value serialized in the `cached_at` wire field.
	CachedAt *string `json:"cached_at,omitempty"`
	// Data Optional object value serialized in the `data` wire field.
	Data *V1SummariesData `json:"data,omitempty"`
}

// NewV1StatusBarViewModel returns a validated V1StatusBarViewModel built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewV1StatusBarViewModel(fields V1StatusBarViewModel) (*V1StatusBarViewModel, error) {
	return ConstructModel(fields)
}

// V1SummariesCumulativeTotal Typed representation of the `V1SummariesCumulativeTotal` API schema.
type V1SummariesCumulativeTotal struct {
	// Decimal Optional `string` value serialized in the `decimal` wire field.
	Decimal *string `json:"decimal,omitempty"`
	// Digital Optional `string` value serialized in the `digital` wire field.
	Digital *string `json:"digital,omitempty"`
	// Seconds Optional `number` value serialized in the `seconds` wire field.
	Seconds *float64 `json:"seconds,omitempty"`
	// Text Optional `string` value serialized in the `text` wire field.
	Text *string `json:"text,omitempty"`
}

// NewV1SummariesCumulativeTotal returns a validated V1SummariesCumulativeTotal built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewV1SummariesCumulativeTotal(fields V1SummariesCumulativeTotal) (*V1SummariesCumulativeTotal, error) {
	return ConstructModel(fields)
}

// V1SummariesDailyAverage Typed representation of the `V1SummariesDailyAverage` API schema.
type V1SummariesDailyAverage struct {
	// DaysIncludingHolidays Optional `integer` value serialized in the `days_including_holidays` wire field.
	DaysIncludingHolidays *int64 `json:"days_including_holidays,omitempty"`
	// DaysMinusHolidays Optional `integer` value serialized in the `days_minus_holidays` wire field.
	DaysMinusHolidays *int64 `json:"days_minus_holidays,omitempty"`
	// Holidays Optional `integer` value serialized in the `holidays` wire field.
	Holidays *int64 `json:"holidays,omitempty"`
	// Seconds Optional `integer` value serialized in the `seconds` wire field.
	Seconds *int64 `json:"seconds,omitempty"`
	// SecondsIncludingOtherLanguage Optional `integer` value serialized in the `seconds_including_other_language` wire field.
	SecondsIncludingOtherLanguage *int64 `json:"seconds_including_other_language,omitempty"`
	// Text Optional `string` value serialized in the `text` wire field.
	Text *string `json:"text,omitempty"`
	// TextIncludingOtherLanguage Optional `string` value serialized in the `text_including_other_language` wire field.
	TextIncludingOtherLanguage *string `json:"text_including_other_language,omitempty"`
}

// NewV1SummariesDailyAverage returns a validated V1SummariesDailyAverage built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewV1SummariesDailyAverage(fields V1SummariesDailyAverage) (*V1SummariesDailyAverage, error) {
	return ConstructModel(fields)
}

// V1SummariesData Typed representation of the `V1SummariesData` API schema.
type V1SummariesData struct {
	// Branches Optional array value serialized in the `branches` wire field.
	Branches []V1SummariesEntry `json:"branches,omitempty"`
	// Categories Optional array value serialized in the `categories` wire field.
	Categories []V1SummariesEntry `json:"categories,omitempty"`
	// Dependencies Optional array value serialized in the `dependencies` wire field.
	Dependencies []V1SummariesEntry `json:"dependencies,omitempty"`
	// Editors Optional array value serialized in the `editors` wire field.
	Editors []V1SummariesEntry `json:"editors,omitempty"`
	// Entities Optional array value serialized in the `entities` wire field.
	Entities []V1SummariesEntry `json:"entities,omitempty"`
	// GrandTotal Optional object value serialized in the `grand_total` wire field.
	GrandTotal *V1SummariesGrandTotal `json:"grand_total,omitempty"`
	// Languages Optional array value serialized in the `languages` wire field.
	Languages []V1SummariesEntry `json:"languages,omitempty"`
	// Machines Optional array value serialized in the `machines` wire field.
	Machines []V1SummariesEntry `json:"machines,omitempty"`
	// OperatingSystems Optional array value serialized in the `operating_systems` wire field.
	OperatingSystems []V1SummariesEntry `json:"operating_systems,omitempty"`
	// Projects Optional array value serialized in the `projects` wire field.
	Projects []V1SummariesEntry `json:"projects,omitempty"`
	// Range Optional object value serialized in the `range` wire field.
	Range *V1SummariesRange `json:"range,omitempty"`
}

// NewV1SummariesData returns a validated V1SummariesData built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewV1SummariesData(fields V1SummariesData) (*V1SummariesData, error) {
	return ConstructModel(fields)
}

// V1SummariesEntry Typed representation of the `V1SummariesEntry` API schema.
type V1SummariesEntry struct {
	// Digital Optional `string` value serialized in the `digital` wire field.
	Digital *string `json:"digital,omitempty"`
	// Hours Optional `integer` value serialized in the `hours` wire field.
	Hours *int64 `json:"hours,omitempty"`
	// Minutes Optional `integer` value serialized in the `minutes` wire field.
	Minutes *int64 `json:"minutes,omitempty"`
	// Name Optional `string` value serialized in the `name` wire field.
	Name *string `json:"name,omitempty"`
	// Percent Optional `number` value serialized in the `percent` wire field.
	Percent *float64 `json:"percent,omitempty"`
	// Seconds Optional `integer` value serialized in the `seconds` wire field.
	Seconds *int64 `json:"seconds,omitempty"`
	// Text Optional `string` value serialized in the `text` wire field.
	Text *string `json:"text,omitempty"`
	// TotalSeconds Optional `number` value serialized in the `total_seconds` wire field.
	TotalSeconds *float64 `json:"total_seconds,omitempty"`
}

// NewV1SummariesEntry returns a validated V1SummariesEntry built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewV1SummariesEntry(fields V1SummariesEntry) (*V1SummariesEntry, error) {
	return ConstructModel(fields)
}

// V1SummariesGrandTotal Typed representation of the `V1SummariesGrandTotal` API schema.
type V1SummariesGrandTotal struct {
	// Digital Optional `string` value serialized in the `digital` wire field.
	Digital *string `json:"digital,omitempty"`
	// Hours Optional `integer` value serialized in the `hours` wire field.
	Hours *int64 `json:"hours,omitempty"`
	// Minutes Optional `integer` value serialized in the `minutes` wire field.
	Minutes *int64 `json:"minutes,omitempty"`
	// Text Optional `string` value serialized in the `text` wire field.
	Text *string `json:"text,omitempty"`
	// TotalSeconds Optional `number` value serialized in the `total_seconds` wire field.
	TotalSeconds *float64 `json:"total_seconds,omitempty"`
}

// NewV1SummariesGrandTotal returns a validated V1SummariesGrandTotal built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewV1SummariesGrandTotal(fields V1SummariesGrandTotal) (*V1SummariesGrandTotal, error) {
	return ConstructModel(fields)
}

// V1SummariesRange Typed representation of the `V1SummariesRange` API schema.
type V1SummariesRange struct {
	// Date Optional `string` value serialized in the `date` wire field.
	Date *string `json:"date,omitempty"`
	// End Optional `string` value serialized in the `end` wire field.
	End *string `json:"end,omitempty"`
	// Start Optional `string` value serialized in the `start` wire field.
	Start *string `json:"start,omitempty"`
	// Text Optional `string` value serialized in the `text` wire field.
	Text *string `json:"text,omitempty"`
	// Timezone Optional `string` value serialized in the `timezone` wire field.
	Timezone *string `json:"timezone,omitempty"`
}

// NewV1SummariesRange returns a validated V1SummariesRange built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewV1SummariesRange(fields V1SummariesRange) (*V1SummariesRange, error) {
	return ConstructModel(fields)
}

// V1SummariesViewModel Typed representation of the `V1SummariesViewModel` API schema.
type V1SummariesViewModel struct {
	// CumulativeTotal Optional object value serialized in the `cumulative_total` wire field.
	CumulativeTotal *V1SummariesCumulativeTotal `json:"cumulative_total,omitempty"`
	// DailyAverage Optional object value serialized in the `daily_average` wire field.
	DailyAverage *V1SummariesDailyAverage `json:"daily_average,omitempty"`
	// Data Optional array value serialized in the `data` wire field.
	Data []V1SummariesData `json:"data,omitempty"`
	// End Optional `string` value serialized in the `end` wire field.
	End *string `json:"end,omitempty"`
	// Start Optional `string` value serialized in the `start` wire field.
	Start *string `json:"start,omitempty"`
}

// NewV1SummariesViewModel returns a validated V1SummariesViewModel built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewV1SummariesViewModel(fields V1SummariesViewModel) (*V1SummariesViewModel, error) {
	return ConstructModel(fields)
}

// V1User Typed representation of the `V1User` API schema.
type V1User struct {
	// CreatedAt Optional `string` value serialized in the `created_at` wire field.
	CreatedAt *string `json:"created_at,omitempty"`
	// DisplayName Optional `string` value serialized in the `display_name` wire field.
	DisplayName *string `json:"display_name,omitempty"`
	// Email Optional `string` value serialized in the `email` wire field.
	Email *string `json:"email,omitempty"`
	// FullName Optional `string` value serialized in the `full_name` wire field.
	FullName *string `json:"full_name,omitempty"`
	// Id Optional `string` value serialized in the `id` wire field.
	Id *string `json:"id,omitempty"`
	// IsEmailConfirmed Optional `boolean` value serialized in the `is_email_confirmed` wire field.
	IsEmailConfirmed *bool `json:"is_email_confirmed,omitempty"`
	// IsEmailPublic Optional `boolean` value serialized in the `is_email_public` wire field.
	IsEmailPublic *bool `json:"is_email_public,omitempty"`
	// LastHeartbeatAt Optional `string` value serialized in the `last_heartbeat_at` wire field.
	LastHeartbeatAt *string `json:"last_heartbeat_at,omitempty"`
	// LastPluginName Optional `string` value serialized in the `last_plugin_name` wire field.
	LastPluginName *string `json:"last_plugin_name,omitempty"`
	// LastProject Optional `string` value serialized in the `last_project` wire field.
	LastProject *string `json:"last_project,omitempty"`
	// ModifiedAt Optional `string` value serialized in the `modified_at` wire field.
	ModifiedAt *string `json:"modified_at,omitempty"`
	// Photo Optional `string` value serialized in the `photo` wire field.
	Photo *string `json:"photo,omitempty"`
	// Timezone Optional `string` value serialized in the `timezone` wire field.
	Timezone *string `json:"timezone,omitempty"`
	// Username Optional `string` value serialized in the `username` wire field.
	Username *string `json:"username,omitempty"`
	// Website Optional `string` value serialized in the `website` wire field.
	Website *string `json:"website,omitempty"`
}

// NewV1User returns a validated V1User built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewV1User(fields V1User) (*V1User, error) {
	return ConstructModel(fields)
}

// V1UserAgentEntry Typed representation of the `V1UserAgentEntry` API schema.
type V1UserAgentEntry struct {
	// Editor Optional `string` value serialized in the `editor` wire field.
	Editor *string `json:"editor,omitempty"`
	// FirstSeen Optional `string` value serialized in the `first_seen` wire field.
	FirstSeen *string `json:"first_seen,omitempty"`
	// Id Optional `string` value serialized in the `id` wire field.
	Id *string `json:"id,omitempty"`
	// IsBrowserExtension currently not implemented
	IsBrowserExtension *bool `json:"is_browser_extension,omitempty"`
	// IsDesktopApp currently not implemented
	IsDesktopApp *bool `json:"is_desktop_app,omitempty"`
	// LastSeen Optional `string` value serialized in the `last_seen` wire field.
	LastSeen *string `json:"last_seen,omitempty"`
	// Os Optional `string` value serialized in the `os` wire field.
	Os *string `json:"os,omitempty"`
	// Value Optional `string` value serialized in the `value` wire field.
	Value *string `json:"value,omitempty"`
	// Version currently not implemented
	Version *string `json:"version,omitempty"`
}

// NewV1UserAgentEntry returns a validated V1UserAgentEntry built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewV1UserAgentEntry(fields V1UserAgentEntry) (*V1UserAgentEntry, error) {
	return ConstructModel(fields)
}

// V1UserAgentsViewModel Typed representation of the `V1UserAgentsViewModel` API schema.
type V1UserAgentsViewModel struct {
	// Data Optional array value serialized in the `data` wire field.
	Data []V1UserAgentEntry `json:"data,omitempty"`
	// TotalPages Optional `integer` value serialized in the `total_pages` wire field.
	TotalPages *int64 `json:"total_pages,omitempty"`
}

// NewV1UserAgentsViewModel returns a validated V1UserAgentsViewModel built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewV1UserAgentsViewModel(fields V1UserAgentsViewModel) (*V1UserAgentsViewModel, error) {
	return ConstructModel(fields)
}

// V1UserViewModel Typed representation of the `V1UserViewModel` API schema.
type V1UserViewModel struct {
	// Data Optional object value serialized in the `data` wire field.
	Data *V1User `json:"data,omitempty"`
}

// NewV1UserViewModel returns a validated V1UserViewModel built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewV1UserViewModel(fields V1UserViewModel) (*V1UserViewModel, error) {
	return ConstructModel(fields)
}
