// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

// ModelsDiagnostics Typed representation of the `ModelsDiagnostics` API schema.
type ModelsDiagnostics struct {
	// Architecture Optional `string` value serialized in the `architecture` wire field.
	Architecture *string `json:"architecture,omitempty"`
	// CliVersion Optional `string` value serialized in the `cli_version` wire field.
	CliVersion *string `json:"cli_version,omitempty"`
	// Id Optional `integer` value serialized in the `id` wire field.
	Id *int64 `json:"id,omitempty"`
	// Logs Optional `string` value serialized in the `logs` wire field.
	Logs *string `json:"logs,omitempty"`
	// Platform Optional `string` value serialized in the `platform` wire field.
	Platform *string `json:"platform,omitempty"`
	// Plugin Optional `string` value serialized in the `plugin` wire field.
	Plugin *string `json:"plugin,omitempty"`
	// Stacktrace Optional `string` value serialized in the `stacktrace` wire field.
	Stacktrace *string `json:"stacktrace,omitempty"`
}

// NewModelsDiagnostics returns a validated ModelsDiagnostics built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewModelsDiagnostics(fields ModelsDiagnostics) (*ModelsDiagnostics, error) {
	return ConstructModel(fields)
}
