// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

// V1BadgeData Typed representation of the `V1BadgeData` API schema.
type V1BadgeData struct {
	// Color Optional `string` value serialized in the `color` wire field.
	Color *string `json:"color,omitempty"`
	// Label Optional `string` value serialized in the `label` wire field.
	Label *string `json:"label,omitempty"`
	// Message Optional `string` value serialized in the `message` wire field.
	Message *string `json:"message,omitempty"`
	// SchemaVersion Optional `integer` value serialized in the `schemaVersion` wire field.
	SchemaVersion *int64 `json:"schemaVersion,omitempty"`
}

// NewV1BadgeData returns a validated V1BadgeData built from named fields.
// Optional fields may be left unset; a value that violates the schema is
// reported as *SdkValidationError.
func NewV1BadgeData(fields V1BadgeData) (*V1BadgeData, error) {
	return ConstructModel(fields)
}
