// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import (
	"context"
	"encoding/json"
	"os"
	"reflect"
	"strings"
	"testing"
)

type sdkMethodResponse struct {
	Kind       string          `json:"kind"`
	Expected   json.RawMessage `json:"expected"`
	ByteLength int             `json:"byteLength"`
}

type sdkMethodCase struct {
	ID            string                     `json:"id"`
	MethodName    string                     `json:"methodName"`
	Mode          string                     `json:"mode"`
	Arguments     map[string]json.RawMessage `json:"arguments"`
	ArgumentOrder []string                   `json:"argumentOrder"`
	Response      sdkMethodResponse          `json:"response"`
}

func sdkMethodByName(name string) any {
	switch name {
	case "GetAllTime":
		return GetAllTime
	case "GetBadge":
		return GetBadge
	case "GetHealth":
		return GetHealth
	case "GetHeartbeats":
		return GetHeartbeats
	case "GetSummary":
		return GetSummary
	case "GetWakatimeLeaders":
		return GetWakatimeLeaders
	case "GetWakatimeProject":
		return GetWakatimeProject
	case "GetWakatimeProjects":
		return GetWakatimeProjects
	case "GetWakatimesTats":
		return GetWakatimesTats
	case "GetWakatimeSummaries":
		return GetWakatimeSummaries
	case "GetWakatimeUser":
		return GetWakatimeUser
	case "GetWakatimeUseragents":
		return GetWakatimeUseragents
	case "PostDiagnostics":
		return PostDiagnostics
	case "PostHeartbeat":
		return PostHeartbeat
	case "PostHeartbeat2":
		return PostHeartbeat2
	case "PostHeartbeat3":
		return PostHeartbeat3
	case "PostHeartbeat4":
		return PostHeartbeat4
	case "PostHeartbeat5":
		return PostHeartbeat5
	case "PostHeartbeat6":
		return PostHeartbeat6
	case "PostHeartbeat7":
		return PostHeartbeat7
	case "PostHeartbeat8":
		return PostHeartbeat8
	case "Statusbar":
		return Statusbar
	default:
		return nil
	}
}

func sdkMethodNormalize(value string) string {
	return strings.Map(func(character rune) rune {
		if character >= 'a' && character <= 'z' || character >= '0' && character <= '9' {
			return character
		}
		if character >= 'A' && character <= 'Z' {
			return character + ('a' - 'A')
		}
		return -1
	}, value)
}

func sdkMethodIsUpload(target reflect.Type) bool {
	uploadType := reflect.TypeOf(UploadFile{})
	if target.Kind() == reflect.Ptr {
		target = target.Elem()
	}
	return target == uploadType
}

func sdkMethodDecode(raw json.RawMessage, target reflect.Type) reflect.Value {
	if len(raw) == 0 {
		return reflect.Zero(target)
	}
	// A multipart file part is a plain string in the shared fixture; the SDK
	// models it as a struct carrying the bytes plus filename metadata.
	if sdkMethodIsUpload(target) {
		uploadType := reflect.TypeOf(UploadFile{})
		var text string
		if err := json.Unmarshal(raw, &text); err == nil {
			file := reflect.ValueOf(UploadFile{
				Data:        []byte(text),
				Filename:    "upload.bin",
				ContentType: "application/octet-stream",
			})
			if target.Kind() != reflect.Ptr {
				return file
			}
			boxed := reflect.New(uploadType)
			boxed.Elem().Set(file)
			return boxed
		}
	}
	// A repeated file part arrives as an array of those same strings.
	if target.Kind() == reflect.Slice && sdkMethodIsUpload(target.Elem()) {
		var items []json.RawMessage
		if err := json.Unmarshal(raw, &items); err == nil {
			files := reflect.MakeSlice(target, 0, len(items))
			for _, item := range items {
				files = reflect.Append(files, sdkMethodDecode(item, target.Elem()))
			}
			return files
		}
	}
	// An optional repeated file part is a pointer to that array.
	if target.Kind() == reflect.Ptr && target.Elem().Kind() == reflect.Slice && sdkMethodIsUpload(target.Elem().Elem()) {
		boxed := reflect.New(target.Elem())
		boxed.Elem().Set(sdkMethodDecode(raw, target.Elem()))
		return boxed
	}
	// A union of mixed scalars (OpenAI's max_output_tokens is
	// oneOf [integer, "inf"]) collapses to the string variant in the generated
	// signature, so the fixture's numeric value arrives as its literal text —
	// exactly what a caller has to pass.
	scalar := target
	if scalar.Kind() == reflect.Ptr {
		scalar = scalar.Elem()
	}
	if scalar.Kind() == reflect.String && raw[0] != '"' && raw[0] != 'n' {
		text := reflect.ValueOf(string(raw)).Convert(scalar)
		if target.Kind() != reflect.Ptr {
			return text
		}
		boxed := reflect.New(scalar)
		boxed.Elem().Set(text)
		return boxed
	}
	value := reflect.New(target)
	if err := json.Unmarshal(raw, value.Interface()); err != nil {
		panic(err)
	}
	return value.Elem()
}

func sdkMethodStruct(caseData sdkMethodCase, target reflect.Type) reflect.Value {
	value := reflect.New(target).Elem()
	byName := map[string]json.RawMessage{}
	for name, raw := range caseData.Arguments {
		byName[sdkMethodNormalize(name)] = raw
	}
	for index := 0; index < target.NumField(); index++ {
		field := target.Field(index)
		raw, ok := byName[sdkMethodNormalize(field.Name)]
		if !ok || !value.Field(index).CanSet() {
			continue
		}
		value.Field(index).Set(sdkMethodDecode(raw, field.Type))
	}
	return value
}

func sdkMethodParamsCoverArguments(caseData sdkMethodCase, target reflect.Type) bool {
	if target.Kind() != reflect.Struct || !strings.HasSuffix(target.Name(), "Params") || len(caseData.ArgumentOrder) == 0 {
		return false
	}
	fields := make(map[string]bool, target.NumField())
	for index := 0; index < target.NumField(); index++ {
		fields[sdkMethodNormalize(target.Field(index).Name)] = true
	}
	for _, name := range caseData.ArgumentOrder {
		if !fields[sdkMethodNormalize(name)] {
			return false
		}
	}
	return true
}

func sdkMethodInvoke(caseData sdkMethodCase, config *ClientConfig) (any, error) {
	callable := reflect.ValueOf(sdkMethodByName(caseData.MethodName))
	typeOf := callable.Type()
	values := make([]reflect.Value, 0, typeOf.NumIn())
	argumentIndex := 0
	contextType := reflect.TypeOf((*context.Context)(nil)).Elem()
	configType := reflect.TypeOf(config)
	// Generated methods take ClientConfig by value; only the config accessors
	// deal in pointers. Match both so the configured base URL actually reaches
	// the call instead of the parameter being rebuilt as an empty struct.
	configValueType := configType.Elem()
	// The fixture's argument order is read back from the generated signature, so
	// in positional mode it lines up one-to-one with the callable's own
	// parameters. Object mode instead collapses every argument into a single
	// Params struct, and only there may a Params parameter skip the order. A
	// request body model that happens to be named ...Params is positional and
	// must consume its slot, or every later argument shifts by one.
	// The trailing variadic slot is the per-call RequestOption list, never a
	// spec argument; calls leave it empty.
	parameterCount := typeOf.NumIn()
	if typeOf.IsVariadic() {
		parameterCount--
	}
	callableArity := 0
	for index := 0; index < parameterCount; index++ {
		target := typeOf.In(index)
		if target.Implements(contextType) || target == configValueType || target == configType {
			continue
		}
		callableArity++
	}
	// A one-field object-style Params wrapper has the same arity as its source
	// operation. Use its fields to distinguish it from a positional body model.
	collapseParams := callableArity != len(caseData.ArgumentOrder)
	if !collapseParams && callableArity == 1 {
		for index := 0; index < parameterCount; index++ {
			if sdkMethodParamsCoverArguments(caseData, typeOf.In(index)) {
				collapseParams = true
				break
			}
		}
	}
	for index := 0; index < parameterCount; index++ {
		target := typeOf.In(index)
		switch {
		case target.Implements(contextType):
			values = append(values, reflect.ValueOf(context.Background()))
		case target == configValueType:
			values = append(values, reflect.ValueOf(*config))
		case target == configType:
			values = append(values, reflect.ValueOf(config))
		// NullableValue[T] and any other struct parameter stays positional.
		case collapseParams && target.Kind() == reflect.Struct && strings.HasSuffix(target.Name(), "Params"):
			values = append(values, sdkMethodStruct(caseData, target))
		default:
			name := caseData.ArgumentOrder[argumentIndex]
			argumentIndex++
			values = append(values, sdkMethodDecode(caseData.Arguments[name], target))
		}
	}
	results := callable.Call(values)
	if caseData.Mode == "stream" {
		events := make([]any, 0)
		for {
			value, ok := results[0].Recv()
			if !ok {
				break
			}
			events = append(events, value.Interface())
		}
		if len(results) > 1 && results[1].Kind() == reflect.Chan {
			for {
				value, ok := results[1].Recv()
				if !ok {
					break
				}
				if err, ok := value.Interface().(error); ok && err != nil {
					return nil, err
				}
			}
		}
		if len(events) == 1 {
			return events[0], nil
		}
		return events, nil
	}
	if len(results) > 0 {
		if err, ok := results[len(results)-1].Interface().(error); ok && err != nil {
			return nil, err
		}
	}
	if len(results) == 0 {
		return nil, nil
	}
	return results[0].Interface(), nil
}

// A Go struct field carries omitempty, and a non-pointer struct field cannot
// hold null distinctly from its zero value. Both are deliberate, so re-encoding
// a decoded response legitimately loses "present but empty" — an expectation of
// an empty value is satisfied by an absent or zero one, and by nothing else.
func sdkMethodEmpty(value any) bool {
	switch typed := value.(type) {
	case nil:
		return true
	case string:
		return typed == ""
	case bool:
		return !typed
	case float64:
		return typed == 0
	case []any:
		return len(typed) == 0
	case map[string]any:
		for _, item := range typed {
			if !sdkMethodEmpty(item) {
				return false
			}
		}
		return true
	}
	return false
}

func sdkMethodRepresentative(actual any, expected any) bool {
	if sdkMethodEmpty(expected) && sdkMethodEmpty(actual) {
		return true
	}
	switch wanted := expected.(type) {
	case map[string]any:
		got, ok := actual.(map[string]any)
		if !ok {
			return false
		}
		actualByName := map[string]any{}
		for name, value := range got {
			actualByName[sdkMethodNormalize(name)] = value
		}
		for name, value := range wanted {
			// An exact key wins: distinct wire keys (foo-bar, foo_bar) share a normalized name.
			child, exists := got[name]
			if !exists {
				child, exists = actualByName[sdkMethodNormalize(name)]
			}
			if !exists {
				if sdkMethodEmpty(value) {
					continue
				}
				return false
			}
			if !sdkMethodRepresentative(child, value) {
				return false
			}
		}
		return true
	case []any:
		got, ok := actual.([]any)
		if !ok || len(got) != len(wanted) {
			return false
		}
		for index := range wanted {
			if !sdkMethodRepresentative(got[index], wanted[index]) {
				return false
			}
		}
		return true
	default:
		return reflect.DeepEqual(actual, expected)
	}
}

func TestGeneratedMethodsReachMockAndDecodeResponses(t *testing.T) {
	baseURL := os.Getenv("SDK_METHOD_TEST_BASE_URL")
	if baseURL == "" {
		t.Skip("run ./scripts/test to start the generated mock server")
	}
	bytes, err := os.ReadFile("test/sdk-method-cases.json")
	if err != nil {
		t.Fatal(err)
	}
	var fixture struct {
		Cases []sdkMethodCase `json:"cases"`
	}
	if err := json.Unmarshal(bytes, &fixture); err != nil {
		t.Fatal(err)
	}
	config := GetConfig()
	config.BaseURL = baseURL
	Configure(config)
	for _, caseData := range fixture.Cases {
		caseData := caseData
		t.Run(caseData.ID, func(t *testing.T) {
			actual, callErr := sdkMethodInvoke(caseData, config)
			if callErr != nil {
				t.Fatal(callErr)
			}
			if caseData.Response.Kind == "empty" {
				if actual != nil {
					t.Fatalf("expected empty response, got %#v", actual)
				}
				return
			}
			encoded, marshalErr := json.Marshal(actual)
			if marshalErr != nil {
				t.Fatal(marshalErr)
			}
			if caseData.Response.Kind == "bytes" {
				value := reflect.ValueOf(actual)
				if value.Len() != caseData.Response.ByteLength {
					t.Fatalf("decoded %d bytes, expected %d", value.Len(), caseData.Response.ByteLength)
				}
				return
			}
			var got any
			var expected any
			if err := json.Unmarshal(encoded, &got); err != nil {
				t.Fatal(err)
			}
			if err := json.Unmarshal(caseData.Response.Expected, &expected); err != nil {
				t.Fatal(err)
			}
			if !sdkMethodRepresentative(got, expected) {
				t.Fatalf("%s decoded %s, expected representative %s", caseData.MethodName, encoded, caseData.Response.Expected)
			}
		})
	}
}
