// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import (
	"context"
	"strings"
	"testing"
	"time"
)

func TestEncodePathSegment(t *testing.T) {
	got := EncodePathSegment("/ ?#%雪")
	if got != "%2F%20%3F%23%25%E9%9B%AA" {
		t.Fatalf("unexpected encoded path segment: %q", got)
	}
}

func TestQueryArrayStyles(t *testing.T) {
	got := appendQueryString("https://example.test/resource", map[string]any{
		"repeated": QueryValue{Value: []string{"a", "雪"}, Style: "form", Explode: true},
		"csv":      QueryValue{Value: []string{"a", "b"}, Style: "form", Explode: false},
	})
	if !strings.Contains(got, "repeated=a") || !strings.Contains(got, "repeated=%E9%9B%AA") {
		t.Fatalf("repeated query values were not serialized independently: %s", got)
	}
	if !strings.Contains(got, "csv=a%2Cb") {
		t.Fatalf("comma-delimited query value was not serialized correctly: %s", got)
	}
}

func TestRequestLayerUsesFakeMiddleware(t *testing.T) {
	type probeResponse struct {
		OK bool
	}
	cfg := &ClientConfig{
		BaseURL: "https://example.test",
		Middleware: []Middleware{
			func(_ context.Context, req *SdkRequest, _ SdkNext) (*SdkRawResponse, error) {
				if req.Method != "GET" || req.URL != "https://example.test/probe" {
					t.Fatalf("unexpected request: %s %s", req.Method, req.URL)
				}
				return &SdkRawResponse{
					StatusCode: 200,
					Headers:    map[string]string{"x-request-id": "fake-id"},
					Body:       []byte{123, 34, 111, 107, 34, 58, 116, 114, 117, 101, 125},
					RequestID:  "fake-id",
					Latency:    time.Millisecond,
					Attempt:    req.Attempt,
				}, nil
			},
		},
	}
	response, err := DoCfg[probeResponse](context.Background(), cfg, "GET", "/probe", &RequestOpts{OperationID: "probe"})
	if err != nil {
		t.Fatalf("request failed: %v", err)
	}
	if !response.Data.OK || response.RequestID != "fake-id" {
		t.Fatalf("unexpected response: %#v", response)
	}
}
