// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

// SDKVersion is the release version of this generated SDK.
const SDKVersion = "1.0.0"
