// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import (
	"context"
	"encoding/json"
	"errors"
	"net/url"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
	"testing"
	"time"
)

// Data-driven behavior suite: replays every shared behavior case through the
// request layer with a fake middleware transport. Schema-independent — the
// fixture in test/sdk-behavior-cases.json carries the per-operation detail.

type behaviorQuery struct {
	Name       string          `json:"name"`
	Style      string          `json:"style"`
	Explode    bool            `json:"explode"`
	Value      json.RawMessage `json:"value"`
	Serialized json.RawMessage `json:"serialized"`
}

type behaviorRequest struct {
	Method         string            `json:"method"`
	PathTemplate   string            `json:"pathTemplate"`
	PathParameters map[string]any    `json:"pathParameters"`
	Query          []behaviorQuery   `json:"query"`
	Headers        map[string]string `json:"headers"`
	Body           json.RawMessage   `json:"body"`
	BodyKind       *string           `json:"bodyKind"`
	ContentType    *string           `json:"contentType"`
}

type behaviorExpect struct {
	Method          string            `json:"method"`
	Path            string            `json:"path"`
	Query           string            `json:"query"`
	URL             string            `json:"url"`
	Headers         map[string]string `json:"headers"`
	BodyText        *string           `json:"bodyText"`
	MultipartFields []string          `json:"multipartFields"`
}

type behaviorResponse struct {
	Kind      string          `json:"kind"`
	Status    int             `json:"status"`
	MediaType *string         `json:"mediaType"`
	Body      string          `json:"body"`
	Value     json.RawMessage `json:"value"`
	ErrorKind string          `json:"errorKind"`
}

// The status sentinels a typed HTTP error matches, keyed by fixture error kind.
var behaviorErrorSentinels = map[string]error{
	"BadRequest":          ErrBadRequest,
	"Unauthorized":        ErrUnauthorized,
	"PermissionDenied":    ErrPermissionDenied,
	"NotFound":            ErrNotFound,
	"Conflict":            ErrConflict,
	"UnprocessableEntity": ErrUnprocessableEntity,
	"RateLimit":           ErrRateLimit,
	"InternalServer":      ErrInternalServer,
}

type behaviorCase struct {
	ID          string           `json:"id"`
	OperationID string           `json:"operationId"`
	Kinds       []string         `json:"kinds"`
	Request     *behaviorRequest `json:"request"`
	Expect      behaviorExpect   `json:"expect"`
	Response    behaviorResponse `json:"response"`
}

type behaviorFixture struct {
	BaseURL        string            `json:"baseUrl"`
	OperationCount int               `json:"operationCount"`
	AuthHeaders    map[string]string `json:"authHeaders"`
	Cases          []behaviorCase    `json:"cases"`
}

func loadBehaviorFixture(t *testing.T) behaviorFixture {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join("test", "sdk-behavior-cases.json"))
	if err != nil {
		t.Fatalf("read behavior fixture: %v", err)
	}
	var fixture behaviorFixture
	if err := json.Unmarshal(raw, &fixture); err != nil {
		t.Fatalf("parse behavior fixture: %v", err)
	}
	return fixture
}

// normalizeQuery compares query strings independent of the space encoding
// ("+" in form encoding, "%20" under RFC 3986) and of pair order.
func normalizeQuery(raw string) string {
	parsed, err := url.ParseQuery(strings.ReplaceAll(raw, "+", "%20"))
	if err != nil {
		return raw
	}
	pairs := make([]string, 0, len(parsed))
	for name, values := range parsed {
		sorted := append([]string(nil), values...)
		sort.Strings(sorted)
		pairs = append(pairs, name+"="+strings.Join(sorted, ","))
	}
	sort.Strings(pairs)
	return strings.Join(pairs, "&")
}

func decodeAny(raw json.RawMessage) any {
	if len(raw) == 0 {
		return nil
	}
	var value any
	if err := json.Unmarshal(raw, &value); err != nil {
		return nil
	}
	return value
}

func TestGeneratedBehaviorCases(t *testing.T) {
	fixture := loadBehaviorFixture(t)
	if (len(fixture.Cases) == 0) != (fixture.OperationCount == 0) {
		t.Fatal("behavior fixture presence does not match ordinary operations")
	}
	for _, item := range fixture.Cases {
		t.Run(item.ID, func(t *testing.T) {
			var seen *SdkRequest
			cfg := &ClientConfig{
				BaseURL:     fixture.BaseURL,
				Auth:        &ClientAuthConfig{Headers: fixture.AuthHeaders},
				Retry:       &RetryConfig{MaxAttempts: 1},
				Idempotency: &IdempotencyConfig{Enabled: false, Methods: []string{}},
				Middleware: []Middleware{
					func(_ context.Context, req *SdkRequest, _ SdkNext) (*SdkRawResponse, error) {
						seen = req
						headers := map[string]string{}
						if item.Response.MediaType != nil {
							headers["content-type"] = *item.Response.MediaType
						}
						body := []byte(item.Response.Body)
						if item.Response.Status == 204 {
							body = nil
						}
						return &SdkRawResponse{
							StatusCode: item.Response.Status,
							Headers:    headers,
							Body:       body,
							Latency:    time.Millisecond,
							Attempt:    req.Attempt,
						}, nil
					},
				},
			}

			opts := &RequestOpts{OperationID: item.OperationID, Query: map[string]any{}}
			method := "GET"
			path := "/behavior/" + item.ID
			if item.Request != nil {
				method = item.Request.Method
				path = item.Request.PathTemplate
				for name, value := range item.Request.PathParameters {
					path = strings.ReplaceAll(path, "{"+name+"}", EncodePathSegment(value))
				}
				for _, parameter := range item.Request.Query {
					value := decodeAny(parameter.Value)
					if value == nil {
						continue
					}
					opts.Query[parameter.Name] = QueryValue{
						Value:   value,
						Style:   parameter.Style,
						Explode: parameter.Explode,
					}
				}
				if len(item.Request.Headers) > 0 {
					opts.Headers = item.Request.Headers
				}
				if item.Request.BodyKind != nil {
					opts.Body = decodeAny(item.Request.Body)
					if item.Request.ContentType != nil {
						opts.ContentType = *item.Request.ContentType
					}
				}
			}

			// One entry point per response decoder — Go picks the decoder through the
			// generic return type, exactly as the generated methods do.
			var (
				status  int
				decoded any
				err     error
			)
			switch item.Response.Kind {
			case "text":
				var response *SdkResponse[string]
				response, err = DoRawCfg(context.Background(), cfg, method, path, opts)
				if err == nil {
					status, decoded = response.StatusCode, response.Data
				}
			case "bytes":
				var response *SdkResponse[[]byte]
				response, err = DoBytesCfg(context.Background(), cfg, method, path, opts)
				if err == nil {
					status, decoded = response.StatusCode, len(response.Data)
				}
			case "empty":
				var response *SdkResponse[struct{}]
				response, err = DoEmptyCfg(context.Background(), cfg, method, path, opts)
				if err == nil {
					status = response.StatusCode
				}
			default:
				var response *SdkResponse[json.RawMessage]
				response, err = DoCfg[json.RawMessage](context.Background(), cfg, method, path, opts)
				if err == nil {
					status, decoded = response.StatusCode, decodeAny(response.Data)
				}
			}
			if item.Response.Status >= 400 {
				httpError, ok := err.(*SdkHttpError)
				if !ok {
					t.Fatalf("expected *SdkHttpError for status %d, got %v", item.Response.Status, err)
				}
				if httpError.StatusCode != item.Response.Status {
					t.Fatalf("typed error status: got %d want %d", httpError.StatusCode, item.Response.Status)
				}
				for kind, sentinel := range behaviorErrorSentinels {
					if want := kind == item.Response.ErrorKind; errors.Is(err, sentinel) != want {
						t.Fatalf("typed error kind for %s: errors.Is(err, Err%s) should be %t", item.ID, kind, want)
					}
				}
				if len(item.Response.Value) > 0 &&
					!reflect.DeepEqual(decodeAny(httpError.Body), decodeAny(item.Response.Value)) {
					t.Fatalf("typed error body mismatch for %s", item.ID)
				}
			} else {
				if err != nil {
					t.Fatalf("request failed: %v", err)
				}
				if status != item.Response.Status {
					t.Fatalf("status: got %d want %d", status, item.Response.Status)
				}
				if len(item.Response.Value) > 0 && item.Response.Kind == "json" &&
					!reflect.DeepEqual(decoded, decodeAny(item.Response.Value)) {
					t.Fatalf("decoded response mismatch for %s", item.ID)
				}
				if item.Response.Kind == "text" && len(item.Response.Value) > 0 {
					var want string
					_ = json.Unmarshal(item.Response.Value, &want)
					if decoded != want {
						t.Fatalf("decoded text mismatch for %s", item.ID)
					}
				}
			}

			if item.Request == nil {
				return
			}
			if seen == nil {
				t.Fatal("middleware never saw a request")
			}
			if seen.Method != item.Expect.Method {
				t.Fatalf("method: got %s want %s", seen.Method, item.Expect.Method)
			}
			gotURL, wantURL := seen.URL, item.Expect.URL
			gotBase, gotQuery, _ := strings.Cut(gotURL, "?")
			wantBase, wantQuery, _ := strings.Cut(wantURL, "?")
			if gotBase != wantBase {
				t.Fatalf("url path: got %s want %s", gotBase, wantBase)
			}
			if normalizeQuery(gotQuery) != normalizeQuery(wantQuery) {
				t.Fatalf("url query: got %s want %s", gotQuery, wantQuery)
			}
			for name, value := range item.Expect.Headers {
				actual := ""
				for header, headerValue := range seen.Headers {
					if strings.EqualFold(header, name) {
						actual = headerValue
					}
				}
				if name == "content-type" && item.Expect.MultipartFields != nil {
					if !strings.HasPrefix(actual, "multipart/form-data") {
						t.Fatalf("multipart content type: got %s", actual)
					}
					continue
				}
				if actual != value {
					t.Fatalf("header %s: got %q want %q", name, actual, value)
				}
			}
			if item.Expect.BodyText != nil && item.Request.BodyKind != nil && *item.Request.BodyKind == "json" {
				var got, want any
				_ = json.Unmarshal(seen.Body, &got)
				_ = json.Unmarshal([]byte(*item.Expect.BodyText), &want)
				if !reflect.DeepEqual(got, want) {
					t.Fatalf("request body mismatch for %s", item.ID)
				}
			}
		})
	}
}
