// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"reflect"
	"runtime"
	"strings"
	"sync"
	"time"
)

// Ptr returns a pointer to its argument. Useful for setting optional fields
// on validator option structs without temporary local variables.
func Ptr[T any](v T) *T { return &v }

// ConstructModel is the single construction path behind every generated
// New<Model> entry point. The assembled fields are encoded and decoded through
// the model's own decoding path, so a value built in memory is accepted on
// exactly the same terms as a decoded response and reports the same
// *SdkValidationError. The returned pointer refers to the caller's fields, so
// construction never rewrites a value it accepted.
func ConstructModel[T any](fields T) (*T, error) {
	data, err := json.Marshal(fields)
	if err != nil {
		return nil, err
	}
	var decoded T
	if err := json.Unmarshal(data, &decoded); err != nil {
		return nil, err
	}
	return &fields, nil
}

// SdkResponse is the envelope returned by the low-level request layer.
// High-level endpoint methods unwrap .Data automatically.
type SdkResponse[T any] struct {
	Data       T
	StatusCode int
	Headers    map[string]string
	RequestID  string
	Latency    time.Duration
	Attempt    int
}

// ClientAuthConfig is declared in sdk_auth.go (its fields depend on which
// securitySchemes are declared in the spec).
// LoggingConfig configures error logging. When Enabled, failed requests are
// POSTed to Endpoint as JSON; the Environment/Release/User/Tags fields are
// forwarded with every logged event as enrichment.
type LoggingConfig struct {
	Enabled     bool
	Endpoint    string
	APIKey      string
	Environment string
	Release     string
	User        map[string]any
	Tags        map[string]any
	// FilterPII defaults to enabled. Set it to sdk.Ptr(false) only for a
	// deliberately trusted, private telemetry destination.
	FilterPII *bool
}

// RetryConfig governs automatic retry behaviour.
type RetryConfig struct {
	MaxAttempts int
	RetryOn     []int
	Backoff     time.Duration
	MaxBackoff  time.Duration
}

// IdempotencyConfig controls client-side Idempotency-Key generation.
// Enabled by default for POST/PATCH so retried writes don't double-execute.
type IdempotencyConfig struct {
	Enabled    bool
	HeaderName string   // defaults to "Idempotency-Key"
	Methods    []string // defaults to ["POST", "PATCH"]
}

// SdkRequest is the per-attempt HTTP request visible to middleware. Mutating
// Headers or Body before calling next() changes what hits the wire. Meta is a
// free-form scratch space middleware can use to share state across the chain.
type SdkRequest struct {
	Method      string
	URL         string
	Headers     map[string]string
	Body        []byte
	ContentType string
	OperationID string
	Attempt     int
	Meta        map[string]any
}

// SdkRawResponse is the response returned by the middleware chain. The Data
// envelope is decoded later by Do[T]; middleware sees the raw body bytes.
type SdkRawResponse struct {
	StatusCode int
	Headers    map[string]string
	Body       []byte
	RequestID  string
	Latency    time.Duration
	Attempt    int
}

// SdkNext is the next link in the middleware chain.
type SdkNext func(ctx context.Context, req *SdkRequest) (*SdkRawResponse, error)

// Middleware wraps a single HTTP attempt. Compose patterns like logging,
// tracing, caching, custom auth, or response transforms without forking
// the generator.
//
// Example:
//
//	logging := func(ctx context.Context, req *sdk.SdkRequest, next sdk.SdkNext) (*sdk.SdkRawResponse, error) {
//	    resp, err := next(ctx, req)
//	    log.Printf("%s %s -> %d", req.Method, req.URL, resp.StatusCode)
//	    return resp, err
//	}
//	sdk.Configure(&sdk.ClientConfig{ Middleware: []sdk.Middleware{logging} })
type Middleware func(ctx context.Context, req *SdkRequest, next SdkNext) (*SdkRawResponse, error)

// ClientConfig is the top-level SDK configuration.
type ClientConfig struct {
	BaseURL     string
	Auth        *ClientAuthConfig
	Logging     *LoggingConfig
	Retry       *RetryConfig
	Idempotency *IdempotencyConfig
	Middleware  []Middleware
	Timeout     time.Duration
	OnResponse  func(StatusCode int, Headers map[string]string, RequestID string, Latency time.Duration, Attempt int)
}

// RequestOpts carries optional inputs for a single request. Body is any typed
// value (struct, slice, primitive); the request layer marshals it to JSON.
type RequestOpts struct {
	Query       map[string]any
	Body        any
	ContentType string
	OperationID string
	// Headers set by a request hook, merged over the auto/auth headers.
	Headers map[string]string
	// Per-call options the operation's caller passed.
	Options []RequestOption
}

// RequestOption adjusts a single call. Every generated operation accepts any
// number of them as its last arguments; each applies to that call only, over
// the client config.
type RequestOption func(*requestOptions)

type requestOptions struct {
	headers        map[string]string
	idempotencyKey *string
	retry          *RetryConfig
	timeout        time.Duration
}

// WithHeader sets one request header, over the auth and operation headers.
func WithHeader(name, value string) RequestOption {
	return func(o *requestOptions) {
		if o.headers == nil {
			o.headers = map[string]string{}
		}
		o.headers[name] = value
	}
}

// WithIdempotencyKey replaces the generated Idempotency-Key; an empty key
// sends none. Streaming operations ignore it.
func WithIdempotencyKey(key string) RequestOption {
	return func(o *requestOptions) { o.idempotencyKey = &key }
}

// WithRetry replaces the client's retry policy. Streaming operations ignore it.
func WithRetry(retry RetryConfig) RequestOption {
	return func(o *requestOptions) { o.retry = &retry }
}

// WithTimeout replaces the client's per-attempt timeout. Streaming operations
// ignore it.
func WithTimeout(timeout time.Duration) RequestOption {
	return func(o *requestOptions) { o.timeout = timeout }
}

func resolveRequestOptions(options []RequestOption) requestOptions {
	var resolved requestOptions
	for _, option := range options {
		option(&resolved)
	}
	return resolved
}

// UploadFile is one typed multipart file part.
type UploadFile struct {
	Data        []byte
	Filename    string
	ContentType string
}

type multipartJSON struct {
	Value       any
	ContentType string
}

// MultipartJSONPart marks a structured multipart field and retains its media type.
func MultipartJSONPart(value any, contentType string) any {
	if isNilValue(value) {
		return nil
	}
	return multipartJSON{Value: value, ContentType: contentType}
}

// QueryValue carries the OpenAPI style/explode contract for one parameter.
type QueryValue struct {
	Value   any
	Style   string
	Explode bool
}

// EncodePathSegment percent-encodes one path component. url.PathEscape leaves
// the sub-delims that RFC 3986 allows in a segment (":", "@", "$", "&", "+",
// ",", ";", "=") unescaped, but the other nine SDKs encode them, and the same
// argument must produce the same URL in every language — so escape them too.
func EncodePathSegment(value any) string {
	text := fmt.Sprint(value)
	// A path array uses the default `simple` style: its members comma-joined.
	if rv := reflect.ValueOf(value); rv.Kind() == reflect.Slice || rv.Kind() == reflect.Array {
		members := make([]string, rv.Len())
		for index := range members {
			members[index] = fmt.Sprint(rv.Index(index).Interface())
		}
		text = strings.Join(members, ",")
	}
	escaped := url.PathEscape(text)
	for _, pair := range [][2]string{
		{":", "%3A"}, {"@", "%40"}, {"$", "%24"}, {"&", "%26"},
		{"+", "%2B"}, {",", "%2C"}, {";", "%3B"}, {"=", "%3D"},
	} {
		escaped = strings.ReplaceAll(escaped, pair[0], pair[1])
	}
	return escaped
}

// OperationHeaders converts typed header values and omits nil optionals.
func OperationHeaders(values map[string]any) map[string]string {
	headers := map[string]string{}
	for name, value := range values {
		if isNilValue(value) {
			continue
		}
		headers[name] = scalarString(value)
	}
	return headers
}

// RequestContext is passed to an operation's beforeRequest hook. Mutate Query,
// Body, or Headers (or read Params), then return it — the returned context is
// what the SDK sends. (SDK Studio "custom code".)
type RequestContext struct {
	Params  map[string]any
	Query   map[string]any
	Body    map[string]any
	Headers map[string]string
}

var (
	defaultRetry = RetryConfig{
		MaxAttempts: 3,
		RetryOn:     []int{408, 425, 429, 500, 502, 503, 504},
		Backoff:     500 * time.Millisecond,
		MaxBackoff:  8000 * time.Millisecond,
	}
	defaultIdempotency = IdempotencyConfig{
		Enabled:    true,
		HeaderName: "Idempotency-Key",
		Methods:    []string{"POST", "PATCH"},
	}
	// The reporting endpoint is baked in from the dashboard monitoring config, but
	// Enabled is false at rest: nothing is reported until the consumer opts in via
	// SetLoggingConfig or a ClientConfig whose Logging is enabled.
	defaultLogging = LoggingConfig{
		Enabled:     false,
		Endpoint:    "",
		APIKey:      "",
		Environment: "",
		FilterPII:   Ptr(true),
	}
	defaultTimeout = 30000 * time.Millisecond

	httpClient   = &http.Client{}
	globalConfig *ClientConfig
	configMu     sync.RWMutex
)

// idempotentMethods retry on any retryable status. POST/PATCH only retry on
// 429/503 — the rest of the 5xx codes may have already mutated server state.
var (
	idempotentMethods       = map[string]struct{}{"GET": {}, "HEAD": {}, "PUT": {}, "DELETE": {}, "OPTIONS": {}}
	alwaysRetryableStatuses = map[int]struct{}{429: {}, 503: {}}
	requestIDHeaders        = []string{"x-request-id", "openai-request-id", "x-amzn-requestid"}
)

// Configure replaces the global SDK configuration.
func Configure(cfg *ClientConfig) {
	configMu.Lock()
	defer configMu.Unlock()
	globalConfig = cfg
}

// GetConfig returns the current global SDK configuration.
func GetConfig() *ClientConfig {
	configMu.RLock()
	defer configMu.RUnlock()
	if globalConfig == nil {
		return &ClientConfig{BaseURL: defaultBaseURL}
	}
	return globalConfig
}

// SetLoggingConfig turns SDK logging on and configures it in one call.
//
// Logging is OFF by default — this SDK reports nothing until you ask it to.
// There are exactly two ways to turn it on:
//
//	sdk.Configure(&sdk.ClientConfig{Logging: &sdk.LoggingConfig{Enabled: true}})  // at init
//	sdk.SetLoggingConfig(nil)                                                     // any time after
//
// Reports go to the endpoint this build was generated with, or to the Endpoint
// you pass; with neither, nothing is sent. Pass a LoggingConfig to set the
// endpoint, environment, release, tags, etc.
//
// This call ALWAYS enables logging — Enabled on the passed config is ignored,
// because its zero value is false (logging is opt-in) and honouring it would make
// the obvious "configure and turn on" call a silent no-op. To turn logging back
// off:  sdk.GetConfig().Logging.Enabled = false
func SetLoggingConfig(logging *LoggingConfig) *LoggingConfig {
	configMu.Lock()
	defer configMu.Unlock()
	if globalConfig == nil {
		globalConfig = &ClientConfig{BaseURL: defaultBaseURL}
	}
	merged := mergeLogging(logging)
	merged.Enabled = true
	globalConfig.Logging = &merged
	return globalConfig.Logging
}

// Do executes an HTTP request with the global config and decodes JSON into T.
func Do[T any](ctx context.Context, method, path string, opts *RequestOpts) (*SdkResponse[T], error) {
	return DoCfg[T](ctx, GetConfig(), method, path, opts)
}

// DoCfg executes an HTTP request with an explicit config and decodes JSON into T.
func DoCfg[T any](ctx context.Context, cfg *ClientConfig, method, path string, opts *RequestOpts) (*SdkResponse[T], error) {
	resp, body, err := exchange(ctx, cfg, method, path, opts)
	if err != nil {
		return nil, err
	}
	out := &SdkResponse[T]{
		StatusCode: resp.statusCode,
		Headers:    resp.headers,
		RequestID:  resp.requestID,
		Latency:    resp.latency,
		Attempt:    resp.attempt,
	}
	if len(body) > 0 {
		if err := json.Unmarshal(body, &out.Data); err != nil {
			return nil, fmt.Errorf("decode response: %w", err)
		}
	}
	return out, nil
}

// DoRaw returns the raw response body as a string. For non-JSON endpoints.
func DoRaw(ctx context.Context, method, path string, opts *RequestOpts) (*SdkResponse[string], error) {
	return DoRawCfg(ctx, GetConfig(), method, path, opts)
}

// DoRawCfg returns the raw response body as a string with explicit config.
func DoRawCfg(ctx context.Context, cfg *ClientConfig, method, path string, opts *RequestOpts) (*SdkResponse[string], error) {
	resp, body, err := exchange(ctx, cfg, method, path, opts)
	if err != nil {
		return nil, err
	}
	return &SdkResponse[string]{
		Data:       string(body),
		StatusCode: resp.statusCode,
		Headers:    resp.headers,
		RequestID:  resp.requestID,
		Latency:    resp.latency,
		Attempt:    resp.attempt,
	}, nil
}

// DoBytes returns a binary response without a text or JSON round-trip.
func DoBytes(ctx context.Context, method, path string, opts *RequestOpts) (*SdkResponse[[]byte], error) {
	return DoBytesCfg(ctx, GetConfig(), method, path, opts)
}

// DoBytesCfg is the explicit-config form of DoBytes.
func DoBytesCfg(ctx context.Context, cfg *ClientConfig, method, path string, opts *RequestOpts) (*SdkResponse[[]byte], error) {
	resp, body, err := exchange(ctx, cfg, method, path, opts)
	if err != nil {
		return nil, err
	}
	return &SdkResponse[[]byte]{
		Data:       append([]byte(nil), body...),
		StatusCode: resp.statusCode,
		Headers:    resp.headers,
		RequestID:  resp.requestID,
		Latency:    resp.latency,
		Attempt:    resp.attempt,
	}, nil
}

// DoEmpty executes an endpoint whose successful response has no body.
func DoEmpty(ctx context.Context, method, path string, opts *RequestOpts) (*SdkResponse[struct{}], error) {
	return DoEmptyCfg(ctx, GetConfig(), method, path, opts)
}

// DoEmptyCfg is the explicit-config form of DoEmpty.
func DoEmptyCfg(ctx context.Context, cfg *ClientConfig, method, path string, opts *RequestOpts) (*SdkResponse[struct{}], error) {
	resp, _, err := exchange(ctx, cfg, method, path, opts)
	if err != nil {
		return nil, err
	}
	return &SdkResponse[struct{}]{
		StatusCode: resp.statusCode,
		Headers:    resp.headers,
		RequestID:  resp.requestID,
		Latency:    resp.latency,
		Attempt:    resp.attempt,
	}, nil
}

// DoUnion runs a request and decodes the response via a union-aware unmarshaler.
func DoUnion[T any](ctx context.Context, method, path string, opts *RequestOpts, unmarshal func(any) T) (*SdkResponse[T], error) {
	return DoUnionCfg[T](ctx, GetConfig(), method, path, opts, unmarshal)
}

// DoUnionCfg runs a union request with explicit config.
func DoUnionCfg[T any](ctx context.Context, cfg *ClientConfig, method, path string, opts *RequestOpts, unmarshal func(any) T) (*SdkResponse[T], error) {
	resp, body, err := exchange(ctx, cfg, method, path, opts)
	if err != nil {
		return nil, err
	}
	out := &SdkResponse[T]{
		StatusCode: resp.statusCode,
		Headers:    resp.headers,
		RequestID:  resp.requestID,
		Latency:    resp.latency,
		Attempt:    resp.attempt,
	}
	if len(body) > 0 {
		var raw any
		if err := json.Unmarshal(body, &raw); err != nil {
			return nil, fmt.Errorf("decode response: %w", err)
		}
		out.Data = unmarshal(raw)
	}
	return out, nil
}

// DoAny returns a decoded any value for endpoints with no static schema.
func DoAny(ctx context.Context, method, path string, opts *RequestOpts) (*SdkResponse[any], error) {
	return DoAnyCfg(ctx, GetConfig(), method, path, opts)
}

// DoAnyCfg returns a decoded any value with explicit config.
func DoAnyCfg(ctx context.Context, cfg *ClientConfig, method, path string, opts *RequestOpts) (*SdkResponse[any], error) {
	resp, body, err := exchange(ctx, cfg, method, path, opts)
	if err != nil {
		return nil, err
	}
	out := &SdkResponse[any]{
		StatusCode: resp.statusCode,
		Headers:    resp.headers,
		RequestID:  resp.requestID,
		Latency:    resp.latency,
		Attempt:    resp.attempt,
	}
	if len(body) > 0 {
		if err := json.Unmarshal(body, &out.Data); err != nil {
			return nil, fmt.Errorf("decode response: %w", err)
		}
	}
	return out, nil
}

// ── internals ────────────────────────────────────────────────────────────────
type exchangeMeta struct {
	statusCode int
	headers    map[string]string
	requestID  string
	latency    time.Duration
	attempt    int
}

func exchange(ctx context.Context, cfg *ClientConfig, method, path string, opts *RequestOpts) (exchangeMeta, []byte, error) {
	if opts == nil {
		opts = &RequestOpts{}
	}

	method = strings.ToUpper(method)
	// Absolute URLs (used by url-style pagination follow links) bypass BaseURL.
	var baseURL string
	if strings.HasPrefix(path, "http://") || strings.HasPrefix(path, "https://") {
		baseURL = path
	} else {
		baseURL = cfg.BaseURL + path
	}

	contentType := opts.ContentType
	if contentType == "" {
		contentType = "application/json"
	}

	hasBody := opts.Body != nil
	bodyBytes, contentType, err := encodeBody(opts.Body, contentType)
	if err != nil {
		return exchangeMeta{}, nil, err
	}

	call := resolveRequestOptions(opts.Options)
	retry := mergeRetry(cfg.Retry)
	if call.retry != nil {
		retry = mergeRetry(call.retry)
	}
	idem := mergeIdempotency(cfg.Idempotency)
	timeout := cfg.Timeout
	if call.timeout > 0 {
		timeout = call.timeout
	}
	if timeout <= 0 {
		timeout = defaultTimeout
	}

	// One idempotency key per logical request — reused across retries so the
	// server can deduplicate.
	idempotencyKey := ""
	if call.idempotencyKey != nil {
		idempotencyKey = *call.idempotencyKey
	} else if idem.Enabled && containsString(idem.Methods, method) {
		idempotencyKey, err = generateIdempotencyKey()
		if err != nil {
			return exchangeMeta{}, nil, &SdkNetworkError{Cause: err}
		}
	}

	dispatch := composeMiddleware(cfg.Middleware, coreTransport(timeout))

	for attempt := 1; attempt <= retry.MaxAttempts; attempt++ {
		// Auth may mutate per-attempt (e.g. OAuth refresh). Re-apply on every retry.
		query := map[string]any{}
		for k, v := range opts.Query {
			query[k] = v
		}
		headers, err := buildHeaders(ctx, cfg, contentType, hasBody, query, opts.OperationID)
		if err != nil {
			return exchangeMeta{}, nil, err
		}
		for k, v := range opts.Headers {
			headers[k] = v
		}
		for k, v := range call.headers {
			headers[k] = v
		}
		if idempotencyKey != "" {
			headers[idem.HeaderName] = idempotencyKey
		}
		rawURL := baseURL
		if len(query) > 0 {
			rawURL = appendQueryString(rawURL, query)
		}

		req := &SdkRequest{
			Method:      method,
			URL:         rawURL,
			Headers:     headers,
			Body:        bodyBytes,
			ContentType: contentType,
			OperationID: opts.OperationID,
			Attempt:     attempt,
			Meta:        map[string]any{},
		}

		resp, err := dispatch(ctx, req)
		if err != nil {
			if errors.Is(err, context.DeadlineExceeded) {
				if attempt < retry.MaxAttempts {
					sleepBackoff(ctx, retry, attempt, "")
					continue
				}
				return exchangeMeta{}, nil, logAndReturn(cfg, method, path, opts.OperationID, &SdkTimeoutError{Elapsed: timeout})
			}
			if attempt < retry.MaxAttempts {
				sleepBackoff(ctx, retry, attempt, "")
				continue
			}
			return exchangeMeta{}, nil, logAndReturn(cfg, method, path, opts.OperationID, &SdkNetworkError{Cause: err})
		}

		meta := exchangeMeta{
			statusCode: resp.StatusCode,
			headers:    resp.Headers,
			requestID:  resp.RequestID,
			latency:    resp.Latency,
			attempt:    resp.Attempt,
		}

		if resp.StatusCode >= 200 && resp.StatusCode < 300 {
			if cfg.OnResponse != nil {
				cfg.OnResponse(meta.statusCode, meta.headers, meta.requestID, meta.latency, meta.attempt)
			}
			return meta, resp.Body, nil
		}

		if attempt < retry.MaxAttempts && shouldRetryStatus(method, resp.StatusCode, retry.RetryOn) {
			sleepBackoff(ctx, retry, attempt, resp.Headers["retry-after"])
			continue
		}

		return exchangeMeta{}, nil, logAndReturn(cfg, method, path, opts.OperationID, &SdkHttpError{
			StatusCode: resp.StatusCode,
			StatusText: http.StatusText(resp.StatusCode),
			Body:       resp.Body,
			Headers:    resp.Headers,
			RequestID:  resp.RequestID,
		})
	}

	return exchangeMeta{}, nil, &SdkNetworkError{Cause: fmt.Errorf("request '%s' produced no attempts", opts.OperationID)}
}

// logAndReturn fires the error logger (when configured) and returns the error
// unchanged, so terminal failures can be wrapped inline at each return site.
func logAndReturn(cfg *ClientConfig, method, path, operationID string, err error) error {
	logError(cfg, method, path, operationID, err)
	return err
}

// errorName maps a typed SDK error to the name the monitoring backend groups on.
func errorName(err error) string {
	switch err.(type) {
	case *SdkHttpError:
		return "SdkHttpError"
	case *SdkValidationError:
		return "SdkValidationError"
	case *SdkNetworkError:
		return "SdkNetworkError"
	case *SdkTimeoutError:
		return "SdkTimeoutError"
	default:
		return "error"
	}
}

// requestIDOf returns the request id carried by the typed SDK errors, if any.
func requestIDOf(err error) string {
	switch e := err.(type) {
	case *SdkHttpError:
		return e.RequestID
	case *SdkNetworkError:
		return e.RequestID
	case *SdkTimeoutError:
		return e.RequestID
	default:
		return ""
	}
}

const sourceContextLines = 5

// frameInApp reports whether a source file belongs to the application rather
// than the Go runtime or an installed module.
func frameInApp(file string) bool {
	if file == "" {
		return false
	}
	if strings.Contains(file, "/pkg/mod/") {
		return false
	}
	if root := runtime.GOROOT(); root != "" && strings.HasPrefix(file, root) {
		return false
	}
	return true
}
