// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import (
	"fmt"
	"strings"
	"time"
)

// ValidateEnum returns SdkValidationError if value is not in allowed.
func ValidateEnum[T comparable](field string, value T, allowed []T) error {
	for _, a := range allowed {
		if a == value {
			return nil
		}
	}
	parts := make([]string, len(allowed))
	for i, a := range allowed {
		parts[i] = fmt.Sprintf("%v", a)
	}
	return &SdkValidationError{
		Field:   field,
		Code:    "enum",
		Message: fmt.Sprintf("Validation failed for '%s': must be one of %s", field, strings.Join(parts, ", ")),
	}
}

// ValidateDate enforces YYYY-MM-DD date format.
func ValidateDate(field, value string) error {
	if _, err := time.Parse("2006-01-02", value); err != nil {
		return &SdkValidationError{Field: field, Code: "format:date", Message: fmt.Sprintf("Validation failed for '%s': must be a valid date (YYYY-MM-DD)", field)}
	}
	return nil
}
