// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import (
	"bytes"
	"context"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	mrand "math/rand"
	"mime/multipart"
	"net/http"
	"net/textproto"
	"net/url"
	"os"
	"reflect"
	"runtime"
	"sort"
	"strconv"
	"strings"
	"time"
)

// frameSourceContext reads a few lines around a frame so the dashboard can show
// the original code (best-effort: the source must be readable at runtime).
func frameSourceContext(file string, line int) map[string]any {
	if file == "" || line < 1 {
		return nil
	}
	data, err := os.ReadFile(file)
	if err != nil {
		return nil
	}
	lines := strings.Split(string(data), "\n")
	if line > len(lines) {
		return nil
	}
	idx := line - 1
	ctx := map[string]any{"contextLine": lines[idx]}
	start := idx - sourceContextLines
	if start < 0 {
		start = 0
	}
	if pre := lines[start:idx]; len(pre) > 0 {
		ctx["preContext"] = pre
	}
	end := idx + 1 + sourceContextLines
	if end > len(lines) {
		end = len(lines)
	}
	if post := lines[idx+1 : end]; len(post) > 0 {
		ctx["postContext"] = post
	}
	return ctx
}

// shortFuncName trims the package path from a fully-qualified function name.
func shortFuncName(fn string) string {
	if i := strings.LastIndex(fn, "/"); i >= 0 {
		fn = fn[i+1:]
	}
	return fn
}

// buildFrames captures the call stack at the failing SDK boundary (innermost
// first), with original-source context per frame, dropping the SDK's own
// logging plumbing from the top.
func buildFrames() []map[string]any {
	pcs := make([]uintptr, 64)
	n := runtime.Callers(2, pcs) // skip runtime.Callers + buildFrames
	if n == 0 {
		return nil
	}
	callerFrames := runtime.CallersFrames(pcs[:n])
	out := make([]map[string]any, 0, n)
	for {
		fr, more := callerFrames.Next()
		name := shortFuncName(fr.Function)
		if len(out) == 0 && (strings.Contains(name, "logError") || strings.Contains(name, "logAndReturn")) {
			if !more {
				break
			}
			continue
		}
		frame := map[string]any{
			"function": name,
			"filename": fr.File,
			"lineno":   fr.Line,
			"inApp":    frameInApp(fr.File),
		}
		for k, v := range frameSourceContext(fr.File, fr.Line) {
			frame[k] = v
		}
		out = append(out, frame)
		if !more {
			break
		}
	}
	return out
}

// logError posts a failed request to the configured logging endpoint as a
// fire-and-forget JSON payload. eventId lets the backend deduplicate retried
// deliveries; delivery failures are ignored so they never mask the original
// error. Go errors carry no stack, so frames are captured at this boundary.
func logError(cfg *ClientConfig, method, path, operationID string, err error) {
	if cfg == nil {
		return
	}
	// Folded over the baked defaults, so a consumer who only flips Enabled still
	// reports to the endpoint that was baked in at generation time.
	merged := mergeLogging(cfg.Logging)
	if !merged.Enabled || merged.Endpoint == "" {
		return
	}
	logging := &merged

	eventID, _ := generateIdempotencyKey()
	errorObj := map[string]any{"name": errorName(err), "message": err.Error()}
	// Go errors carry no stack, so capture the call stack at this boundary — with
	// original-source context per frame — to show where in your code the call
	// failed (best-effort: the source must be readable at runtime).
	if frames := buildFrames(); len(frames) > 0 {
		errorObj["frames"] = frames
	}
	payload := map[string]any{
		"eventId":     eventID,
		"timestamp":   time.Now().UTC().Format(time.RFC3339Nano),
		"level":       "error",
		"operationId": operationID,
		"method":      method,
		"path":        path,
		"error":       errorObj,
	}
	if httpErr, ok := err.(*SdkHttpError); ok {
		payload["statusCode"] = httpErr.StatusCode
	}
	if requestID := requestIDOf(err); requestID != "" {
		payload["requestId"] = requestID
	}
	if logging.Environment != "" {
		payload["environment"] = logging.Environment
	}
	if logging.Release != "" {
		payload["release"] = logging.Release
	}
	if logging.User != nil {
		payload["user"] = logging.User
	}
	if logging.Tags != nil {
		payload["tags"] = logging.Tags
	}

	filterPii := logging.FilterPII == nil || *logging.FilterPII
	body, marshalErr := json.Marshal(sanitizeTelemetry(payload, filterPii))
	if marshalErr != nil {
		return
	}
	endpoint := logging.Endpoint
	apiKey := logging.APIKey
	go func() {
		req, reqErr := http.NewRequest(http.MethodPost, endpoint, bytes.NewReader(body))
		if reqErr != nil {
			return
		}
		req.Header.Set("Content-Type", "application/json")
		if apiKey != "" {
			req.Header.Set("Authorization", "Bearer "+apiKey)
		}
		resp, doErr := httpClient.Do(req)
		if doErr != nil {
			return
		}
		resp.Body.Close()
	}()
}

// composeMiddleware wraps `stack` around `terminal` so the first middleware
// is outermost. When `stack` is empty, `terminal` is returned directly.
func composeMiddleware(stack []Middleware, terminal SdkNext) SdkNext {
	if len(stack) == 0 {
		return terminal
	}
	next := terminal
	for i := len(stack) - 1; i >= 0; i-- {
		mw := stack[i]
		current := next
		next = func(ctx context.Context, req *SdkRequest) (*SdkRawResponse, error) {
			return mw(ctx, req, current)
		}
	}
	return next
}

// coreTransport is the innermost handler — performs the actual HTTP call and
// assembles an SdkRawResponse. Non-2xx responses are returned as-is so
// middleware can inspect them; only network-level errors propagate as errors.
func coreTransport(timeout time.Duration) SdkNext {
	return func(parent context.Context, req *SdkRequest) (*SdkRawResponse, error) {
		ctx, cancel := context.WithTimeout(parent, timeout)
		defer cancel()

		var bodyReader io.Reader
		if req.Body != nil {
			bodyReader = bytes.NewReader(req.Body)
		}
		httpReq, err := http.NewRequestWithContext(ctx, req.Method, req.URL, bodyReader)
		if err != nil {
			return nil, err
		}
		for k, v := range req.Headers {
			httpReq.Header.Set(k, v)
		}

		started := time.Now()
		resp, err := httpClient.Do(httpReq)
		if err != nil {
			return nil, err
		}
		defer resp.Body.Close()
		body, err := io.ReadAll(resp.Body)
		if err != nil {
			return nil, fmt.Errorf("read response: %w", err)
		}
		headers := flattenHeaders(resp.Header)
		return &SdkRawResponse{
			StatusCode: resp.StatusCode,
			Headers:    headers,
			Body:       body,
			RequestID:  findRequestID(headers),
			Latency:    time.Since(started),
			Attempt:    req.Attempt,
		}, nil
	}
}

func mergeIdempotency(override *IdempotencyConfig) IdempotencyConfig {
	r := defaultIdempotency
	if override == nil {
		return r
	}
	r.Enabled = override.Enabled
	if override.HeaderName != "" {
		r.HeaderName = override.HeaderName
	}
	if len(override.Methods) > 0 {
		r.Methods = override.Methods
	}
	return r
}

// mergeLogging folds a caller override over the baked defaults, so a consumer who
// only sets Enabled still gets the reporting endpoint that was baked in at
// generation time.
func mergeLogging(override *LoggingConfig) LoggingConfig {
	l := defaultLogging
	if override == nil {
		return l
	}
	l.Enabled = override.Enabled
	if override.Endpoint != "" {
		l.Endpoint = override.Endpoint
	}
	if override.APIKey != "" {
		l.APIKey = override.APIKey
	}
	if override.Environment != "" {
		l.Environment = override.Environment
	}
	if override.Release != "" {
		l.Release = override.Release
	}
	if override.User != nil {
		l.User = override.User
	}
	if override.Tags != nil {
		l.Tags = override.Tags
	}
	if override.FilterPII != nil {
		l.FilterPII = override.FilterPII
	}
	return l
}

func generateIdempotencyKey() (string, error) {
	// UUID v4 layout — 16 random bytes with version + variant nibbles set.
	var b [16]byte
	if _, err := rand.Read(b[:]); err != nil {
		return "", fmt.Errorf("generate idempotency key: %w", err)
	}
	b[6] = (b[6] & 0x0f) | 0x40
	b[8] = (b[8] & 0x3f) | 0x80
	hexStr := hex.EncodeToString(b[:])
	return hexStr[0:8] + "-" + hexStr[8:12] + "-" + hexStr[12:16] + "-" + hexStr[16:20] + "-" + hexStr[20:32], nil
}

func containsString(s []string, v string) bool {
	for _, x := range s {
		if x == v {
			return true
		}
	}
	return false
}

// NullableValue represents a JSON value that may explicitly be null. An outer
// *NullableValue in generated request/model fields distinguishes omission
// (nil pointer) from an explicit null (non-nil wrapper whose Value is nil).
type NullableValue[T any] struct {
	Value *T
}

// ValueOf wraps a concrete nullable value.
func ValueOf[T any](value T) NullableValue[T] {
	return NullableValue[T]{Value: &value}
}

// NullValue constructs an explicit JSON null.
func NullValue[T any]() NullableValue[T] {
	return NullableValue[T]{}
}

func (value NullableValue[T]) MarshalJSON() ([]byte, error) {
	if value.Value == nil {
		return []byte("null"), nil
	}
	return json.Marshal(value.Value)
}

func (value *NullableValue[T]) UnmarshalJSON(data []byte) error {
	if bytes.Equal(bytes.TrimSpace(data), []byte("null")) {
		value.Value = nil
		return nil
	}
	var decoded T
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	value.Value = &decoded
	return nil
}

// encodeBody serializes the request body and returns the effective content type
// — usually the input, but for multipart/form-data the returned type carries the
// generated boundary, so callers must use the second return value as the header.
func isJSONMediaType(contentType string) bool {
	mediaType := strings.ToLower(strings.TrimSpace(strings.SplitN(contentType, ";", 2)[0]))
	return mediaType == "application/json" || strings.HasSuffix(mediaType, "+json")
}

func encodeBody(body any, contentType string) ([]byte, string, error) {
	if body == nil {
		return nil, contentType, nil
	}
	if strings.HasPrefix(contentType, "multipart/form-data") {
		fields, ok := body.(map[string]any)
		if !ok {
			return nil, "", fmt.Errorf("multipart body must be a map, got %T", body)
		}
		var buf bytes.Buffer
		w := multipart.NewWriter(&buf)
		for key, value := range fields {
			if err := writeMultipartValue(w, key, value); err != nil {
				return nil, "", err
			}
		}
		if err := w.Close(); err != nil {
			return nil, "", fmt.Errorf("close multipart: %w", err)
		}
		return buf.Bytes(), w.FormDataContentType(), nil
	}
	if isJSONMediaType(contentType) {
		return encodeJSONBody(body, contentType)
	}
	if contentType == "application/x-www-form-urlencoded" {
		fields, ok := body.(map[string]any)
		if !ok {
			return nil, "", fmt.Errorf("form body must be a map, got %T", body)
		}
		values := url.Values{}
		for key, value := range fields {
			if isNilValue(value) {
				continue
			}
			switch typed := value.(type) {
			case []string:
				for _, item := range typed {
					values.Add(key, item)
				}
			case []any:
				for _, item := range typed {
					if !isNilValue(item) {
						values.Add(key, fmt.Sprint(item))
					}
				}
			default:
				values.Set(key, fmt.Sprint(value))
			}
		}
		return []byte(values.Encode()), contentType, nil
	}
	switch v := body.(type) {
	case []byte:
		return v, contentType, nil
	case string:
		return []byte(v), contentType, nil
	case io.Reader:
		buf, err := io.ReadAll(v)
		if err != nil {
			return nil, "", fmt.Errorf("read body: %w", err)
		}
		return buf, contentType, nil
	default:
		// A structured body under a media type with no encoder of its own (XML,
		// a vendor type) is written as JSON, as the response side reads it.
		return encodeJSONBody(body, contentType)
	}
}

func encodeJSONBody(body any, contentType string) ([]byte, string, error) {
	if fields, ok := body.(map[string]any); ok {
		present := make(map[string]any, len(fields))
		for key, value := range fields {
			if !isNilValue(value) {
				present[key] = value
			}
		}
		body = present
	}
	encoded, err := json.Marshal(body)
	if err != nil {
		return nil, "", fmt.Errorf("encode body: %w", err)
	}
	return encoded, contentType, nil
}

func writeMultipartValue(w *multipart.Writer, key string, value any) error {
	if isNilValue(value) {
		return nil
	}
	if file, ok := value.(UploadFile); ok {
		return writeMultipartPart(w, key, file.Filename, file.ContentType, file.Data)
	}
	if file, ok := value.(*UploadFile); ok {
		return writeMultipartPart(w, key, file.Filename, file.ContentType, file.Data)
	}
	if structured, ok := value.(multipartJSON); ok {
		encoded, err := json.Marshal(structured.Value)
		if err != nil {
			return fmt.Errorf("encode multipart field %q: %w", key, err)
		}
		return writeMultipartPart(w, key, "", structured.ContentType, encoded)
	}
	if bytesValue, ok := value.([]byte); ok {
		return writeMultipartPart(w, key, key, "application/octet-stream", bytesValue)
	}
	rv := reflect.ValueOf(value)
	if rv.Kind() == reflect.Pointer {
		return writeMultipartValue(w, key, rv.Elem().Interface())
	}
	if rv.Kind() == reflect.Slice || rv.Kind() == reflect.Array {
		for i := 0; i < rv.Len(); i++ {
			if err := writeMultipartValue(w, key, rv.Index(i).Interface()); err != nil {
				return err
			}
		}
		return nil
	}
	return writeMultipartPart(w, key, "", "", []byte(scalarString(value)))
}

func writeMultipartPart(w *multipart.Writer, name, filename, contentType string, data []byte) error {
	header := textproto.MIMEHeader{}
	disposition := fmt.Sprintf(`form-data; name=%q`, name)
	if filename != "" {
		disposition += fmt.Sprintf(`; filename=%q`, filename)
	}
	header.Set("Content-Disposition", disposition)
	if contentType != "" {
		header.Set("Content-Type", contentType)
	}
	part, err := w.CreatePart(header)
	if err != nil {
		return fmt.Errorf("create multipart part %q: %w", name, err)
	}
	if _, err := part.Write(data); err != nil {
		return fmt.Errorf("write multipart part %q: %w", name, err)
	}
	return nil
}

func isNilValue(value any) bool {
	if value == nil {
		return true
	}
	rv := reflect.ValueOf(value)
	switch rv.Kind() {
	case reflect.Chan, reflect.Func, reflect.Interface, reflect.Map, reflect.Pointer, reflect.Slice:
		return rv.IsNil()
	default:
		return false
	}
}

func scalarString(value any) string {
	if isNilValue(value) {
		return "null"
	}
	rv := reflect.ValueOf(value)
	if rv.Kind() == reflect.Pointer {
		return scalarString(rv.Elem().Interface())
	}
	if t, ok := value.(time.Time); ok {
		return t.UTC().Format(time.RFC3339)
	}
	encoded, err := json.Marshal(value)
	if err != nil {
		return fmt.Sprint(value)
	}
	if len(encoded) >= 2 && encoded[0] == '"' && encoded[len(encoded)-1] == '"' {
		var decoded string
		if json.Unmarshal(encoded, &decoded) == nil {
			return decoded
		}
	}
	return string(encoded)
}

func buildHeaders(ctx context.Context, cfg *ClientConfig, contentType string, hasBody bool, query map[string]any, operationID string) (map[string]string, error) {
	headers := map[string]string{}
	if cfg.Auth != nil {
		for k, v := range cfg.Auth.Headers {
			headers[k] = v
		}
	}
	if err := applyAuth(ctx, cfg, headers, query, operationID); err != nil {
		return nil, err
	}
	if hasBody {
		headers["Content-Type"] = contentType
	}
	return headers, nil
}

func mergeRetry(override *RetryConfig) RetryConfig {
	r := defaultRetry
	if override == nil {
		return r
	}
	if override.MaxAttempts > 0 {
		r.MaxAttempts = override.MaxAttempts
	}
	if len(override.RetryOn) > 0 {
		r.RetryOn = override.RetryOn
	}
	if override.Backoff > 0 {
		r.Backoff = override.Backoff
	}
	if override.MaxBackoff > 0 {
		r.MaxBackoff = override.MaxBackoff
	}
	return r
}

func shouldRetryStatus(method string, status int, retryOn []int) bool {
	allowed := false
	for _, code := range retryOn {
		if code == status {
			allowed = true
			break
		}
	}
	if !allowed {
		return false
	}
	if _, ok := idempotentMethods[method]; ok {
		return true
	}
	_, ok := alwaysRetryableStatuses[status]
	return ok
}

func sleepBackoff(ctx context.Context, retry RetryConfig, attempt int, retryAfter string) {
	if retryAfter != "" {
		if seconds, err := strconv.Atoi(strings.TrimSpace(retryAfter)); err == nil && seconds > 0 {
			d := time.Duration(seconds) * time.Second
			if d > retry.MaxBackoff {
				d = retry.MaxBackoff
			}
			waitOrCancel(ctx, d)
			return
		}
		if t, err := http.ParseTime(retryAfter); err == nil {
			d := time.Until(t)
			if d < 0 {
				d = 0
			}
			if d > retry.MaxBackoff {
				d = retry.MaxBackoff
			}
			waitOrCancel(ctx, d)
			return
		}
	}
	exp := retry.Backoff * (1 << (attempt - 1))
	jitter := time.Duration(mrand.Int63n(int64(retry.Backoff)))
	d := exp + jitter
	if d > retry.MaxBackoff {
		d = retry.MaxBackoff
	}
	waitOrCancel(ctx, d)
}

func waitOrCancel(ctx context.Context, d time.Duration) {
	if d <= 0 {
		return
	}
	timer := time.NewTimer(d)
	defer timer.Stop()
	select {
	case <-ctx.Done():
	case <-timer.C:
	}
}

// The query encoding every SDK in the family shares: RFC 3986 unreserved plus
// the sub-delimiters a URI component may carry literally. url.QueryEscape would
// percent-encode those sub-delimiters and write a space as `+`, which is a
// literal plus in a URI query and only means a space to a parser reading the
// component as an HTML form body.
func encodeQueryComponent(value string) string {
	var out strings.Builder
	for _, b := range []byte(value) {
		switch {
		case b >= 'A' && b <= 'Z', b >= 'a' && b <= 'z', b >= '0' && b <= '9',
			b == '-', b == '_', b == '.', b == '~', b == '!', b == '*', b == '\'', b == '(', b == ')':
			out.WriteByte(b)
		default:
			fmt.Fprintf(&out, "%%%02X", b)
		}
	}
	return out.String()
}

func encodeQueryValues(values url.Values) string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	pairs := make([]string, 0, len(values))
	for _, key := range keys {
		name := encodeQueryComponent(key)
		for _, value := range values[key] {
			pairs = append(pairs, name+"="+encodeQueryComponent(value))
		}
	}
	return strings.Join(pairs, "&")
}

func appendQueryString(baseURL string, params map[string]any) string {
	values := url.Values{}
	for k, v := range params {
		appendQueryValue(values, k, v)
	}
	encoded := encodeQueryValues(values)
	if encoded == "" {
		return baseURL
	}
	sep := "?"
	if strings.Contains(baseURL, "?") {
		sep = "&"
	}
	return baseURL + sep + encoded
}

func appendQueryValue(values url.Values, key string, v any) {
	if queryValue, ok := v.(QueryValue); ok {
		appendStyledQueryValue(values, key, queryValue)
		return
	}
	if v == nil {
		return
	}
	rv := reflect.ValueOf(v)
	if rv.Kind() == reflect.Pointer {
		if rv.IsNil() {
			return
		}
		v = rv.Elem().Interface()
		rv = reflect.ValueOf(v)
	}
	switch rv.Kind() {
	case reflect.Slice, reflect.Array:
		for i := 0; i < rv.Len(); i++ {
			appendQueryValue(values, key, rv.Index(i).Interface())
		}
		return
	case reflect.String:
		values.Add(key, rv.String())
		return
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		values.Add(key, strconv.FormatInt(rv.Int(), 10))
		return
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		values.Add(key, strconv.FormatUint(rv.Uint(), 10))
		return
	case reflect.Float32, reflect.Float64:
		values.Add(key, strconv.FormatFloat(rv.Float(), 'f', -1, 64))
		return
	case reflect.Bool:
		values.Add(key, strconv.FormatBool(rv.Bool()))
		return
	}
	if t, ok := v.(time.Time); ok {
		values.Add(key, t.UTC().Format(time.RFC3339))
		return
	}
	encoded, err := json.Marshal(v)
	if err != nil {
		return
	}
	values.Add(key, strings.Trim(string(encoded), `"`))
}
