// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import (
	"context"
)

// ClientAuthConfig holds explicit request headers and optional credentials.
type ClientAuthConfig struct {
	ApiKeyAuth string
	Headers    map[string]string
}

// SdkAuthError reports that the selected authentication capability cannot
// satisfy an operation's declared security requirement.
type SdkAuthError struct {
	sdkErrorBase
	OperationID string
	Preference  string
	Message     string
}

func (e *SdkAuthError) Error() string { return e.Message }

var operationSecurity = map[string][][]string{
	"GetBadge":              [][]string{},
	"GetWakatimeLeaders":    [][]string{[]string{"ApiKeyAuth"}},
	"GetWakatimeUser":       [][]string{[]string{"ApiKeyAuth"}},
	"GetAllTime":            [][]string{[]string{"ApiKeyAuth"}},
	"GetHeartbeats":         [][]string{[]string{"ApiKeyAuth"}},
	"PostHeartbeat3":        [][]string{[]string{"ApiKeyAuth"}},
	"PostHeartbeat7":        [][]string{[]string{"ApiKeyAuth"}},
	"GetWakatimeProjects":   [][]string{[]string{"ApiKeyAuth"}},
	"GetWakatimeProject":    [][]string{[]string{"ApiKeyAuth"}},
	"GetWakatimesTats":      [][]string{[]string{"ApiKeyAuth"}},
	"GetWakatimeSummaries":  [][]string{[]string{"ApiKeyAuth"}},
	"GetWakatimeUseragents": [][]string{[]string{"ApiKeyAuth"}},
	"GetHealth":             [][]string{},
	"PostHeartbeat":         [][]string{[]string{"ApiKeyAuth"}},
	"PostHeartbeat5":        [][]string{[]string{"ApiKeyAuth"}},
	"PostDiagnostics":       [][]string{},
	"GetSummary":            [][]string{[]string{"ApiKeyAuth"}},
	"PostHeartbeat4":        [][]string{[]string{"ApiKeyAuth"}},
	"PostHeartbeat8":        [][]string{[]string{"ApiKeyAuth"}},
	"Statusbar":             [][]string{[]string{"ApiKeyAuth"}},
	"PostHeartbeat2":        [][]string{[]string{"ApiKeyAuth"}},
	"PostHeartbeat6":        [][]string{[]string{"ApiKeyAuth"}},
}

const defaultBaseURL = ""

// applyAuthScheme attaches one named scheme. Schema-wide credential branches
// skip absent optional values; selection-owned providers return typed failures
// when the operation cannot obtain the credential it requires.
func applyAuthScheme(ctx context.Context, cfg *ClientConfig, headers map[string]string, query map[string]any, name string) error {
	switch name {
	case "ApiKeyAuth":
		if cfg == nil || cfg.Auth == nil {
			return nil
		}
		if cfg.Auth.ApiKeyAuth != "" {
			headers["Authorization"] = cfg.Auth.ApiKeyAuth
		}
	}
	return nil
}

// isApiKeyScheme reports whether a declared security scheme name is one
// the apiKey selection can satisfy.
func isApiKeyScheme(name string) bool {
	switch name {
	case "ApiKeyAuth":
		return true
	default:
		return false
	}
}

// hasApiKeyCredential reports whether the configuration carries the
// credential a declared scheme name needs.
func hasApiKeyCredential(cfg *ClientConfig, name string) bool {
	if cfg == nil || cfg.Auth == nil {
		return false
	}
	switch name {
	case "ApiKeyAuth":
		return cfg.Auth.ApiKeyAuth != ""
	default:
		return false
	}
}

// selectApiKeyRequirement returns the security alternative to apply: the
// first one whose every member is configured, and otherwise the first one the
// selection can satisfy at all.
func selectApiKeyRequirement(requirements [][]string, cfg *ClientConfig) ([]string, bool) {
	var fallback []string
	found := false
	for _, alternative := range requirements {
		compatible := true
		configured := true
		for _, name := range alternative {
			if !isApiKeyScheme(name) {
				compatible = false
				break
			}
			if !hasApiKeyCredential(cfg, name) {
				configured = false
			}
		}
		if !compatible {
			continue
		}
		if configured {
			return alternative, true
		}
		if !found {
			fallback = alternative
			found = true
		}
	}
	return fallback, found
}

// applyAuth attaches credentials to the outgoing request. Selection-aware
// modes validate the current operation before applying any scheme.
func applyAuth(ctx context.Context, cfg *ClientConfig, headers map[string]string, query map[string]any, operationID string) error {
	if security, known := operationSecurity[operationID]; known {
		if len(security) == 0 {
			return nil
		}
		selected, compatible := selectApiKeyRequirement(security, cfg)
		if !compatible {
			return &SdkAuthError{
				OperationID: operationID,
				Preference:  "apiKey",
				Message:     "auth apiKey cannot satisfy the security requirement for operation " + operationID,
			}
		}
		for _, name := range selected {
			if err := applyAuthScheme(ctx, cfg, headers, query, name); err != nil {
				return err
			}
		}
		return nil
	}

	if cfg == nil || cfg.Auth == nil {
		return nil
	}

	if err := applyAuthScheme(ctx, cfg, headers, query, "ApiKeyAuth"); err != nil {
		return err
	}
	return nil

}
