// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import (
	"bytes"
	"context"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"mime/multipart"
	"net/http"
	"net/textproto"
	"net/url"
	"os"
	"reflect"
	"runtime"
	"strings"
	"time"
)

func exchange(ctx context.Context, cfg *ClientConfig, method, path string, opts *RequestOpts) (exchangeMeta, []byte, error) {
	if opts == nil {
		opts = &RequestOpts{}
	}

	method = strings.ToUpper(method)
	// Absolute URLs (used by url-style pagination follow links) bypass BaseURL.
	var baseURL string
	if strings.HasPrefix(path, "http://") || strings.HasPrefix(path, "https://") {
		baseURL = path
	} else {
		baseURL = cfg.BaseURL + path
	}

	contentType := opts.ContentType
	if contentType == "" {
		contentType = "application/json"
	}

	hasBody := opts.Body != nil
	bodyBytes, contentType, err := encodeBody(opts.Body, contentType)
	if err != nil {
		return exchangeMeta{}, nil, err
	}

	call := resolveRequestOptions(opts.Options)
	retry := mergeRetry(cfg.Retry)
	if call.retry != nil {
		retry = mergeRetry(call.retry)
	}
	idem := mergeIdempotency(cfg.Idempotency)
	timeout := cfg.Timeout
	if call.timeout > 0 {
		timeout = call.timeout
	}
	if timeout <= 0 {
		timeout = defaultTimeout
	}

	// One idempotency key per logical request — reused across retries so the
	// server can deduplicate.
	idempotencyKey := ""
	if call.idempotencyKey != nil {
		idempotencyKey = *call.idempotencyKey
	} else if idem.Enabled && containsString(idem.Methods, method) {
		idempotencyKey, err = generateIdempotencyKey()
		if err != nil {
			return exchangeMeta{}, nil, &SdkNetworkError{Cause: err}
		}
	}

	dispatch := composeMiddleware(cfg.Middleware, coreTransport(timeout))

	for attempt := 1; attempt <= retry.MaxAttempts; attempt++ {
		// Auth may mutate per-attempt (e.g. OAuth refresh). Re-apply on every retry.
		query := map[string]any{}
		for k, v := range opts.Query {
			query[k] = v
		}
		headers, err := buildHeaders(ctx, cfg, contentType, hasBody, query, opts.Headers, opts.OperationID)
		if err != nil {
			return exchangeMeta{}, nil, err
		}
		for k, v := range call.headers {
			headers[k] = v
		}
		if idempotencyKey != "" {
			headers[idem.HeaderName] = idempotencyKey
		}
		rawURL := baseURL
		if len(query) > 0 {
			rawURL = appendQueryString(rawURL, query)
		}

		req := &SdkRequest{
			Method:      method,
			URL:         rawURL,
			Headers:     headers,
			Body:        bodyBytes,
			ContentType: contentType,
			OperationID: opts.OperationID,
			Attempt:     attempt,
			Meta:        map[string]any{},
		}

		resp, err := dispatch(ctx, req)
		if err != nil {
			if errors.Is(err, context.DeadlineExceeded) {
				if attempt < retry.MaxAttempts {
					sleepBackoff(ctx, retry, attempt, "")
					continue
				}
				return exchangeMeta{}, nil, logAndReturn(cfg, method, path, opts.OperationID, &SdkTimeoutError{Elapsed: timeout})
			}
			if attempt < retry.MaxAttempts {
				sleepBackoff(ctx, retry, attempt, "")
				continue
			}
			return exchangeMeta{}, nil, logAndReturn(cfg, method, path, opts.OperationID, &SdkNetworkError{Cause: err})
		}

		meta := exchangeMeta{
			statusCode: resp.StatusCode,
			headers:    resp.Headers,
			requestID:  resp.RequestID,
			latency:    resp.Latency,
			attempt:    resp.Attempt,
		}

		if resp.StatusCode >= 200 && resp.StatusCode < 300 {
			if cfg.OnResponse != nil {
				cfg.OnResponse(meta.statusCode, meta.headers, meta.requestID, meta.latency, meta.attempt)
			}
			return meta, resp.Body, nil
		}

		if attempt < retry.MaxAttempts && shouldRetryStatus(method, resp.StatusCode, retry.RetryOn) {
			sleepBackoff(ctx, retry, attempt, resp.Headers["retry-after"])
			continue
		}

		return exchangeMeta{}, nil, logAndReturn(cfg, method, path, opts.OperationID, &SdkHttpError{
			StatusCode: resp.StatusCode,
			StatusText: http.StatusText(resp.StatusCode),
			Body:       resp.Body,
			Headers:    resp.Headers,
			RequestID:  resp.RequestID,
		})
	}

	return exchangeMeta{}, nil, &SdkNetworkError{Cause: fmt.Errorf("request '%s' produced no attempts", opts.OperationID)}
}

// logAndReturn fires the error logger (when configured) and returns the error
// unchanged, so terminal failures can be wrapped inline at each return site.
func logAndReturn(cfg *ClientConfig, method, path, operationID string, err error) error {
	logError(cfg, method, path, operationID, err)
	return err
}

// errorName maps a typed SDK error to the name the monitoring backend groups on.
func errorName(err error) string {
	switch err.(type) {
	case *SdkHttpError:
		return "SdkHttpError"
	case *SdkValidationError:
		return "SdkValidationError"
	case *SdkNetworkError:
		return "SdkNetworkError"
	case *SdkTimeoutError:
		return "SdkTimeoutError"
	default:
		return "error"
	}
}

// requestIDOf returns the request id carried by the typed SDK errors, if any.
func requestIDOf(err error) string {
	switch e := err.(type) {
	case *SdkHttpError:
		return e.RequestID
	case *SdkNetworkError:
		return e.RequestID
	case *SdkTimeoutError:
		return e.RequestID
	default:
		return ""
	}
}

const sourceContextLines = 5

// frameInApp reports whether a source file belongs to the application rather
// than the Go runtime or an installed module.
func frameInApp(file string) bool {
	if file == "" {
		return false
	}
	if strings.Contains(file, "/pkg/mod/") {
		return false
	}
	if root := runtime.GOROOT(); root != "" && strings.HasPrefix(file, root) {
		return false
	}
	return true
}

// frameSourceContext reads a few lines around a frame so the dashboard can show
// the original code (best-effort: the source must be readable at runtime).
func frameSourceContext(file string, line int) map[string]any {
	if file == "" || line < 1 {
		return nil
	}
	data, err := os.ReadFile(file)
	if err != nil {
		return nil
	}
	lines := strings.Split(string(data), "\n")
	if line > len(lines) {
		return nil
	}
	idx := line - 1
	ctx := map[string]any{"contextLine": lines[idx]}
	start := idx - sourceContextLines
	if start < 0 {
		start = 0
	}
	if pre := lines[start:idx]; len(pre) > 0 {
		ctx["preContext"] = pre
	}
	end := idx + 1 + sourceContextLines
	if end > len(lines) {
		end = len(lines)
	}
	if post := lines[idx+1 : end]; len(post) > 0 {
		ctx["postContext"] = post
	}
	return ctx
}

// shortFuncName trims the package path from a fully-qualified function name.
func shortFuncName(fn string) string {
	if i := strings.LastIndex(fn, "/"); i >= 0 {
		fn = fn[i+1:]
	}
	return fn
}

// buildFrames captures the call stack at the failing SDK boundary (innermost
// first), with original-source context per frame, dropping the SDK's own
// logging plumbing from the top.
func buildFrames() []map[string]any {
	pcs := make([]uintptr, 64)
	n := runtime.Callers(2, pcs) // skip runtime.Callers + buildFrames
	if n == 0 {
		return nil
	}
	callerFrames := runtime.CallersFrames(pcs[:n])
	out := make([]map[string]any, 0, n)
	for {
		fr, more := callerFrames.Next()
		name := shortFuncName(fr.Function)
		if len(out) == 0 && (strings.Contains(name, "logError") || strings.Contains(name, "logAndReturn")) {
			if !more {
				break
			}
			continue
		}
		frame := map[string]any{
			"function": name,
			"filename": fr.File,
			"lineno":   fr.Line,
			"inApp":    frameInApp(fr.File),
		}
		for k, v := range frameSourceContext(fr.File, fr.Line) {
			frame[k] = v
		}
		out = append(out, frame)
		if !more {
			break
		}
	}
	return out
}

// logError posts a failed request to the configured logging endpoint as a
// fire-and-forget JSON payload. eventId lets the backend deduplicate retried
// deliveries; delivery failures are ignored so they never mask the original
// error. Go errors carry no stack, so frames are captured at this boundary.
func logError(cfg *ClientConfig, method, path, operationID string, err error) {
	if cfg == nil {
		return
	}
	// Folded over the baked defaults, so a consumer who only flips Enabled still
	// reports to the endpoint that was baked in at generation time.
	merged := mergeLogging(cfg.Logging)
	if !merged.Enabled || merged.Endpoint == "" {
		return
	}
	logging := &merged

	eventID, _ := generateIdempotencyKey()
	errorObj := map[string]any{"name": errorName(err), "message": err.Error()}
	// Go errors carry no stack, so capture the call stack at this boundary — with
	// original-source context per frame — to show where in your code the call
	// failed (best-effort: the source must be readable at runtime).
	if frames := buildFrames(); len(frames) > 0 {
		errorObj["frames"] = frames
	}
	payload := map[string]any{
		"eventId":     eventID,
		"timestamp":   time.Now().UTC().Format(time.RFC3339Nano),
		"level":       "error",
		"operationId": operationID,
		"method":      method,
		"path":        path,
		"error":       errorObj,
	}
	if httpErr, ok := err.(*SdkHttpError); ok {
		payload["statusCode"] = httpErr.StatusCode
	}
	if requestID := requestIDOf(err); requestID != "" {
		payload["requestId"] = requestID
	}
	if logging.Environment != "" {
		payload["environment"] = logging.Environment
	}
	if logging.Release != "" {
		payload["release"] = logging.Release
	}
	if logging.User != nil {
		payload["user"] = logging.User
	}
	if logging.Tags != nil {
		payload["tags"] = logging.Tags
	}

	filterPii := logging.FilterPII == nil || *logging.FilterPII
	body, marshalErr := json.Marshal(sanitizeTelemetry(payload, filterPii))
	if marshalErr != nil {
		return
	}
	endpoint := logging.Endpoint
	apiKey := logging.APIKey
	go func() {
		req, reqErr := http.NewRequest(http.MethodPost, endpoint, bytes.NewReader(body))
		if reqErr != nil {
			return
		}
		req.Header.Set("Content-Type", "application/json")
		if apiKey != "" {
			req.Header.Set("Authorization", "Bearer "+apiKey)
		}
		resp, doErr := httpClient.Do(req)
		if doErr != nil {
			return
		}
		resp.Body.Close()
	}()
}

// composeMiddleware wraps `stack` around `terminal` so the first middleware
// is outermost. When `stack` is empty, `terminal` is returned directly.
func composeMiddleware(stack []Middleware, terminal SdkNext) SdkNext {
	if len(stack) == 0 {
		return terminal
	}
	next := terminal
	for i := len(stack) - 1; i >= 0; i-- {
		mw := stack[i]
		current := next
		next = func(ctx context.Context, req *SdkRequest) (*SdkRawResponse, error) {
			return mw(ctx, req, current)
		}
	}
	return next
}

// coreTransport is the innermost handler — performs the actual HTTP call and
// assembles an SdkRawResponse. Non-2xx responses are returned as-is so
// middleware can inspect them; only network-level errors propagate as errors.
func coreTransport(timeout time.Duration) SdkNext {
	return func(parent context.Context, req *SdkRequest) (*SdkRawResponse, error) {
		ctx, cancel := context.WithTimeout(parent, timeout)
		defer cancel()

		var bodyReader io.Reader
		if req.Body != nil {
			bodyReader = bytes.NewReader(req.Body)
		}
		httpReq, err := http.NewRequestWithContext(ctx, req.Method, req.URL, bodyReader)
		if err != nil {
			return nil, err
		}
		for k, v := range req.Headers {
			httpReq.Header.Set(k, v)
		}

		started := time.Now()
		resp, err := httpClient.Do(httpReq)
		if err != nil {
			return nil, err
		}
		defer resp.Body.Close()
		body, err := io.ReadAll(resp.Body)
		if err != nil {
			return nil, fmt.Errorf("read response: %w", err)
		}
		headers := flattenHeaders(resp.Header)
		return &SdkRawResponse{
			StatusCode: resp.StatusCode,
			Headers:    headers,
			Body:       body,
			RequestID:  findRequestID(headers),
			Latency:    time.Since(started),
			Attempt:    req.Attempt,
		}, nil
	}
}

func mergeIdempotency(override *IdempotencyConfig) IdempotencyConfig {
	r := defaultIdempotency
	if override == nil {
		return r
	}
	r.Enabled = override.Enabled
	if override.HeaderName != "" {
		r.HeaderName = override.HeaderName
	}
	if len(override.Methods) > 0 {
		r.Methods = override.Methods
	}
	return r
}

// mergeLogging folds a caller override over the baked defaults, so a consumer who
// only sets Enabled still gets the reporting endpoint that was baked in at
// generation time.
func mergeLogging(override *LoggingConfig) LoggingConfig {
	l := defaultLogging
	if override == nil {
		return l
	}
	l.Enabled = override.Enabled
	if override.Endpoint != "" {
		l.Endpoint = override.Endpoint
	}
	if override.APIKey != "" {
		l.APIKey = override.APIKey
	}
	if override.Environment != "" {
		l.Environment = override.Environment
	}
	if override.Release != "" {
		l.Release = override.Release
	}
	if override.User != nil {
		l.User = override.User
	}
	if override.Tags != nil {
		l.Tags = override.Tags
	}
	if override.FilterPII != nil {
		l.FilterPII = override.FilterPII
	}
	return l
}

func generateIdempotencyKey() (string, error) {
	// UUID v4 layout — 16 random bytes with version + variant nibbles set.
	var b [16]byte
	if _, err := rand.Read(b[:]); err != nil {
		return "", fmt.Errorf("generate idempotency key: %w", err)
	}
	b[6] = (b[6] & 0x0f) | 0x40
	b[8] = (b[8] & 0x3f) | 0x80
	hexStr := hex.EncodeToString(b[:])
	return hexStr[0:8] + "-" + hexStr[8:12] + "-" + hexStr[12:16] + "-" + hexStr[16:20] + "-" + hexStr[20:32], nil
}

func containsString(s []string, v string) bool {
	for _, x := range s {
		if x == v {
			return true
		}
	}
	return false
}

// NullableValue represents a JSON value that may explicitly be null. An outer
// *NullableValue in generated request/model fields distinguishes omission
// (nil pointer) from an explicit null (non-nil wrapper whose Value is nil).
type NullableValue[T any] struct {
	Value *T
}

// ValueOf wraps a concrete nullable value.
func ValueOf[T any](value T) NullableValue[T] {
	return NullableValue[T]{Value: &value}
}

// NullValue constructs an explicit JSON null.
func NullValue[T any]() NullableValue[T] {
	return NullableValue[T]{}
}

func (value NullableValue[T]) MarshalJSON() ([]byte, error) {
	if value.Value == nil {
		return []byte("null"), nil
	}
	return json.Marshal(value.Value)
}

func (value *NullableValue[T]) UnmarshalJSON(data []byte) error {
	if bytes.Equal(bytes.TrimSpace(data), []byte("null")) {
		value.Value = nil
		return nil
	}
	var decoded T
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	value.Value = &decoded
	return nil
}

func isJSONMediaType(contentType string) bool {
	mediaType := strings.ToLower(strings.TrimSpace(strings.SplitN(contentType, ";", 2)[0]))
	return mediaType == "application/json" || strings.HasSuffix(mediaType, "+json")
}

// encodeBody serializes the request body and returns the effective content type
// — usually the input, but for multipart/form-data the returned type carries the
// generated boundary, so callers must use the second return value as the header.
func encodeBody(body any, contentType string) ([]byte, string, error) {
	if body == nil {
		return nil, contentType, nil
	}
	switch strings.ToLower(strings.TrimSpace(strings.SplitN(contentType, ";", 2)[0])) {
	case "application/x-ndjson", "application/ndjson", "application/jsonl", "application/json-lines", "application/x-jsonlines":
		return encodeJSONRecords(body, contentType, "")
	case "application/json-seq":
		return encodeJSONRecords(body, contentType, "\x1e")
	}
	if strings.HasPrefix(contentType, "multipart/form-data") {
		fields, ok := body.(map[string]any)
		if !ok {
			return nil, "", fmt.Errorf("multipart body must be a map, got %T", body)
		}
		var buf bytes.Buffer
		w := multipart.NewWriter(&buf)
		for key, value := range fields {
			if err := writeMultipartValue(w, key, value); err != nil {
				return nil, "", err
			}
		}
		if err := w.Close(); err != nil {
			return nil, "", fmt.Errorf("close multipart: %w", err)
		}
		return buf.Bytes(), w.FormDataContentType(), nil
	}
	if isJSONMediaType(contentType) {
		return encodeJSONBody(body, contentType)
	}
	if contentType == "application/x-www-form-urlencoded" {
		fields, ok := body.(map[string]any)
		if !ok {
			return nil, "", fmt.Errorf("form body must be a map, got %T", body)
		}
		values := url.Values{}
		for key, value := range fields {
			if isNilValue(value) {
				continue
			}
			switch typed := value.(type) {
			case []string:
				for _, item := range typed {
					values.Add(key, item)
				}
			case []any:
				for _, item := range typed {
					if !isNilValue(item) {
						values.Add(key, fmt.Sprint(item))
					}
				}
			default:
				values.Set(key, fmt.Sprint(value))
			}
		}
		return []byte(values.Encode()), contentType, nil
	}
	switch v := body.(type) {
	case []byte:
		return v, contentType, nil
	case string:
		return []byte(v), contentType, nil
	case io.Reader:
		buf, err := io.ReadAll(v)
		if err != nil {
			return nil, "", fmt.Errorf("read body: %w", err)
		}
		return buf, contentType, nil
	default:
		// A structured body under a media type with no encoder of its own (XML,
		// a vendor type) is written as JSON, as the response side reads it.
		return encodeJSONBody(body, contentType)
	}
}

// encodeJSONRecords writes one JSON record per line, each after separator; an
// array body is sent as its items.
func encodeJSONRecords(body any, contentType, separator string) ([]byte, string, error) {
	encoded, err := json.Marshal(body)
	if err != nil {
		return nil, "", fmt.Errorf("encode body: %w", err)
	}
	records := []json.RawMessage{encoded}
	if bytes.HasPrefix(encoded, []byte("[")) {
		if err := json.Unmarshal(encoded, &records); err != nil {
			return nil, "", fmt.Errorf("encode body: %w", err)
		}
	}
	var buf bytes.Buffer
	for _, record := range records {
		buf.WriteString(separator)
		buf.Write(record)
		buf.WriteByte('\n')
	}
	return buf.Bytes(), contentType, nil
}

func encodeJSONBody(body any, contentType string) ([]byte, string, error) {
	if fields, ok := body.(map[string]any); ok {
		present := make(map[string]any, len(fields))
		for key, value := range fields {
			if !isNilValue(value) {
				present[key] = value
			}
		}
		body = present
	}
	encoded, err := json.Marshal(body)
	if err != nil {
		return nil, "", fmt.Errorf("encode body: %w", err)
	}
	return encoded, contentType, nil
}

func writeMultipartValue(w *multipart.Writer, key string, value any) error {
	if isNilValue(value) {
		return nil
	}
	if file, ok := value.(UploadFile); ok {
		return writeMultipartPart(w, key, file.Filename, file.ContentType, file.Data)
	}
	if file, ok := value.(*UploadFile); ok {
		return writeMultipartPart(w, key, file.Filename, file.ContentType, file.Data)
	}
	if structured, ok := value.(multipartJSON); ok {
		encoded, err := json.Marshal(structured.Value)
		if err != nil {
			return fmt.Errorf("encode multipart field %q: %w", key, err)
		}
		return writeMultipartPart(w, key, "", structured.ContentType, encoded)
	}
	if bytesValue, ok := value.([]byte); ok {
		return writeMultipartPart(w, key, key, "application/octet-stream", bytesValue)
	}
	rv := reflect.ValueOf(value)
	if rv.Kind() == reflect.Pointer {
		return writeMultipartValue(w, key, rv.Elem().Interface())
	}
	if rv.Kind() == reflect.Slice || rv.Kind() == reflect.Array {
		for i := 0; i < rv.Len(); i++ {
			if err := writeMultipartValue(w, key, rv.Index(i).Interface()); err != nil {
				return err
			}
		}
		return nil
	}
	return writeMultipartPart(w, key, "", "", []byte(scalarString(value)))
}

func writeMultipartPart(w *multipart.Writer, name, filename, contentType string, data []byte) error {
	header := textproto.MIMEHeader{}
	disposition := fmt.Sprintf(`form-data; name=%q`, name)
	if filename != "" {
		disposition += fmt.Sprintf(`; filename=%q`, filename)
	}
	header.Set("Content-Disposition", disposition)
	if contentType != "" {
		header.Set("Content-Type", contentType)
	}
	part, err := w.CreatePart(header)
	if err != nil {
		return fmt.Errorf("create multipart part %q: %w", name, err)
	}
	if _, err := part.Write(data); err != nil {
		return fmt.Errorf("write multipart part %q: %w", name, err)
	}
	return nil
}

func isNilValue(value any) bool {
	if value == nil {
		return true
	}
	rv := reflect.ValueOf(value)
	switch rv.Kind() {
	case reflect.Chan, reflect.Func, reflect.Interface, reflect.Map, reflect.Pointer, reflect.Slice:
		return rv.IsNil()
	default:
		return false
	}
}

func scalarString(value any) string {
	if isNilValue(value) {
		return "null"
	}
	rv := reflect.ValueOf(value)
	if rv.Kind() == reflect.Pointer {
		return scalarString(rv.Elem().Interface())
	}
	if t, ok := value.(time.Time); ok {
		return t.UTC().Format(time.RFC3339)
	}
	encoded, err := json.Marshal(value)
	if err != nil {
		return fmt.Sprint(value)
	}
	if len(encoded) >= 2 && encoded[0] == '"' && encoded[len(encoded)-1] == '"' {
		var decoded string
		if json.Unmarshal(encoded, &decoded) == nil {
			return decoded
		}
	}
	return string(encoded)
}
