// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import (
	"bufio"
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	mrand "math/rand"
	"net/http"
	"net/url"
	"reflect"
	"sort"
	"strconv"
	"strings"
	"time"
	"unicode"
)

func buildHeaders(ctx context.Context, cfg *ClientConfig, contentType string, hasBody bool, query map[string]any, operationHeaders map[string]string, operationID string) (map[string]string, error) {
	headers := map[string]string{}
	if cfg.Auth != nil {
		for k, v := range cfg.Auth.Headers {
			headers[k] = v
		}
	}
	// Before auth, so an apiKey cookie joins the operation's cookies.
	for k, v := range operationHeaders {
		headers[k] = v
	}
	if err := applyAuth(ctx, cfg, headers, query, operationID); err != nil {
		return nil, err
	}
	if hasBody {
		headers["Content-Type"] = contentType
	}
	return headers, nil
}

func mergeRetry(override *RetryConfig) RetryConfig {
	r := defaultRetry
	if override == nil {
		return r
	}
	if override.MaxAttempts > 0 {
		r.MaxAttempts = override.MaxAttempts
	}
	if len(override.RetryOn) > 0 {
		r.RetryOn = override.RetryOn
	}
	if override.Backoff > 0 {
		r.Backoff = override.Backoff
	}
	if override.MaxBackoff > 0 {
		r.MaxBackoff = override.MaxBackoff
	}
	return r
}

func shouldRetryStatus(method string, status int, retryOn []int) bool {
	allowed := false
	for _, code := range retryOn {
		if code == status {
			allowed = true
			break
		}
	}
	if !allowed {
		return false
	}
	if _, ok := idempotentMethods[method]; ok {
		return true
	}
	_, ok := alwaysRetryableStatuses[status]
	return ok
}

func sleepBackoff(ctx context.Context, retry RetryConfig, attempt int, retryAfter string) {
	if retryAfter != "" {
		if seconds, err := strconv.Atoi(strings.TrimSpace(retryAfter)); err == nil && seconds > 0 {
			d := time.Duration(seconds) * time.Second
			if d > retry.MaxBackoff {
				d = retry.MaxBackoff
			}
			waitOrCancel(ctx, d)
			return
		}
		if t, err := http.ParseTime(retryAfter); err == nil {
			d := time.Until(t)
			if d < 0 {
				d = 0
			}
			if d > retry.MaxBackoff {
				d = retry.MaxBackoff
			}
			waitOrCancel(ctx, d)
			return
		}
	}
	exp := retry.Backoff * (1 << (attempt - 1))
	jitter := time.Duration(mrand.Int63n(int64(retry.Backoff)))
	d := exp + jitter
	if d > retry.MaxBackoff {
		d = retry.MaxBackoff
	}
	waitOrCancel(ctx, d)
}

func waitOrCancel(ctx context.Context, d time.Duration) {
	if d <= 0 {
		return
	}
	timer := time.NewTimer(d)
	defer timer.Stop()
	select {
	case <-ctx.Done():
	case <-timer.C:
	}
}

// The query encoding every SDK in the family shares: RFC 3986 unreserved plus
// the sub-delimiters a URI component may carry literally. url.QueryEscape would
// percent-encode those sub-delimiters and write a space as `+`, which is a
// literal plus in a URI query and only means a space to a parser reading the
// component as an HTML form body.
func encodeQueryComponent(value string) string {
	var out strings.Builder
	for _, b := range []byte(value) {
		switch {
		case b >= 'A' && b <= 'Z', b >= 'a' && b <= 'z', b >= '0' && b <= '9',
			b == '-', b == '_', b == '.', b == '~', b == '!', b == '*', b == '\'', b == '(', b == ')':
			out.WriteByte(b)
		default:
			fmt.Fprintf(&out, "%%%02X", b)
		}
	}
	return out.String()
}

func encodeQueryValues(values url.Values) string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	pairs := make([]string, 0, len(values))
	for _, key := range keys {
		name := encodeQueryComponent(key)
		for _, value := range values[key] {
			pairs = append(pairs, name+"="+encodeQueryComponent(value))
		}
	}
	return strings.Join(pairs, "&")
}

func appendQueryString(baseURL string, params map[string]any) string {
	values := url.Values{}
	for k, v := range params {
		appendQueryValue(values, k, v)
	}
	encoded := encodeQueryValues(values)
	if encoded == "" {
		return baseURL
	}
	sep := "?"
	if strings.Contains(baseURL, "?") {
		sep = "&"
	}
	return baseURL + sep + encoded
}

func appendQueryValue(values url.Values, key string, v any) {
	if queryValue, ok := v.(QueryValue); ok {
		appendStyledQueryValue(values, key, queryValue)
		return
	}
	if v == nil {
		return
	}
	rv := reflect.ValueOf(v)
	if rv.Kind() == reflect.Pointer {
		if rv.IsNil() {
			return
		}
		v = rv.Elem().Interface()
		rv = reflect.ValueOf(v)
	}
	switch rv.Kind() {
	case reflect.Slice, reflect.Array:
		for i := 0; i < rv.Len(); i++ {
			appendQueryValue(values, key, rv.Index(i).Interface())
		}
		return
	case reflect.String:
		values.Add(key, rv.String())
		return
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		values.Add(key, strconv.FormatInt(rv.Int(), 10))
		return
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		values.Add(key, strconv.FormatUint(rv.Uint(), 10))
		return
	case reflect.Float32, reflect.Float64:
		values.Add(key, strconv.FormatFloat(rv.Float(), 'f', -1, 64))
		return
	case reflect.Bool:
		values.Add(key, strconv.FormatBool(rv.Bool()))
		return
	}
	if t, ok := v.(time.Time); ok {
		values.Add(key, t.UTC().Format(time.RFC3339))
		return
	}
	encoded, err := json.Marshal(v)
	if err != nil {
		return
	}
	values.Add(key, strings.Trim(string(encoded), `"`))
}

func appendStyledQueryValue(values url.Values, key string, descriptor QueryValue) {
	if isNilValue(descriptor.Value) {
		return
	}
	rv := reflect.ValueOf(descriptor.Value)
	if rv.Kind() == reflect.Pointer {
		descriptor.Value = rv.Elem().Interface()
		rv = reflect.ValueOf(descriptor.Value)
	}
	if rv.Kind() != reflect.Slice && rv.Kind() != reflect.Array {
		values.Add(key, scalarString(descriptor.Value))
		return
	}
	items := make([]string, 0, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		items = append(items, scalarString(rv.Index(i).Interface()))
	}
	if descriptor.Style == "form" && descriptor.Explode {
		for _, item := range items {
			values.Add(key, item)
		}
		return
	}
	delimiter := ","
	if descriptor.Style == "spaceDelimited" {
		delimiter = " "
	} else if descriptor.Style == "pipeDelimited" {
		delimiter = "|"
	}
	values.Add(key, strings.Join(items, delimiter))
}

func flattenHeaders(h http.Header) map[string]string {
	out := make(map[string]string, len(h))
	for k, vs := range h {
		if len(vs) == 0 {
			continue
		}
		out[strings.ToLower(k)] = vs[0]
	}
	return out
}

func findRequestID(headers map[string]string) string {
	for _, name := range requestIDHeaders {
		if v, ok := headers[name]; ok {
			return v
		}
	}
	return ""
}

// SdkStreamEvent is one Server-Sent Event yielded by Stream. Data is the raw
// event payload; consumers can JSON-decode it themselves when applicable.
type SdkStreamEvent struct {
	Event string
	Data  string
	ID    string
	Retry int
}

// Stream opens an SSE connection and emits parsed events on the returned
// channel. Bypasses the retry loop and idempotency layer — streaming
// connections are long-lived; reconnect is the caller's responsibility.
// Cancel via the supplied context; the goroutine closes the channel on exit.
func Stream(ctx context.Context, method, path string, opts *RequestOpts) (<-chan SdkStreamEvent, <-chan error) {
	return StreamCfg(ctx, GetConfig(), method, path, opts)
}

// StreamWithFormat opens a stream using explicit framing and media metadata.
func StreamWithFormat(ctx context.Context, method, path string, opts *RequestOpts, streamFormat, streamMediaType, chunkDomain string) (<-chan SdkStreamEvent, <-chan error) {
	return StreamCfgWithFormat(ctx, GetConfig(), method, path, opts, streamFormat, streamMediaType, chunkDomain)
}

// StreamCfg is the explicit-config form of Stream.
func StreamCfg(ctx context.Context, cfg *ClientConfig, method, path string, opts *RequestOpts) (<-chan SdkStreamEvent, <-chan error) {
	return StreamCfgWithFormat(ctx, cfg, method, path, opts, "sse", "text/event-stream", "text")
}

// StreamCfgWithFormat is the explicit-config, format-aware form of Stream.
func StreamCfgWithFormat(ctx context.Context, cfg *ClientConfig, method, path string, opts *RequestOpts, streamFormat, streamMediaType, chunkDomain string) (<-chan SdkStreamEvent, <-chan error) {
	events := make(chan SdkStreamEvent, 16)
	errs := make(chan error, 1)
	go func() {
		defer close(events)
		defer close(errs)
		if opts == nil {
			opts = &RequestOpts{}
		}
		method = strings.ToUpper(method)
		var rawURL string
		if strings.HasPrefix(path, "http://") || strings.HasPrefix(path, "https://") {
			rawURL = path
		} else {
			rawURL = cfg.BaseURL + path
		}
		contentType := opts.ContentType
		if contentType == "" {
			contentType = "application/json"
		}
		bodyBytes, contentType, err := encodeBody(opts.Body, contentType)
		if err != nil {
			errs <- err
			return
		}
		query := opts.Query
		if query == nil {
			query = map[string]any{}
		}
		headers, err := buildHeaders(ctx, cfg, contentType, opts.Body != nil, query, opts.Headers, opts.OperationID)
		if err != nil {
			errs <- err
			return
		}
		for k, v := range resolveRequestOptions(opts.Options).headers {
			headers[k] = v
		}
		headers["Accept"] = streamMediaType
		if len(query) > 0 {
			rawURL = appendQueryString(rawURL, query)
		}
		var bodyReader io.Reader
		if bodyBytes != nil {
			bodyReader = bytes.NewReader(bodyBytes)
		}
		req, err := http.NewRequestWithContext(ctx, method, rawURL, bodyReader)
		if err != nil {
			errs <- err
			return
		}
		for k, v := range headers {
			req.Header.Set(k, v)
		}
		resp, err := httpClient.Do(req)
		if err != nil {
			errs <- &SdkNetworkError{Cause: err}
			return
		}
		defer resp.Body.Close()
		if resp.StatusCode < 200 || resp.StatusCode >= 300 {
			body, _ := io.ReadAll(resp.Body)
			respHeaders := flattenHeaders(resp.Header)
			errs <- &SdkHttpError{
				StatusCode: resp.StatusCode,
				StatusText: resp.Status,
				Body:       body,
				Headers:    respHeaders,
				RequestID:  findRequestID(respHeaders),
			}
			return
		}
		if streamFormat == "chunked" {
			chunk := make([]byte, 32*1024)
			for {
				n, readErr := resp.Body.Read(chunk)
				if n > 0 {
					data := ""
					if chunkDomain == "text" {
						data = string(chunk[:n])
					}
					if chunkDomain != "text" {
						data = string(chunk[:n])
					}
					events <- SdkStreamEvent{Event: "chunk", Data: data}
				}
				if readErr == io.EOF {
					return
				}
				if readErr != nil {
					errs <- &SdkNetworkError{Cause: readErr}
					return
				}
			}
		}
		reader := bufio.NewReader(resp.Body)
		if streamFormat == "ndjson" {
			for {
				line, readErr := reader.ReadString('\n')
				// A JSON text sequence record also starts with RS.
				line = strings.TrimPrefix(strings.TrimSpace(line), "\x1e")
				if line != "" {
					events <- SdkStreamEvent{Event: "message", Data: line}
				}
				if readErr == io.EOF {
					return
				}
				if readErr != nil {
					errs <- &SdkNetworkError{Cause: readErr}
					return
				}
			}
		}
		var (
			eventName  string
			eventID    string
			eventRetry int
			dataLines  []string
		)
		flush := func() {
			if len(dataLines) == 0 {
				eventName = ""
				return
			}
			ev := SdkStreamEvent{
				Event: defaultEventName(eventName),
				Data:  strings.Join(dataLines, "\n"),
				ID:    eventID,
				Retry: eventRetry,
			}
			select {
			case <-ctx.Done():
			case events <- ev:
			}
			eventName = ""
			dataLines = nil
		}
		for {
			line, err := reader.ReadString('\n')
			if len(line) > 0 {
				trimmed := strings.TrimRight(line, "\r\n")
				if trimmed == "" {
					flush()
				} else {
					parseSseLine(trimmed, &eventName, &eventID, &eventRetry, &dataLines)
				}
			}
			if err == io.EOF {
				flush()
				return
			}
			if err != nil {
				errs <- &SdkNetworkError{Cause: err}
				return
			}
		}
	}()
	return events, errs
}

func defaultEventName(name string) string {
	if name == "" {
		return "message"
	}
	return name
}

func parseSseLine(line string, eventName, eventID *string, eventRetry *int, dataLines *[]string) {
	if strings.HasPrefix(line, ":") {
		return
	}
	colon := strings.IndexByte(line, ':')
	var field, value string
	if colon == -1 {
		field = line
	} else {
		field = line[:colon]
		value = line[colon+1:]
		if strings.HasPrefix(value, " ") {
			value = value[1:]
		}
	}
	switch field {
	case "event":
		*eventName = value
	case "data":
		*dataLines = append(*dataLines, value)
	case "id":
		*eventID = value
	case "retry":
		if n, err := strconv.Atoi(value); err == nil {
			*eventRetry = n
		}
	}
}

// StreamTyped wraps Stream and JSON-decodes each event's Data into T. Stops
// on the OpenAI/Anthropic-style `[DONE]` sentinel. Generated streaming
// methods call this so consumers iterate typed event payloads (not raw
// strings) on the returned channel.
func StreamTyped[T any](ctx context.Context, method, path string, opts *RequestOpts) (<-chan T, <-chan error) {
	return StreamTypedCfg[T](ctx, GetConfig(), method, path, opts)
}

// StreamTypedWithFormat decodes a stream using explicit framing metadata.
func StreamTypedWithFormat[T any](ctx context.Context, method, path string, opts *RequestOpts, streamFormat, streamMediaType, chunkDomain string) (<-chan T, <-chan error) {
	return StreamTypedCfgWithFormat[T](ctx, GetConfig(), method, path, opts, streamFormat, streamMediaType, chunkDomain)
}

// StreamTypedCfg is the explicit-config form of StreamTyped. Instance methods
// use it so their base URL, auth, timeout, and middleware configuration cannot
// silently fall back to the global client.
func StreamTypedCfg[T any](ctx context.Context, cfg *ClientConfig, method, path string, opts *RequestOpts) (<-chan T, <-chan error) {
	return StreamTypedCfgWithFormat[T](ctx, cfg, method, path, opts, "sse", "text/event-stream", "text")
}

// StreamTypedCfgWithFormat is the explicit-config, format-aware form of StreamTyped.
func StreamTypedCfgWithFormat[T any](ctx context.Context, cfg *ClientConfig, method, path string, opts *RequestOpts, streamFormat, streamMediaType, chunkDomain string) (<-chan T, <-chan error) {
	out := make(chan T, 16)
	errs := make(chan error, 1)
	go func() {
		defer close(out)
		defer close(errs)
		eventStream, errStream := StreamCfgWithFormat(ctx, cfg, method, path, opts, streamFormat, streamMediaType, chunkDomain)
		for {
			select {
			case <-ctx.Done():
				return
			case ev, ok := <-eventStream:
				if !ok {
					return
				}
				if ev.Data == "[DONE]" {
					return
				}
				var encoded []byte
				if streamFormat == "chunked" {
					var err error
					if chunkDomain == "text" {
						encoded, err = json.Marshal(ev.Data)
					} else {
						encoded, err = json.Marshal([]byte(ev.Data))
					}
					if err != nil {
						errs <- err
						return
					}
				} else {
					encoded = []byte(ev.Data)
				}
				var typed T
				if err := json.Unmarshal(encoded, &typed); err != nil {
					errs <- err
					return
				}
				select {
				case <-ctx.Done():
					return
				case out <- typed:
				}
			case err, ok := <-errStream:
				if !ok {
					continue
				}
				if err != nil {
					errs <- err
					return
				}
			}
		}
	}()
	return out, errs
}

// WaitForConfig configures the WaitFor polling helper. Polling starts at
// Interval and doubles (with jitter) up to MaxInterval. If Timeout elapses
// before reaching a terminal state, WaitFor returns a SdkTimeoutError.
type WaitForConfig struct {
	Interval    time.Duration
	MaxInterval time.Duration
	Timeout     time.Duration
}

var defaultWaitFor = WaitForConfig{
	Interval:    1 * time.Second,
	MaxInterval: 30 * time.Second,
	Timeout:     10 * time.Minute,
}

// WaitForTerminal describes whether a poll has reached a final state. Failed
// resolves with a typed SdkNetworkError carrying the reason.
type WaitForTerminal struct {
	Done   bool
	Failed bool
	Reason string
}

// WaitFor polls a long-running operation until terminal. The caller supplies
// a poll function (typically a Get<X> method) and a predicate that classifies
// each result. Returns the final result, or an error on timeout/failure.
func WaitFor[T any](ctx context.Context, poll func(context.Context) (T, error), isTerminal func(T) WaitForTerminal, cfg *WaitForConfig) (T, error) {
	var zero T
	c := defaultWaitFor
	if cfg != nil {
		if cfg.Interval > 0 {
			c.Interval = cfg.Interval
		}
		if cfg.MaxInterval > 0 {
			c.MaxInterval = cfg.MaxInterval
		}
		if cfg.Timeout > 0 {
			c.Timeout = cfg.Timeout
		}
	}
	deadline := time.Now().Add(c.Timeout)
	interval := c.Interval
	for {
		select {
		case <-ctx.Done():
			return zero, &SdkNetworkError{Cause: ctx.Err()}
		default:
		}
		result, err := poll(ctx)
		if err != nil {
			return zero, err
		}
		state := isTerminal(result)
		if state.Done {
			if state.Failed {
				return zero, &SdkNetworkError{Cause: fmt.Errorf("operation failed: %s", state.Reason)}
			}
			return result, nil
		}
		if time.Now().After(deadline) {
			return zero, &SdkTimeoutError{Elapsed: c.Timeout}
		}
		jitter := time.Duration(mrand.Int63n(int64(c.Interval)))
		wait := interval + jitter
		if wait > c.MaxInterval {
			wait = c.MaxInterval
		}
		waitOrCancel(ctx, wait)
		interval *= 2
		if interval > c.MaxInterval {
			interval = c.MaxInterval
		}
	}
}

var piiKeys = map[string]struct{}{"authorization": {}, "cookie": {}, "set_cookie": {}, "setcookie": {}, "password": {}, "passcode": {}, "secret": {}, "token": {}, "api_key": {}, "apikey": {}, "access_token": {}, "accesstoken": {}, "refresh_token": {}, "refreshtoken": {}, "client_secret": {}, "clientsecret": {}, "email": {}, "email_address": {}, "emailaddress": {}, "phone": {}, "phone_number": {}, "phonenumber": {}, "address": {}, "street_address": {}, "streetaddress": {}, "street": {}, "city": {}, "postal_code": {}, "postalcode": {}, "zip_code": {}, "zipcode": {}, "first_name": {}, "firstname": {}, "last_name": {}, "lastname": {}, "full_name": {}, "fullname": {}, "username": {}, "user_name": {}, "ip": {}, "ip_address": {}, "ipaddress": {}, "user_agent": {}, "useragent": {}, "referrer": {}, "url": {}, "uri": {}, "query": {}, "latitude": {}, "longitude": {}, "ssn": {}, "social_security_number": {}, "socialsecuritynumber": {}, "tax_id": {}, "taxid": {}, "national_id": {}, "nationalid": {}, "passport_number": {}, "passportnumber": {}, "date_of_birth": {}, "dateofbirth": {}, "birth_date": {}, "birthdate": {}, "headers": {}, "body": {}, "request_headers": {}, "requestheaders": {}, "request_body": {}, "requestbody": {}}

// Word runs matched anywhere inside a key (`billingEmail`, `stripe_secret_key`).
var piiSegments = []string{"_password_", "_passwd_", "_passphrase_", "_secret_", "_token_", "_api_key_", "_access_token_", "_refresh_token_", "_client_secret_", "_authorization_", "_cookie_", "_set_cookie_", "_credential_", "_private_key_", "_access_key_", "_session_id_", "_card_number_", "_credit_card_", "_cvv_", "_cvc_", "_email_", "_email_address_", "_phone_", "_phone_number_", "_address_", "_street_address_", "_postal_code_", "_zip_code_", "_first_name_", "_last_name_", "_full_name_", "_user_name_", "_user_agent_", "_ssn_", "_social_security_number_", "_tax_id_", "_national_id_", "_passport_number_", "_passport_", "_date_of_birth_", "_birth_date_", "_birthdate_", "_dob_"}

// normalizePiiKey turns `stripeSecretKey`, `API-Key` and `first name` into
// `stripe_secret_key`, `api_key` and `first_name`.
func normalizePiiKey(key string) string {
	var out strings.Builder
	var previous rune
	for _, char := range key {
		if unicode.IsUpper(char) && (unicode.IsLower(previous) || unicode.IsDigit(previous)) {
			out.WriteByte('_')
		}
		if unicode.IsLetter(char) || unicode.IsDigit(char) {
			out.WriteRune(unicode.ToLower(char))
		} else {
			out.WriteByte('_')
		}
		previous = char
	}
	return out.String()
}

func isPiiKey(key string) bool {
	normalized := normalizePiiKey(key)
	if _, sensitive := piiKeys[normalized]; sensitive {
		return true
	}
	padded := "_" + normalized + "_"
	for _, segment := range piiSegments {
		if strings.Contains(padded, segment) {
			return true
		}
	}
	return false
}

// sanitizeTelemetry recursively redacts common credential and direct-identifier
// fields while preserving the shape of the telemetry payload.
func sanitizeTelemetry(value any, enabled bool) any {
	if !enabled || value == nil {
		return value
	}
	switch v := value.(type) {
	case map[string]any:
		out := make(map[string]any, len(v))
		for key, item := range v {
			if isPiiKey(key) {
				out[key] = "[REDACTED]"
			} else {
				out[key] = sanitizeTelemetry(item, enabled)
			}
		}
		return out
	case []any:
		out := make([]any, len(v))
		for i, item := range v {
			out[i] = sanitizeTelemetry(item, enabled)
		}
		return out
	}
	// JSON-compatible values often arrive through typed slices or maps (for
	// example []string or map[string]string). Walk those shapes too, while
	// preserving []byte because encoding/json gives it its standard base64 form.
	rv := reflect.ValueOf(value)
	switch rv.Kind() {
	case reflect.Map:
		if rv.Type().Key().Kind() != reflect.String {
			return value
		}
		out := make(map[string]any, rv.Len())
		iter := rv.MapRange()
		for iter.Next() {
			key := iter.Key().String()
			item := iter.Value().Interface()
			if isPiiKey(key) {
				out[key] = "[REDACTED]"
			} else {
				out[key] = sanitizeTelemetry(item, enabled)
			}
		}
		return out
	case reflect.Slice, reflect.Array:
		if rv.Type().Elem().Kind() == reflect.Uint8 {
			return value
		}
		out := make([]any, rv.Len())
		for i := 0; i < rv.Len(); i++ {
			out[i] = sanitizeTelemetry(rv.Index(i).Interface(), enabled)
		}
		return out
	default:
		return value
	}
}
