// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import "context"

type GetSummaryParams struct {
	Interval        *string
	From            *string
	To              *string
	Recompute       *bool
	Project         *string
	Language        *string
	Editor          *string
	OperatingSystem *string
	Machine         *string
	Label           *string
}

// GetSummary retrieves a summary of activity for the requested interval or date range. Use `from` and `to` to define the period, and apply project, language, editor, operating system, machine, or label filters to narrow the summary.
//
// Parameters:
//
//	interval: Interval identifier
//	from: Start date (e.g. '2021-02-07')
//	to: End date (e.g. '2021-02-08')
//	recompute: Whether to recompute the summary from raw heartbeat or use cache
//	project: Project to filter by
//	language: Language to filter by
//	editor: Editor to filter by
//	operatingSystem: OS to filter by
//	machine: Machine to filter by
//	label: Project label to filter by
func GetSummary(ctx context.Context, clientConfig ClientConfig, params GetSummaryParams, opts ...RequestOption) (*ModelsSummary, error) {
	interval := params.Interval
	from := params.From
	to := params.To
	recompute := params.Recompute
	project := params.Project
	language := params.Language
	editor := params.Editor
	operatingSystem := params.OperatingSystem
	machine := params.Machine
	label := params.Label

	resp, err := DoCfg[ModelsSummary](ctx, &clientConfig, "GET", "/summary", &RequestOpts{
		Query: map[string]any{
			"interval":         QueryValue{Value: interval, Style: "form", Explode: true},
			"from":             QueryValue{Value: from, Style: "form", Explode: true},
			"to":               QueryValue{Value: to, Style: "form", Explode: true},
			"recompute":        QueryValue{Value: recompute, Style: "form", Explode: true},
			"project":          QueryValue{Value: project, Style: "form", Explode: true},
			"language":         QueryValue{Value: language, Style: "form", Explode: true},
			"editor":           QueryValue{Value: editor, Style: "form", Explode: true},
			"operating_system": QueryValue{Value: operatingSystem, Style: "form", Explode: true},
			"machine":          QueryValue{Value: machine, Style: "form", Explode: true},
			"label":            QueryValue{Value: label, Style: "form", Explode: true},
		},
		OperationID: "GetSummary",
		Options:     opts,
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}
