// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import (
	"context"
	"fmt"
)

// GetWakatimeLeaders lists users ranked by coding activity in descending order. Use this endpoint to retrieve the leaderboard, including its ranking data, current-user information, and range metadata.
//
// Mimics https://wakatime.com/developers#leaders
func GetWakatimeLeaders(ctx context.Context, clientConfig ClientConfig, opts ...RequestOption) (*V1LeadersViewModel, error) {

	resp, err := DoCfg[V1LeadersViewModel](ctx, &clientConfig, "GET", "/compat/wakatime/v1/leaders", &RequestOpts{
		OperationID: "GetWakatimeLeaders",
		Options:     opts,
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

type GetWakatimeUserParams struct {
	User string
}

// GetWakatimeUser retrieves a user's profile information. Set `user` to a user ID or `current` to retrieve the profile associated with the authenticated user.
//
// Mimics https://wakatime.com/developers#users
//
// Parameters:
//
//	user: User ID to fetch (or 'current')
func GetWakatimeUser(ctx context.Context, clientConfig ClientConfig, params GetWakatimeUserParams, opts ...RequestOption) (*V1UserViewModel, error) {
	user := params.User

	resp, err := DoCfg[V1UserViewModel](ctx, &clientConfig, "GET", fmt.Sprintf("/compat/wakatime/v1/users/%s", EncodePathSegment(user)), &RequestOpts{
		OperationID: "GetWakatimeUser",
		Options:     opts,
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

type GetAllTimeParams struct {
	User string
}

// GetAllTime retrieves a user's coding-time summary for all time since today. Set `user` to a user ID or `current` to select the user whose summary you want.
//
// Mimics https://wakatime.com/developers#all_time_since_today
//
// Parameters:
//
//	user: User ID to fetch data for (or 'current')
func GetAllTime(ctx context.Context, clientConfig ClientConfig, params GetAllTimeParams, opts ...RequestOption) (*V1AllTimeViewModel, error) {
	user := params.User

	resp, err := DoCfg[V1AllTimeViewModel](ctx, &clientConfig, "GET", fmt.Sprintf("/compat/wakatime/v1/users/%s/all_time_since_today", EncodePathSegment(user)), &RequestOpts{
		OperationID: "GetAllTime",
		Options:     opts,
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

type GetWakatimeProjectsParams struct {
	User string
	Q    *string
}

// GetWakatimeProjects lists a user's projects. Set `user` to a user ID or `current`, and optionally use `q` to filter the projects.
//
// Mimics https://wakatime.com/developers#projects
//
// Parameters:
//
//	user: User ID to fetch data for (or 'current')
//	q: Query to filter projects by
func GetWakatimeProjects(ctx context.Context, clientConfig ClientConfig, params GetWakatimeProjectsParams, opts ...RequestOption) (*V1ProjectsViewModel, error) {
	user := params.User
	q := params.Q

	resp, err := DoCfg[V1ProjectsViewModel](ctx, &clientConfig, "GET", fmt.Sprintf("/compat/wakatime/v1/users/%s/projects", EncodePathSegment(user)), &RequestOpts{
		Query: map[string]any{
			"q": QueryValue{Value: q, Style: "form", Explode: true},
		},
		OperationID: "GetWakatimeProjects",
		Options:     opts,
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

type GetWakatimeProjectParams struct {
	User string
	Id   string
}

// GetWakatimeProject retrieves a single project for a specified user. Provide `user` to select the user and `id` to identify the project.
//
// Mimics undocumented endpoint related to https://wakatime.com/developers#projects
//
// Parameters:
//
//	user: User ID to fetch data for (or 'current')
//	id: Project ID to fetch
func GetWakatimeProject(ctx context.Context, clientConfig ClientConfig, params GetWakatimeProjectParams, opts ...RequestOption) (*V1ProjectViewModel, error) {
	user := params.User
	id := params.Id

	resp, err := DoCfg[V1ProjectViewModel](ctx, &clientConfig, "GET", fmt.Sprintf("/compat/wakatime/v1/users/%s/projects/%s", EncodePathSegment(user), EncodePathSegment(id)), &RequestOpts{
		OperationID: "GetWakatimeProject",
		Options:     opts,
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

type GetWakatimesTatsParams struct {
	User            string
	Range_          *string
	Project         *string
	Language        *string
	Editor          *string
	OperatingSystem *string
	Machine         *string
	Label           *string
}

// GetWakatimesTats retrieves coding-activity statistics for a user over a selected interval. Use the optional query parameters to filter the statistics by project, language, editor, operating system, machine, or project label.
//
// Mimics https://wakatime.com/developers#stats
//
// Parameters:
//
//	user: User ID to fetch data for (or 'current')
//	range_: Range interval identifier
//	project: Project to filter by
//	language: Language to filter by
//	editor: Editor to filter by
//	operatingSystem: OS to filter by
//	machine: Machine to filter by
//	label: Project label to filter by
func GetWakatimesTats(ctx context.Context, clientConfig ClientConfig, params GetWakatimesTatsParams, opts ...RequestOption) (*V1StatsViewModel, error) {
	user := params.User
	range_ := params.Range_
	project := params.Project
	language := params.Language
	editor := params.Editor
	operatingSystem := params.OperatingSystem
	machine := params.Machine
	label := params.Label

	resp, err := DoCfg[V1StatsViewModel](ctx, &clientConfig, "GET", fmt.Sprintf("/compat/wakatime/v1/users/%s/stats/%s", EncodePathSegment(user), EncodePathSegment(range_)), &RequestOpts{
		Query: map[string]any{
			"project":          QueryValue{Value: project, Style: "form", Explode: true},
			"language":         QueryValue{Value: language, Style: "form", Explode: true},
			"editor":           QueryValue{Value: editor, Style: "form", Explode: true},
			"operating_system": QueryValue{Value: operatingSystem, Style: "form", Explode: true},
			"machine":          QueryValue{Value: machine, Style: "form", Explode: true},
			"label":            QueryValue{Value: label, Style: "form", Explode: true},
		},
		OperationID: "GetWakatimesTats",
		Options:     opts,
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

type GetWakatimeSummariesParams struct {
	User            string
	Range_          *string
	Start           *string
	End             *string
	Project         *string
	Language        *string
	Editor          *string
	OperatingSystem *string
	Machine         *string
	Label           *string
}

// GetWakatimeSummaries retrieves WakaTime-compatible summaries for a specified user. Use `range` or the `start` and `end` dates to select a period, and apply project, language, editor, operating system, machine, or label filters to narrow the results.
//
// Mimics https://wakatime.com/developers#summaries.
//
// Parameters:
//
//	user: User ID to fetch data for (or 'current')
//	range_: Range interval identifier
//	start: Start date (e.g. '2021-02-07')
//	end: End date (e.g. '2021-02-08')
//	project: Project to filter by
//	language: Language to filter by
//	editor: Editor to filter by
//	operatingSystem: OS to filter by
//	machine: Machine to filter by
//	label: Project label to filter by
func GetWakatimeSummaries(ctx context.Context, clientConfig ClientConfig, params GetWakatimeSummariesParams, opts ...RequestOption) (*V1SummariesViewModel, error) {
	user := params.User
	range_ := params.Range_
	start := params.Start
	end := params.End
	project := params.Project
	language := params.Language
	editor := params.Editor
	operatingSystem := params.OperatingSystem
	machine := params.Machine
	label := params.Label

	resp, err := DoCfg[V1SummariesViewModel](ctx, &clientConfig, "GET", fmt.Sprintf("/compat/wakatime/v1/users/%s/summaries", EncodePathSegment(user)), &RequestOpts{
		Query: map[string]any{
			"range":            QueryValue{Value: range_, Style: "form", Explode: true},
			"start":            QueryValue{Value: start, Style: "form", Explode: true},
			"end":              QueryValue{Value: end, Style: "form", Explode: true},
			"project":          QueryValue{Value: project, Style: "form", Explode: true},
			"language":         QueryValue{Value: language, Style: "form", Explode: true},
			"editor":           QueryValue{Value: editor, Style: "form", Explode: true},
			"operating_system": QueryValue{Value: operatingSystem, Style: "form", Explode: true},
			"machine":          QueryValue{Value: machine, Style: "form", Explode: true},
			"label":            QueryValue{Value: label, Style: "form", Explode: true},
		},
		OperationID: "GetWakatimeSummaries",
		Options:     opts,
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

type GetWakatimeUseragentsParams struct {
	User string
}

// GetWakatimeUseragents lists the unique user agents recorded for a specified user. Use the `user` path parameter to select the user whose agent history you want to inspect.
//
// Mimics https://wakatime.com/developers#user_agents
//
// Parameters:
//
//	user: User ID to fetch data for (or 'current')
func GetWakatimeUseragents(ctx context.Context, clientConfig ClientConfig, params GetWakatimeUseragentsParams, opts ...RequestOption) (*V1UserAgentsViewModel, error) {
	user := params.User

	resp, err := DoCfg[V1UserAgentsViewModel](ctx, &clientConfig, "GET", fmt.Sprintf("/compat/wakatime/v1/users/%s/user_agents", EncodePathSegment(user)), &RequestOpts{
		OperationID: "GetWakatimeUseragents",
		Options:     opts,
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}

type StatusbarParams struct {
	User string
}

// Statusbar retrieves today's activity summary for a specified user in a status-bar-compatible format. Use the `user` path parameter to select the user whose current-day activity you want to view.
//
// Mimics https://wakatime.com/api/v1/users/current/statusbar/today. Have no official documentation
//
// Parameters:
//
//	user: User ID to fetch data for (or 'current')
func Statusbar(ctx context.Context, clientConfig ClientConfig, params StatusbarParams, opts ...RequestOption) (*V1StatusBarViewModel, error) {
	user := params.User

	resp, err := DoCfg[V1StatusBarViewModel](ctx, &clientConfig, "GET", fmt.Sprintf("/users/%s/statusbar/today", EncodePathSegment(user)), &RequestOpts{
		OperationID: "Statusbar",
		Options:     opts,
	})
	if err != nil {
		return nil, err
	}
	return &resp.Data, nil
}
