// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import "context"

type BadgesNamespace struct {
	config ClientConfig
}

func NewBadgesNamespace(config ClientConfig) *BadgesNamespace {
	return &BadgesNamespace{
		config: config,
	}
}

// Get retrieves badge data for a user, interval, and filter in a format compatible with Shields.io. Use `interval` to choose the aggregation period and `filter` to select an entity such as a project or language; public data access must be enabled for the user.
//
// Retrieve total time for a given entity (e.g. a project) within a given range (e.g. one week) in a format compatible with [Shields.io](https://shields.io/endpoint). Requires public data access to be allowed.
//
// Parameters:
//
//	user: User ID to fetch data for
//	interval: Interval to aggregate data for
//	filter: Filter to apply (e.g. 'project:wakapi' or 'language:Go')
func (sdk *BadgesNamespace) Get(ctx context.Context, params GetBadgeParams, opts ...RequestOption) (*V1BadgeData, error) {
	return GetBadge(ctx, sdk.config, params, opts...)
}

type WakatimeNamespace struct {
	config ClientConfig
}

func NewWakatimeNamespace(config ClientConfig) *WakatimeNamespace {
	return &WakatimeNamespace{
		config: config,
	}
}

// GetLeaders lists users ranked by coding activity in descending order. Use this endpoint to retrieve the leaderboard, including its ranking data, current-user information, and range metadata.
//
// Mimics https://wakatime.com/developers#leaders
func (sdk *WakatimeNamespace) GetLeaders(ctx context.Context, opts ...RequestOption) (*V1LeadersViewModel, error) {
	return GetWakatimeLeaders(ctx, sdk.config, opts...)
}

// GetUser retrieves a user's profile information. Set `user` to a user ID or `current` to retrieve the profile associated with the authenticated user.
//
// Mimics https://wakatime.com/developers#users
//
// Parameters:
//
//	user: User ID to fetch (or 'current')
func (sdk *WakatimeNamespace) GetUser(ctx context.Context, params GetWakatimeUserParams, opts ...RequestOption) (*V1UserViewModel, error) {
	return GetWakatimeUser(ctx, sdk.config, params, opts...)
}

// GetAllTime retrieves a user's coding-time summary for all time since today. Set `user` to a user ID or `current` to select the user whose summary you want.
//
// Mimics https://wakatime.com/developers#all_time_since_today
//
// Parameters:
//
//	user: User ID to fetch data for (or 'current')
func (sdk *WakatimeNamespace) GetAllTime(ctx context.Context, params GetAllTimeParams, opts ...RequestOption) (*V1AllTimeViewModel, error) {
	return GetAllTime(ctx, sdk.config, params, opts...)
}

// GetProjects lists a user's projects. Set `user` to a user ID or `current`, and optionally use `q` to filter the projects.
//
// Mimics https://wakatime.com/developers#projects
//
// Parameters:
//
//	user: User ID to fetch data for (or 'current')
//	q: Query to filter projects by
func (sdk *WakatimeNamespace) GetProjects(ctx context.Context, params GetWakatimeProjectsParams, opts ...RequestOption) (*V1ProjectsViewModel, error) {
	return GetWakatimeProjects(ctx, sdk.config, params, opts...)
}

// GetProject retrieves a single project for a specified user. Provide `user` to select the user and `id` to identify the project.
//
// Mimics undocumented endpoint related to https://wakatime.com/developers#projects
//
// Parameters:
//
//	user: User ID to fetch data for (or 'current')
//	id: Project ID to fetch
func (sdk *WakatimeNamespace) GetProject(ctx context.Context, params GetWakatimeProjectParams, opts ...RequestOption) (*V1ProjectViewModel, error) {
	return GetWakatimeProject(ctx, sdk.config, params, opts...)
}

// GetTats retrieves coding-activity statistics for a user over a selected interval. Use the optional query parameters to filter the statistics by project, language, editor, operating system, machine, or project label.
//
// Mimics https://wakatime.com/developers#stats
//
// Parameters:
//
//	user: User ID to fetch data for (or 'current')
//	range_: Range interval identifier
//	project: Project to filter by
//	language: Language to filter by
//	editor: Editor to filter by
//	operatingSystem: OS to filter by
//	machine: Machine to filter by
//	label: Project label to filter by
func (sdk *WakatimeNamespace) GetTats(ctx context.Context, params GetWakatimesTatsParams, opts ...RequestOption) (*V1StatsViewModel, error) {
	return GetWakatimesTats(ctx, sdk.config, params, opts...)
}

// GetSummaries retrieves WakaTime-compatible summaries for a specified user. Use `range` or the `start` and `end` dates to select a period, and apply project, language, editor, operating system, machine, or label filters to narrow the results.
//
// Mimics https://wakatime.com/developers#summaries.
//
// Parameters:
//
//	user: User ID to fetch data for (or 'current')
//	range_: Range interval identifier
//	start: Start date (e.g. '2021-02-07')
//	end: End date (e.g. '2021-02-08')
//	project: Project to filter by
//	language: Language to filter by
//	editor: Editor to filter by
//	operatingSystem: OS to filter by
//	machine: Machine to filter by
//	label: Project label to filter by
func (sdk *WakatimeNamespace) GetSummaries(ctx context.Context, params GetWakatimeSummariesParams, opts ...RequestOption) (*V1SummariesViewModel, error) {
	return GetWakatimeSummaries(ctx, sdk.config, params, opts...)
}

// GetUseragents lists the unique user agents recorded for a specified user. Use the `user` path parameter to select the user whose agent history you want to inspect.
//
// Mimics https://wakatime.com/developers#user_agents
//
// Parameters:
//
//	user: User ID to fetch data for (or 'current')
func (sdk *WakatimeNamespace) GetUseragents(ctx context.Context, params GetWakatimeUseragentsParams, opts ...RequestOption) (*V1UserAgentsViewModel, error) {
	return GetWakatimeUseragents(ctx, sdk.config, params, opts...)
}

// Statusbar retrieves today's activity summary for a specified user in a status-bar-compatible format. Use the `user` path parameter to select the user whose current-day activity you want to view.
//
// Mimics https://wakatime.com/api/v1/users/current/statusbar/today. Have no official documentation
//
// Parameters:
//
//	user: User ID to fetch data for (or 'current')
func (sdk *WakatimeNamespace) Statusbar(ctx context.Context, params StatusbarParams, opts ...RequestOption) (*V1StatusBarViewModel, error) {
	return Statusbar(ctx, sdk.config, params, opts...)
}

type HeartbeatNamespace struct {
	config ClientConfig
}

func NewHeartbeatNamespace(config ClientConfig) *HeartbeatNamespace {
	return &HeartbeatNamespace{
		config: config,
	}
}

// Get lists a user's heartbeats for a specified date. Provide `date` to select the day and `user` to identify whose activity to retrieve.
//
// Parameters:
//
//	user: Username (or current)
//	date: Date
func (sdk *HeartbeatNamespace) Get(ctx context.Context, params GetHeartbeatsParams, opts ...RequestOption) (*V1HeartbeatsResult, error) {
	return GetHeartbeats(ctx, sdk.config, params, opts...)
}

// Post3 creates a single heartbeat for a user from a WakaTime-compatible request. Send the heartbeat as a JSON object; `created_at` is numeric, and the `editor` field is ignored.
//
// Parameters:
//
//	user: Username (or current)
//	aiInputTokens: Optional `integer` value serialized in the `ai_input_tokens`
//	wire field.
//	aiLineChanges: Optional `integer` value serialized in the `ai_line_changes`
//	wire field.
//	aiOutputTokens: Optional `integer` value serialized in the
//	`ai_output_tokens` wire field.
//	aiPromptLength: Optional `integer` value serialized in the
//	`ai_prompt_length` wire field.
//	aiSession: Optional `string` value serialized in the `ai_session` wire
//	field.
//	branch: Optional `string` value serialized in the `branch` wire field.
//	category: Optional `string` value serialized in the `category` wire field.
//	createdAt: https://gorm.io/docs/conventions.html#CreatedAt
//	cursorpos: Optional `integer` value serialized in the `cursorpos` wire
//	field.
//	editor: ignored because editor might be parsed differently by wakatime
//	entity: Optional `string` value serialized in the `entity` wire field.
//	humanLineChanges: Optional `integer` value serialized in the
//	`human_line_changes` wire field.
//	isWrite: Optional `boolean` value serialized in the `is_write` wire field.
//	language: Optional `string` value serialized in the `language` wire field.
//	lineAdditions: Optional `integer` value serialized in the `line_additions`
//	wire field.
//	lineDeletions: Optional `integer` value serialized in the `line_deletions`
//	wire field.
//	lineno: Optional `integer` value serialized in the `lineno` wire field.
//	lines: Optional `integer` value serialized in the `lines` wire field.
//	machine: ignored because wakatime api doesn't return machines currently
//	operatingSystem: ignored because os might be parsed differently by wakatime
//	project: Optional `string` value serialized in the `project` wire field.
//	projectRootCount: Optional `integer` value serialized in the
//	`project_root_count` wire field.
//	time: note: on sqlite, table will have an additional column `time_real`,
//	introduced "manually" by migration 20260111 see
//	https://github.com/muety/wakapi/issues/882 for details
//	type_: Optional `string` value serialized in the `type` wire field.
//	userAgent: Optional `string` value serialized in the `user_agent` wire
//	field.
func (sdk *HeartbeatNamespace) Post3(ctx context.Context, params PostHeartbeat3Params, opts ...RequestOption) (any, error) {
	return PostHeartbeat3(ctx, sdk.config, params, opts...)
}

// Post7 creates multiple heartbeats for a user from a WakaTime-compatible request. Send a JSON array of heartbeat objects; each object can include fields such as `entity`, `language`, and `created_at`.
//
// Parameters:
//
//	user: Username (or current)
func (sdk *HeartbeatNamespace) Post7(ctx context.Context, params PostHeartbeat7Params, opts ...RequestOption) (any, error) {
	return PostHeartbeat7(ctx, sdk.config, params, opts...)
}

// Post submits a single heartbeat containing activity data. Send the heartbeat as a JSON object, using fields such as `entity`, `category`, and `language` to describe the recorded activity.
//
// Parameters:
//
//	aiInputTokens: Optional `integer` value serialized in the `ai_input_tokens`
//	wire field.
//	aiLineChanges: Optional `integer` value serialized in the `ai_line_changes`
//	wire field.
//	aiOutputTokens: Optional `integer` value serialized in the
//	`ai_output_tokens` wire field.
//	aiPromptLength: Optional `integer` value serialized in the
//	`ai_prompt_length` wire field.
//	aiSession: Optional `string` value serialized in the `ai_session` wire
//	field.
//	branch: Optional `string` value serialized in the `branch` wire field.
//	category: Optional `string` value serialized in the `category` wire field.
//	createdAt: https://gorm.io/docs/conventions.html#CreatedAt
//	cursorpos: Optional `integer` value serialized in the `cursorpos` wire
//	field.
//	editor: ignored because editor might be parsed differently by wakatime
//	entity: Optional `string` value serialized in the `entity` wire field.
//	humanLineChanges: Optional `integer` value serialized in the
//	`human_line_changes` wire field.
//	isWrite: Optional `boolean` value serialized in the `is_write` wire field.
//	language: Optional `string` value serialized in the `language` wire field.
//	lineAdditions: Optional `integer` value serialized in the `line_additions`
//	wire field.
//	lineDeletions: Optional `integer` value serialized in the `line_deletions`
//	wire field.
//	lineno: Optional `integer` value serialized in the `lineno` wire field.
//	lines: Optional `integer` value serialized in the `lines` wire field.
//	machine: ignored because wakatime api doesn't return machines currently
//	operatingSystem: ignored because os might be parsed differently by wakatime
//	project: Optional `string` value serialized in the `project` wire field.
//	projectRootCount: Optional `integer` value serialized in the
//	`project_root_count` wire field.
//	time: note: on sqlite, table will have an additional column `time_real`,
//	introduced "manually" by migration 20260111 see
//	https://github.com/muety/wakapi/issues/882 for details
//	type_: Optional `string` value serialized in the `type` wire field.
//	userAgent: Optional `string` value serialized in the `user_agent` wire
//	field.
func (sdk *HeartbeatNamespace) Post(ctx context.Context, params PostHeartbeatParams, opts ...RequestOption) (any, error) {
	return PostHeartbeat(ctx, sdk.config, params, opts...)
}

// Post5 submits multiple heartbeats in one request. Send a JSON array of heartbeat objects to record activity in bulk.
func (sdk *HeartbeatNamespace) Post5(ctx context.Context, params PostHeartbeat5Params, opts ...RequestOption) (any, error) {
	return PostHeartbeat5(ctx, sdk.config, params, opts...)
}

// Post4 submits a single heartbeat for a specified user. Send the heartbeat as a JSON object containing activity data such as `entity`, `category`, and `language`.
//
// Parameters:
//
//	user: Username (or current)
//	aiInputTokens: Optional `integer` value serialized in the `ai_input_tokens`
//	wire field.
//	aiLineChanges: Optional `integer` value serialized in the `ai_line_changes`
//	wire field.
//	aiOutputTokens: Optional `integer` value serialized in the
//	`ai_output_tokens` wire field.
//	aiPromptLength: Optional `integer` value serialized in the
//	`ai_prompt_length` wire field.
//	aiSession: Optional `string` value serialized in the `ai_session` wire
//	field.
//	branch: Optional `string` value serialized in the `branch` wire field.
//	category: Optional `string` value serialized in the `category` wire field.
//	createdAt: https://gorm.io/docs/conventions.html#CreatedAt
//	cursorpos: Optional `integer` value serialized in the `cursorpos` wire
//	field.
//	editor: ignored because editor might be parsed differently by wakatime
//	entity: Optional `string` value serialized in the `entity` wire field.
//	humanLineChanges: Optional `integer` value serialized in the
//	`human_line_changes` wire field.
//	isWrite: Optional `boolean` value serialized in the `is_write` wire field.
//	language: Optional `string` value serialized in the `language` wire field.
//	lineAdditions: Optional `integer` value serialized in the `line_additions`
//	wire field.
//	lineDeletions: Optional `integer` value serialized in the `line_deletions`
//	wire field.
//	lineno: Optional `integer` value serialized in the `lineno` wire field.
//	lines: Optional `integer` value serialized in the `lines` wire field.
//	machine: ignored because wakatime api doesn't return machines currently
//	operatingSystem: ignored because os might be parsed differently by wakatime
//	project: Optional `string` value serialized in the `project` wire field.
//	projectRootCount: Optional `integer` value serialized in the
//	`project_root_count` wire field.
//	time: note: on sqlite, table will have an additional column `time_real`,
//	introduced "manually" by migration 20260111 see
//	https://github.com/muety/wakapi/issues/882 for details
//	type_: Optional `string` value serialized in the `type` wire field.
//	userAgent: Optional `string` value serialized in the `user_agent` wire
//	field.
func (sdk *HeartbeatNamespace) Post4(ctx context.Context, params PostHeartbeat4Params, opts ...RequestOption) (any, error) {
	return PostHeartbeat4(ctx, sdk.config, params, opts...)
}

// Post8 submits multiple heartbeats for a specified user in one request. Send a JSON array of heartbeat objects to record activity in bulk.
//
// Parameters:
//
//	user: Username (or current)
func (sdk *HeartbeatNamespace) Post8(ctx context.Context, params PostHeartbeat8Params, opts ...RequestOption) (any, error) {
	return PostHeartbeat8(ctx, sdk.config, params, opts...)
}

// Post2 creates a heartbeat for the specified user. Submit a JSON object with the activity data you want to record, such as `entity`, `language`, `category`, and line-change values. The schema does not mark any heartbeat fields as required.
//
// Parameters:
//
//	user: Username (or current)
//	aiInputTokens: Optional `integer` value serialized in the `ai_input_tokens`
//	wire field.
//	aiLineChanges: Optional `integer` value serialized in the `ai_line_changes`
//	wire field.
//	aiOutputTokens: Optional `integer` value serialized in the
//	`ai_output_tokens` wire field.
//	aiPromptLength: Optional `integer` value serialized in the
//	`ai_prompt_length` wire field.
//	aiSession: Optional `string` value serialized in the `ai_session` wire
//	field.
//	branch: Optional `string` value serialized in the `branch` wire field.
//	category: Optional `string` value serialized in the `category` wire field.
//	createdAt: https://gorm.io/docs/conventions.html#CreatedAt
//	cursorpos: Optional `integer` value serialized in the `cursorpos` wire
//	field.
//	editor: ignored because editor might be parsed differently by wakatime
//	entity: Optional `string` value serialized in the `entity` wire field.
//	humanLineChanges: Optional `integer` value serialized in the
//	`human_line_changes` wire field.
//	isWrite: Optional `boolean` value serialized in the `is_write` wire field.
//	language: Optional `string` value serialized in the `language` wire field.
//	lineAdditions: Optional `integer` value serialized in the `line_additions`
//	wire field.
//	lineDeletions: Optional `integer` value serialized in the `line_deletions`
//	wire field.
//	lineno: Optional `integer` value serialized in the `lineno` wire field.
//	lines: Optional `integer` value serialized in the `lines` wire field.
//	machine: ignored because wakatime api doesn't return machines currently
//	operatingSystem: ignored because os might be parsed differently by wakatime
//	project: Optional `string` value serialized in the `project` wire field.
//	projectRootCount: Optional `integer` value serialized in the
//	`project_root_count` wire field.
//	time: note: on sqlite, table will have an additional column `time_real`,
//	introduced "manually" by migration 20260111 see
//	https://github.com/muety/wakapi/issues/882 for details
//	type_: Optional `string` value serialized in the `type` wire field.
//	userAgent: Optional `string` value serialized in the `user_agent` wire
//	field.
func (sdk *HeartbeatNamespace) Post2(ctx context.Context, params PostHeartbeat2Params, opts ...RequestOption) (any, error) {
	return PostHeartbeat2(ctx, sdk.config, params, opts...)
}

// Post6 creates multiple heartbeats for the specified user. Submit a JSON array of heartbeat objects containing the activity data you want to record. The schema does not mark any fields within the heartbeat objects as required.
//
// Parameters:
//
//	user: Username (or current)
func (sdk *HeartbeatNamespace) Post6(ctx context.Context, params PostHeartbeat6Params, opts ...RequestOption) (any, error) {
	return PostHeartbeat6(ctx, sdk.config, params, opts...)
}

type MiscNamespace struct {
	config ClientConfig
}

func NewMiscNamespace(config ClientConfig) *MiscNamespace {
	return &MiscNamespace{
		config: config,
	}
}

// GetHealth retrieves the application's health status. Use this endpoint to check the service's current health without supplying request parameters or a body.
func (sdk *MiscNamespace) GetHealth(ctx context.Context, opts ...RequestOption) (string, error) {
	return GetHealth(ctx, sdk.config, opts...)
}

type DiagnosticsNamespace struct {
	config ClientConfig
}

func NewDiagnosticsNamespace(config ClientConfig) *DiagnosticsNamespace {
	return &DiagnosticsNamespace{
		config: config,
	}
}

// Post submits a diagnostics object sent by the WakaTime CLI. Include diagnostic details such as the CLI version, platform, logs, or stack trace to provide context for the reported issue.
//
// Parameters:
//
//	architecture: Optional `string` value serialized in the `architecture` wire
//	field.
//	cliVersion: Optional `string` value serialized in the `cli_version` wire
//	field.
//	id: Optional `integer` value serialized in the `id` wire field.
//	logs: Optional `string` value serialized in the `logs` wire field.
//	platform: Optional `string` value serialized in the `platform` wire field.
//	plugin: Optional `string` value serialized in the `plugin` wire field.
//	stacktrace: Optional `string` value serialized in the `stacktrace` wire
//	field.
func (sdk *DiagnosticsNamespace) Post(ctx context.Context, params PostDiagnosticsParams, opts ...RequestOption) (any, error) {
	return PostDiagnostics(ctx, sdk.config, params, opts...)
}

type SummaryNamespace struct {
	config ClientConfig
}

func NewSummaryNamespace(config ClientConfig) *SummaryNamespace {
	return &SummaryNamespace{
		config: config,
	}
}

// Get retrieves a summary of activity for the requested interval or date range. Use `from` and `to` to define the period, and apply project, language, editor, operating system, machine, or label filters to narrow the summary.
//
// Parameters:
//
//	interval: Interval identifier
//	from: Start date (e.g. '2021-02-07')
//	to: End date (e.g. '2021-02-08')
//	recompute: Whether to recompute the summary from raw heartbeat or use cache
//	project: Project to filter by
//	language: Language to filter by
//	editor: Editor to filter by
//	operatingSystem: OS to filter by
//	machine: Machine to filter by
//	label: Project label to filter by
func (sdk *SummaryNamespace) Get(ctx context.Context, params GetSummaryParams, opts ...RequestOption) (*ModelsSummary, error) {
	return GetSummary(ctx, sdk.config, params, opts...)
}

type Wakapi struct {
	Badges      *BadgesNamespace
	Wakatime    *WakatimeNamespace
	Heartbeat   *HeartbeatNamespace
	Misc        *MiscNamespace
	Diagnostics *DiagnosticsNamespace
	Summary     *SummaryNamespace
}

func NewWakapi(config ClientConfig) *Wakapi {
	return &Wakapi{
		Badges:      NewBadgesNamespace(config),
		Wakatime:    NewWakatimeNamespace(config),
		Heartbeat:   NewHeartbeatNamespace(config),
		Misc:        NewMiscNamespace(config),
		Diagnostics: NewDiagnosticsNamespace(config),
		Summary:     NewSummaryNamespace(config),
	}
}
